-- Seed KSL lookup table from KSL.csv
INSERT INTO ksl (ksl_name)
VALUES
  ('A Great Big World'),
  ('Above & Beyond'),
  ('AC/DC'),
  ('Adele'),
  ('Aeroplane'),
  ('Afrojack'),
  ('Aimee Mann'),
  ('Air'),
  ('Alan Jackson'),
  ('Alison Moyet'),
  ('Alphaville'),
  ('Ani DiFranco'),
  ('Arcade Fire'),
  ('Aretha Franklin'),
  ('Armin Van Buuren'),
  ('Atmosphere'),
  ('The Avett Brothers'),
  ('Avicii'),
  ('The B-52s'),
  ('Bach'),
  ('Backstreet Boys'),
  ('Bad Company'),
  ('Band of Horses'),
  ('Barenaked Ladies'),
  ('Barry White'),
  ('Bassbot'),
  ('Bassnectar'),
  ('Bauer'),
  ('Beck'),
  ('Berlin'),
  ('Beth Orton'),
  ('Beverly Hills Cop'),
  ('Big and Rich'),
  ('Billie Holiday'),
  ('Bjork'),
  ('Black Keys'),
  ('Blockhead'),
  ('Blonde Redhead'),
  ('Blood Sweat & Tears'),
  ('Blur'),
  ('Bob Dylan'),
  ('Bombay Bicycle Club'),
  ('Bootsy Collins'),
  ('Boys Noize'),
  ('Brandi Carlile'),
  ('Braveheart'),
  ('Brett Dennen'),
  ('Bro Safari'),
  ('Broken Bells'),
  ('Bruce Hornsby'),
  ('Bruckner'),
  ('Bruno Mars'),
  ('Busta Rhymes'),
  ('Cafe del Mar'),
  ('Calvin Harris'),
  ('Carole King'),
  ('Carrie Underwood'),
  ('Cassius'),
  ('Chaka Khan'),
  ('Chemical Brothers'),
  ('Chic'),
  ('Chicago'),
  ('Chromeo'),
  ('Coldplay'),
  ('Com Truise'),
  ('Counting Crows'),
  ('Creedence Clearwater Revival'),
  ('Daft Punk'),
  ('Dam Funk'),
  ('Dan Fogelberg'),
  ('Daniel Portman'),
  ('Danny Brown'),
  ('Danny Elfman'),
  ('Darkest Appalachia'),
  ('Darkside'),
  ('Darude'),
  ('Datsik'),
  ('Dave Matthews Band'),
  ('David Arnold'),
  ('David Guetta'),
  ('Deadmau5'),
  ('Death Cab for Cutie'),
  ('Debussy'),
  ('Deee-Lite'),
  ('Deepest'),
  ('Deftones'),
  ('Depeche Mode'),
  ('Dick Dale'),
  ('Dido'),
  ('Dionne Warwick'),
  ('Disclosure'),
  ('Dixie'),
  ('The Chicks'),
  ('DJ Khaled'),
  ('DJ Shadow'),
  ('DJ Sneak'),
  ('Dogs'),
  ('Donna Lewis'),
  ('Drake'),
  ('Duran Duran'),
  ('Dwight Yoakam'),
  ('Early Bee Gees'),
  ('Early U2'),
  ('Edward Sharpe & The Magnetic Zeros'),
  ('Edwin McCain'),
  ('Ellie Goulding'),
  ('Elliot Goldenthal'),
  ('Electric Light Orchestra'),
  ('Emiliana Torrini'),
  ('Eminem'),
  ('Ennio Morricone'),
  ('Erasure'),
  ('Erik Satie'),
  ('Evanescence'),
  ('Excision'),
  ('Fall Out Boy'),
  ('Feed Me'),
  ('Feist'),
  ('Fiona Apple'),
  ('Five for Fighting'),
  ('Flo Rida'),
  ('Florence and The Machine'),
  ('Flying Lotus'),
  ('Forrest Gump'),
  ('Frou Frou'),
  ('Funkadelic'),
  ('Genesis'),
  ('George Harrison'),
  ('Goldfrapp'),
  ('Goo Goo Dolls'),
  ('Grocer'),
  ('Gotye'),
  ('Grace Potter'),
  ('Gram Parsons'),
  ('Grateful Dead'),
  ('Green Day'),
  ('Greg Laswell'),
  ('Groove Collective'),
  ('Guy Clark'),
  ('Gym Class Heroes'),
  ('Hall and Oates'),
  ('Hans Zimmer'),
  ('Hay'),
  ('Herbie Hancock'),
  ('Hollywood Undead'),
  ('Hot Chip'),
  ('Howard Jones'),
  ('Howard Shore'),
  ('The Human League'),
  ('Immortal Technique'),
  ('Imogen Heap'),
  ('Incubus'),
  ('Ingrid Michaelson'),
  ('Irene Cara'),
  ('Isaac Hayes'),
  ('J Dilla'),
  ('Jack Johnson'),
  ('Jackson Browne'),
  ('James Brown'),
  ('James McMurtry'),
  ('James Morrison'),
  ('James Newton Howard'),
  ('James Taylor'),
  ('Jamie Woon'),
  ('Jamiroquai'),
  ('Jason Mraz'),
  ('Jay-Z'),
  ('Jeff Lorber Fusion'),
  ('Jefferson Airplane'),
  ('Jerry Lee Lewis'),
  ('Jet'),
  ('Jewel'),
  ('Jimi Hendrix'),
  ('Joe Jackson'),
  ('John Barry'),
  ('John Hiatt'),
  ('John Legend'),
  ('John Mayer'),
  ('John Mellencamp'),
  ('John Prine'),
  ('John Williams'),
  ('Johnny and June'),
  ('Johnny Cash'),
  ('Joni Mitchell'),
  ('Journey'),
  ('Juana Molina'),
  ('June Carter'),
  ('Justice'),
  ('Justin Timberlake'),
  ('Kaskade'),
  ('Katy Perry'),
  ('Keith Urban'),
  ('Kelly Clarkson'),
  ('Kings of Leon'),
  ('Kiss'),
  ('Kruder & Dorfmeister'),
  ('Lady Gaga'),
  ('Laidback Luke'),
  ('Legowelt'),
  ('Lenny Kravitz'),
  ('Lil Wayne'),
  ('Linda Ronstadt'),
  ('Lindstrom'),
  ('Living Colour'),
  ('Lullabies'),
  ('Madonna'),
  ('Mahler'),
  ('Marc Cohn'),
  ('Mariah Carey'),
  ('Marilyn Manson'),
  ('Mark Knopfler'),
  ('Martha and the Vandellas'),
  ('Martin Garrix'),
  ('Mary Wells'),
  ('Massive Attack'),
  ('Matchbox Twenty'),
  ('Maxwell'),
  ('Metallica'),
  ('MGMT'),
  ('Michael Jackson'),
  ('Ministry'),
  ('Moby'),
  ('Mogwai'),
  ('Monsters & Men'),
  ('Morcheeba'),
  ('Moza'),
  ('Mozart'),
  ('MSTRKRFT'),
  ('Mumford & Sons'),
  ('Muse'),
  ('Nas'),
  ('Natalie Maines'),
  ('Neil Diamond'),
  ('Neon Trees'),
  ('Nero'),
  ('New Order'),
  ('Nickelback'),
  ('Nik Kershaw'),
  ('Nile Rodgers'),
  ('Nine Inch Nails'),
  ('Nino Rota'),
  ('No Doubt'),
  ('Noah and The Whale'),
  ('Nosaj Thing'),
  ('NSYNC'),
  ('O.A.R'),
  ('Olive'),
  ('Orgy'),
  ('Oxfords'),
  ('Palestrina'),
  ('Parliament'),
  ('Patsy Cline'),
  ('Pearl Jam'),
  ('Peggy Lee'),
  ('Pepper'),
  ('Peter Frampton'),
  ('Peter Gabriel'),
  ('Pharrell'),
  ('Phil Collins'),
  ('Philip Glass'),
  ('Philip Phillips'),
  ('Phoenix'),
  ('Pit Bull'),
  ('Porter Robinson'),
  ('Portishead'),
  ('Prairie Home Companion'),
  ('Prince'),
  ('Psy'),
  ('Psychedelic Furs'),
  ('Q-tip'),
  ('Quentin Tarantino'),
  ('R3hab'),
  ('Radiohead'),
  ('Rascal Flatts'),
  ('Ravel'),
  ('Reba McEntire'),
  ('Rebelution'),
  ('Rebirth Brass Band'),
  ('Red Hot Chili Peppers'),
  ('REM'),
  ('Ricardo Villalobos'),
  ('Rick Ross'),
  ('Ruth Brown'),
  ('RZA'),
  ('Sam Smith'),
  ('Santana'),
  ('Sarah McLachlan'),
  ('Scandal'),
  ('Sebastian'),
  ('Sex Pistols'),
  ('Shania Twain'),
  ('Sheryl Crow'),
  ('Shostakovich'),
  ('Sia'),
  ('Sigur Ros'),
  ('Simian Mobile Disco'),
  ('Simon & Garfunkel'),
  ('Skrillex'),
  ('Slaid Cleaves'),
  ('Soja'),
  ('Soulwax'),
  ('Southside Johnny'),
  ('Steely Dan'),
  ('Steve Winwood'),
  ('Stevie Ray Vaughan'),
  ('Stevie Wonder'),
  ('Stevie Wonder'),
  ('Stevie Wonder'),
  ('Sub Focus'),
  ('Sublime'),
  ('Swedish House Mafia'),
  ('Taylor Swift'),
  ('Tchaikovsky'),
  ('Tears For Fears'),
  ('The Allman Brothers'),
  ('The Black Crowes'),
  ('The Black Lillies'),
  ('The Cardigans'),
  ('The Carter Family'),
  ('The Dark Hills of West Virginny'),
  ('The Diplomats'),
  ('The Doobie Brothers'),
  ('The Doors'),
  ('The Eagles'),
  ('The Hives'),
  ('The Lumineers'),
  ('The Mighty Mighty Bosstones'),
  ('The Moody Blues'),
  ('The Offspring'),
  ('The Pointer Sisters'),
  ('The Ramones'),
  ('The Shins'),
  ('The Streets'),
  ('The Strokes'),
  ('The Supremes'),
  ('The Time'),
  ('The Unicorns'),
  ('The Vaccines'),
  ('The Ventures'),
  ('The Ventures (on acid)'),
  ('The Vines'),
  ('Thin Lizzy'),
  ('Thomas Newman'),
  ('Tiesto'),
  ('Til'' Tuesday'),
  ('Tim McGraw'),
  ('Timbaland'),
  ('Tina Turner'),
  ('Todd Terje'),
  ('Tom Petty'),
  ('Tommy Shaw'),
  ('Tori Amos'),
  ('Tower of Power'),
  ('Tracey Thorn'),
  ('Trent Reznor & Atticus Ross'),
  ('Tricky'),
  ('U2'),
  ('Usher'),
  ('Wagner'),
  ('Wall of Voodoo'),
  ('Weezer'),
  ('Whitney Houston'),
  ('Wilco'),
  ('Wolfgang Gartner'),
  ('Wu Tang Clan'),
  ('Young Jeezy'),
  ('Yvonne Elliman'),
  ('Zedd'),
  ('Zee Avi'),
  ('Zero 7'),
  ('ZZ Top'),
  ('Cindy Lauper'),
  ('Dolly Parton'),
  ('Jeff Buckley'),
  ('The Jesus and Mary Chain'),
  ('The Secret Machines'),
  ('Willie Nelson'),
  ('Jackson Browne'),
  ('The Beatles'),
  ('John Powell'),
  ('Harold Faltermeyer'),
  ('Lightning Hopkins'),
  ('Johnny Winter'),
  ('B.B. King'),
  ('Ry Cooder'),
  ('Robert Johnson'),
  ('Albert King'),
  ('Robert Johnson'),
  ('The Chemical Brothers'),
  ('Tan Dun'),
  ('Dead Can Dance'),
  ('Sade'),
  ('Gigi'),
  ('Céu'),
  ('Marisa Monte'),
  ('Gotan Project'),
  ('Astor Piazzolla'),
  ('Narcotango'),
  ('Bajofondo'),
  ('Gustavo Santolalla'),
  ('Hank Williams'),
  ('Kanye West'),
  ('Lana Del Rey'),
  ('Regina Spektor'),
  ('Cat Power'),
  ('Steve Jablonsky'),
  ('Harry Gregson-Williams'),
  ('Len'),
  ('EMF'),
  ('The Cinematic Orchestra'),
  ('Steve Reich'),
  ('Queens of the Stone Age'),
  ('Kraftwerk'),
  ('College and Electric Youth'),
  ('Kavinsky'),
  ('The Monkees'),
  ('Herman''s Hermits'),
  ('Cream'),
  ('Eric Clapton'),
  ('The Outlaws'),
  ('Remember a lover'),
  ('Peter Frampton'),
  ('Pink Floyd'),
  ('Carlos Santana'),
  ('Pink'),
  ('Blink 182'),
  ('Rihanna'),
  ('Tiesto'),
  ('Daniel Portman'),
  ('Droplex'),
  ('Carl Cox'),
  ('Kaskade'),
  ('Mark Knight'),
  ('Flight Facilities'),
  ('Goldroom'),
  ('Purity Ring'),
  ('MSTRKRFT'),
  ('Sara Bareilles'),
  ('Regina Spektor'),
  ('The Glitch Mob'),
  ('Flosstradamus'),
  ('50 Cent'),
  ('The Game'),
  ('Alexandre Desplat'),
  ('Heitor Pereira'),
  ('Ted Nugent'),
  ('Molly Hatchet'),
  ('David Grey'),
  ('Pink Floyd'),
  ('Alan Parsons'),
  ('Barenaked Ladies'),
  ('Smash Mouth'),
  ('Jess Penner'),
  ('Theodore Shapiro'),
  ('David Wax Museum'),
  ('Windham Hill'),
  ('Sufjan Stevens'),
  ('Dropkick Murphys'),
  ('The Pogues'),
  ('Don Henley'),
  ('Bill Withers'),
  ('Otis Redding'),
  ('Jimmy Buffet'),
  ('George Thorogood'),
  ('Phish'),
  ('The Kinks'),
  ('Little Feat'),
  ('The Fray'),
  ('Of Monsters and Men'),
  ('Grand Funk Railroad'),
  ('Billy Idol'),
  ('The Cult'),
  ('Howlin'' Wolf'),
  ('Joe Satriani'),
  ('Tom Waits'),
  ('Leonard Cohen'),
  ('Gogol Bordello'),
  ('John Lurie'),
  ('Motley Crue'),
  ('David Bowie'),
  ('Albert Collins'),
  ('Harold Faltermeyer'),
  ('Giorgio Moroder'),
  ('Slayer'),
  ('Machine Head'),
  ('Huey Lewis and the News'),
  ('The Romantics'),
  ('The J. Geils Band'),
  ('Loverboy'),
  ('Dick Dale'),
  ('Bill Monroe'),
  ('Lynyrd Skynyrd'),
  ('Dave Porter'),
  ('Iggy Pop'),
  ('Killing Joke'),
  ('Gang Of Four'),
  ('Mercury Rev'),
  ('Little Walter'),
  ('Otis Spann'),
  ('Black Sabbath'),
  ('Morphine'),
  ('Dick Dale'),
  ('Ozzy Osbourne'),
  ('Led Zeppelin'),
  ('Van Halen'),
  ('Poison'),
  ('Deep Purple'),
  ('Megadeth'),
  ('Edith Piaf'),
  ('Cafe de Paris'),
  ('Squeeze'),
  ('Difford & Tilbrook'),
  ('Thomas Dolby'),
  ('Scandal'),
  ('The Rolling Stones'),
  ('The Cars'),
  ('Tito & Tarantula'),
  ('Bush'),
  ('Soundgarden'),
  ('Sting'),
  ('Jack White'),
  ('The WHO'),
  ('Alice Cooper'),
  ('Pat Metheny'),
  ('Yaz'),
  ('John Powell'),
  ('Bela Fleck'),
  ('Tony Trishka'),
  ('Matthew Sweet'),
  ('Marvin Gaye'),
  ('Motown Stax'),
  ('Donny Hathaway'),
  ('Aphex Twin'),
  ('alt-J'),
  ('Iron Maiden'),
  ('Aaron Copland'),
  ('Mark Mothersbaugh'),
  ('Pantera'),
  ('Yes'),
  ('Foo Fighters'),
  ('Phoenix'),
  ('Henry Mancini'),
  ('Christmas'),
  ('Whitesnake'),
  ('Def Leppard'),
  ('Aerosmith'),
  ('Bon Jovi'),
  ('Death Cab For Cutie'),
  ('Passion Pit'),
  ('Vampire Weekend'),
  ('The Postal Service'),
  ('Stone Temple Pilots'),
  ('Stax'),
  ('60''s Soul'),
  ('Sam and Dave'),
  ('The Tubes'),
  ('Dave Grisman'),
  ('Lee "Scratch" Perry'),
  ('Bob Marley'),
  ('Jimmy Cliff'),
  ('The English Beat'),
  ('Eric Burden'),
  ('60''s Blues'),
  ('Van Morrison'),
  ('Kansas'),
  ('Power Station'),
  ('The Fabulous Thunderbirds'),
  ('The E Street Band'),
  ('Scandal'),
  ('Pat Benatar'),
  ('Berlin'),
  ('Culture Club'),
  ('Wham!'),
  ('Guns & Roses'),
  ('fun.'),
  ('The Georgia Satellites'),
  ('Survivor'),
  ('Fela'),
  ('Youssou N''Dour'),
  ('Zap Mama'),
  ('Paul Simon'),
  ('Filter'),
  ('Joe Walsh'),
  ('Ronnie James Dio'),
  ('Augustus Pablo'),
  ('Demian Marley'),
  ('Augustus Pablo'),
  ('Diplo'),
  ('Earth Wind & Fire'),
  ('Al Jarreau'),
  ('Blondie'),
  ('Gary Glitter'),
  ('Avril Lavigne'),
  ('Katy Perry'),
  ('INXS'),
  ('The Cure'),
  ('The Pretenders'),
  ('Nathan Barr'),
  ('Old Crow Medicine Show'),
  ('Old 97''s'),
  ('Bruce Cockburn'),
  ('Steve Miller Band'),
  ('70''s Laurel Canyon'),
  ('David Crosby'),
  ('CSNY'),
  ('Jan Hammer'),
  ('Flock of Seagulls'),
  ('Rage Against The Machine'),
  ('Avenged Sevenfold'),
  ('Mudvayne'),
  ('Disturbed'),
  ('Five Finger Death Punch'),
  ('T. Rex'),
  ('Yann Tiersen'),
  ('Devotchka'),
  ('Rod Stewart'),
  ('Robert Palmer'),
  ('Warren Zevon'),
  ('Living Colour'),
  ('John Fogerty'),
  ('Eric Church'),
  ('Midnight Oil'),
  ('Boston'),
  ('Edgar Winter'),
  ('My Life With The Thrill Kill Kult'),
  ('Joan Jett and the Blackhearts'),
  ('Gary Glitter'),
  ('Heart'),
  ('The Clash'),
  ('Nirvana'),
  ('Lyle Lovett'),
  ('Slaid Cleaves'),
  ('Bush'),
  ('Gin Blossoms'),
  ('Rick Springfield'),
  ('The Knack'),
  ('Tom Morello'),
  ('Mark Isham'),
  ('Alison Krauss'),
  ('The Vapors'),
  ('Bob Seger'),
  ('The Killers'),
  ('Billy Squier'),
  ('Tim McGraw'),
  ('Kid Rock'),
  ('Jerry Lee Lewis'),
  ('Paul Butterfield Blues Band'),
  ('Little Walter'),
  ('Blues Traveler'),
  ('The Byrds'),
  ('Waylon Jennings'),
  ('Ryan Adams'),
  ('Twisted Sister'),
  ('Cheap Trick'),
  ('The Police'),
  ('Buckcherry'),
  ('Steven Price'),
  ('Alice In Chains'),
  ('Bon Iver'),
  ('The Civil Wars'),
  ('Cat Stevens'),
  ('Simple Minds'),
  ('Tears For Fears'),
  ('The Stooges'),
  ('Gipsy Kings'),
  ('The Traveling Wilburys'),
  ('The Dixie Dregs'),
  ('Good Charlotte'),
  ('All American Rejects'),
  ('Jimmy Eat World'),
  ('Everclear'),
  ('Harvey Danger'),
  ('Cake'),
  ('Black Rebel Motorcycle Club'),
  ('The Nutcracker'),
  ('Harry Potter'),
  ('Collective Soul'),
  ('Tonic'),
  ('Better Than Ezra'),
  ('Toad The Wet Sprocket'),
  ('Everclear'),
  ('Muddy Waters'),
  ('P.O.D.'),
  ('Marshall Crenshaw'),
  ('The Smithereens'),
  ('Nick Lowe'),
  ('Korn'),
  ('The Verve Pipe'),
  ('Toad The Wet Sprocket'),
  ('Elmore James'),
  ('Marcy Playground'),
  ('Tommy Castro'),
  ('The Band'),
  ('Young The Giant'),
  ('Walk The Moon'),
  ('Ben Folds'),
  ('The Beach Boys'),
  ('Buddy Guy'),
  ('Bronze Radio Returns'),
  ('The Cranberries'),
  ('Sam Bush'),
  ('David Grisman'),
  ('Lefty Frizell'),
  ('Henry Mancini'),
  ('Imagine Dragons'),
  ('Violent Femmes'),
  ('Bonnie Raitt'),
  ('NFL Films'),
  ('The Breeders'),
  ('Dire Straits'),
  ('Buddy Holly'),
  ('Ronnie Hawkins'),
  ('Brian Setzer'),
  ('Chuck Berry'),
  ('Jeff Beck'),
  ('Stray Cats'),
  ('Fleetwood Mac'),
  ('Slipknot'),
  ('Calexico'),
  ('Bruce Springsteen'),
  ('The Wallflowers'),
  ('Dave Clark Five'),
  ('Flying Burrito Brothers'),
  ('Glenn Frey'),
  ('Bee Gees'),
  ('Donna Summer'),
  ('The O''jays'),
  ('Strawberry Alarm Clock'),
  ('Donovan'),
  ('King Curtis'),
  ('Martin and Wood'),
  ('Booker T.'),
  ('Kenny Loggins'),
  ('Ambrosia'),
  ('The Zombies'),
  ('The Holding Company'),
  ('Polyphonic Spree'),
  ('Flaming Lips'),
  ('The Hollies'),
  ('Procol Harum'),
  ('Los Bravos'),
  ('Anita Baker'),
  ('The Pointer Sisters'),
  ('Fairport Convention'),
  ('The Waterboys'),
  ('Otis Redding'),
  ('Paula Abdul'),
  ('Isaac Hayes'),
  ('Quincy Jones'),
  ('Miami Sound Machine'),
  ('The Turtles'),
  ('The Commodores'),
  ('The Troggs'),
  ('Third Eye Blind'),
  ('Burt Bacharach'),
  ('Herb Alpert & the TJB'),
  ('Veruca Salt'),
  ('The Breeders'),
  ('Kenny G.'),
  ('The Jackson 5'),
  ('Gary Clark Jr.'),
  ('The Animals'),
  ('Foreigner'),
  ('Michael Kamen'),
  ('Elvis Costello'),
  ('Natalie Imbruglia'),
  ('Frank Zappa'),
  ('Randy Newman'),
  ('Postal Service'),
  ('George Duke'),
  ('Lady A'),
  ('Michael Penn'),
  ('Bollywood'),
  ('Disney Movie'),
  ('Animation / Cartoon'),
  ('The Breeders'),
  ('Austin Powers'),
  ('The Bangles'),
  ('The Talking Heads'),
  ('Sean Paul'),
  ('Marc Anthony'),
  ('J Lo'),
  ('Afro Jack'),
  ('Afro Celt'),
  ('Boston'),
  ('Live'),
  ('The Smashing Pumpkins'),
  ('Fountains of Wayne'),
  ('The Hooters'),
  ('Julian Lennon'),
  ('Michael Penn'),
  ('Los Lobos'),
  ('Annie Lennox'),
  ('Arctic Monkeys'),
  ('Modern English'),
  ('Appalachia'),
  ('Punch Brothers'),
  ('Doc Watson'),
  ('New Grass Revival'),
  ('Leo Kottke'),
  ('G. Love and Special Sauce'),
  ('Hot Tuna'),
  ('Don Swidinsky'),
  ('Cracker'),
  ('St. Paul and The Broken Bones'),
  ('Kenny Chesney'),
  ('Loretta Lynn'),
  ('Vance Joy'),
  ('Sugarland'),
  ('Miranda Lambet'),
  ('Tito Puente'),
  ('Sheila E'),
  ('A Drum Circle'),
  ('Lalo Schifrin'),
  ('Black Veil Brides'),
  ('Max Richter'),
  ('CJ Chenier'),
  ('Doug Kershaw'),
  ('bauhaus'),
  ('T Bone Burnett'),
  ('Dr. John'),
  ('James Horner'),
  ('Buckwheat Zydeco'),
  ('James Bond'),
  ('Disney'),
  ('Chet Atkins'),
  ('Emmylou Harris'),
  ('Didgeridoos'),
  ('David Hudson'),
  ('World Percussion'),
  ('Scott Joplin'),
  ('Eurythmics'),
  ('Basement Jaxx'),
  ('Mister Mister'),
  ('Buffalo Springfield'),
  ('John Carpenter'),
  ('Harry Nilsson'),
  ('Merle Haggard'),
  ('Preservation Hall Jazz Band'),
  ('Blake Shelton'),
  ('Jason Bourne'),
  ('Little Green Cars'),
  ('Patty Griffin'),
  ('Black Eyed Peas'),
  ('Linkin Park'),
  ('Carter Burwell'),
  ('Orchestral Manoeuvres in the Dark'),
  ('The Brothers Johnson'),
  ('Boz Scaggs'),
  ('Alexander Courage'),
  ('Sean Callery'),
  ('Stone Roses'),
  ('Velvet Revolver'),
  ('Gordon Lightfoot'),
  ('Zac Brown Band'),
  ('Buck Owens'),
  ('George Jones'),
  ('38 Special'),
  ('5 Seconds Of Summer'),
  ('Brian Eno'),
  ('Paul Anka'),
  ('The Ronettes'),
  ('Al Di Meola'),
  ('The Fixx'),
  ('Cage The Elephant'),
  ('Cage the Elephant'),
  ('Kaleo'),
  ('The Record Company'),
  ('Faces'),
  ('Motorhead'),
  ('System of a Down'),
  ('New York Dolls'),
  ('Mott the Hoople'),
  ('Jefferson Starship'),
  ('Barry Manilow'),
  ('The Go Go''s'),
  ('Stephen Foster'),
  ('Lou Reed'),
  ('Morphine'),
  ('Urge Overkill'),
  ('Tangerine Dream'),
  ('Colbie Caillat'),
  ('Circus Music'),
  ('Malcolm Arnold'),
  ('George Winston'),
  ('Hot Chocolate'),
  ('Sam Cooke'),
  ('Curtis Mayfield'),
  ('Wild Cherry'),
  ('Ohio Players'),
  ('Peter Frampton'),
  ('Chris Stapleton'),
  ('Arlo Guthrie'),
  ('Gillian Welsh'),
  ('Memphis Slim'),
  ('Los Lonely Boys'),
  ('Cliff Martinez'),
  ('How To Destroy Angels'),
  ('Alan Silvestri'),
  ('Kevin Riepl'),
  ('Jamie Christopherson'),
  ('Fatboy Slim'),
  ('The Specials'),
  ('UB40'),
  ('Roy Orbison'),
  ('Brad Fiedel'),
  ('Wolfmother'),
  ('Robert Rodriguez'),
  ('Trace Adkins'),
  ('Neil Young'),
  ('Derek and the Dominos'),
  ('Jethro Tull'),
  ('Audioslave'),
  ('Mountain'),
  ('The Hold Steady'),
  ('Social Distortion'),
  ('David Holmes'),
  ('Kyle Dixon & Michael Stein'),
  ('Stranger Things'),
  ('Daniel Licht'),
  ('Jack Wall (Mass Effect)'),
  ('Airborne Toxic Event'),
  ('Blue Oyster Cult'),
  ('Jane''s Addiction'),
  ('Reel Big Fish'),
  ('The Dirty Heads'),
  ('Fishbone'),
  ('Ramin Djawadi'),
  ('Alan Menken'),
  ('Koji Kondo (Nintendo)'),
  ('Tom Jones'),
  ('Johnny Mathis'),
  ('Dinosaur Jr.'),
  ('Extreme'),
  ('Jerry Goldsmith'),
  ('Kenji Yamamoto (Metroid)'),
  ('Harry Manfredini'),
  ('Olafur Arnalds'),
  ('Dead Boys'),
  ('Alabama Shakes'),
  ('10000 Maniacs'),
  ('Morrissey'),
  ('The Church'),
  ('The Smiths'),
  ('Billy Joel'),
  ('Elton John'),
  ('Primus'),
  ('A. R. Rahman'),
  ('Rush'),
  ('Styx'),
  ('Ed Sheeran'),
  ('Oasis'),
  ('Breaking Benjamin'),
  ('Robert Cray'),
  ('Anthrax'),
  ('Queensryche'),
  ('Neil Sedaka'),
  ('Sugar Hill Gang'),
  ('Grandmaster Flash'),
  ('Run DMC'),
  ('Monster Magnet'),
  ('Alice in Chains (Jar of Flies)'),
  ('Frank Turner'),
  ('Days of the New'),
  ('White Zombie'),
  ('Dream Theater'),
  ('Gene Loves Jezebel'),
  ('The Misfits'),
  ('Rick Derringer'),
  ('Montrose'),
  ('Akira Yamaoka (Silent Hill)'),
  ('X Ambassadors'),
  ('Tesla'),
  ('Twenty One Pilots'),
  ('Suicidal Tendencies'),
  ('Bad Religion'),
  ('The Runaways'),
  ('Beastie Boys'),
  ('Big Audio Dynamite'),
  ('Michael Giacchino'),
  ('Psapp'),
  ('Ray LaMontagne'),
  ('The Band Perry'),
  ('Dixie Chicks'),
  ('Bob Mould'),
  ('Husker Du'),
  ('The Replacements'),
  ('Soul Asylum'),
  ('Manuel Galban'),
  ('Jake Owen'),
  ('Sonic Youth'),
  ('John Lee Hooker'),
  ('Iron & Wine'),
  ('Boots Randolph'),
  ('Keith Richards'),
  ('Augustana'),
  ('Oingo Boingo'),
  ('The Pixies'),
  ('John Debney'),
  ('Dirty Pretty Things'),
  ('Les Paul'),
  ('Merle Travis'),
  ('James Vincent McMorrow'),
  ('Ben Howard'),
  ('My Chemical Romance'),
  ('Kaiser Chiefs'),
  ('The Black Keys'),
  ('The White Stripes'),
  ('Willie Dixon'),
  ('Mad Season'),
  ('The Yardbirds'),
  ('The Temptations'),
  ('America'),
  ('The Lion King'),
  ('Carmina Burana'),
  ('Hoobastank'),
  ('George Michael'),
  ('David First'),
  ('Keane'),
  ('James Blunt'),
  ('Kodaline'),
  ('Maroon 5'),
  ('Eric Serra'),
  ('Muzak'),
  ('AFI'),
  ('Shinedown'),
  ('Bastille'),
  ('Tyler Bates & Tree Adams'),
  ('Rainbow'),
  ('UFO'),
  ('The Scorpions'),
  ('Fuel'),
  ('Paramore'),
  ('Passenger'),
  ('Average White Band'),
  ('Steppenwolf'),
  ('Vanilla Fudge'),
  ('Queen'),
  ('Ben Harper'),
  ('Matt Kearney'),
  ('Traffic'),
  ('Focus'),
  ('Ed Sheerin'),
  ('Indigo Girls'),
  ('Agent Orange'),
  ('Benny Hill'),
  ('Frank Worth'),
  ('Bernard Herrmann'),
  ('Eve 6'),
  ('Eddie Vedder'),
  ('Emerson Lake and Palmer'),
  ('Damn Yankees'),
  ('Lin Manuel Miranda'),
  ('311'),
  ('Satan'),
  ('Eric Whitacre'),
  ('Johann Sebastian Bach'),
  ('Church Music'),
  ('Gregorian Chant'),
  ('Game of Thrones'),
  ('Clint Mansell'),
  ('Three Doors Down'),
  ('Limp Bizkit'),
  ('Lit'),
  ('Train'),
  ('Technotronic'),
  ('CID'),
  ('Kim Wilde'),
  ('Devo'),
  ('Enrique Iglesias'),
  ('Eric Johnson'),
  ('D''Arcangelo'),
  ('Al Green'),
  ('Sister Hazel'),
  ('Toby Keith'),
  ('Uncle Kracker'),
  ('Brooks and Dunn'),
  ('Sweet'),
  ('Slade'),
  ('Hoyt Curtin'),
  ('Yello'),
  ('Fugazi'),
  ('Deep Blue Something'),
  ('Eagle Eye Cherry'),
  ('The Crystal Method'),
  ('Ace Of Base'),
  ('Doctor Zhivago'),
  ('Lorde'),
  ('Walk Off the Earth'),
  ('Vivaldi'),
  ('Beethoven'),
  ('Gloria Gaynor'),
  ('Right Said Fred'),
  ('Handel'),
  ('The Prodigy'),
  ('Mobb Deep'),
  ('AZ'),
  ('Wiz Khalifa'),
  ('Jaylib'),
  ('Slum Village'),
  ('Black Box'),
  ('Flamin Groovies'),
  ('Technasia'),
  ('Loco Dice'),
  ('KREAM'),
  ('Jonathan Wolff'),
  ('Chopin'),
  ('Franz Liszt'),
  ('Winifred Atwell'),
  ('Thelonious Monk'),
  ('Cherry Poppin'' Daddies'),
  ('Del Shannon'),
  ('Big Bad Voodoo Daddy'),
  ('Bananarama'),
  ('Sven Vath'),
  ('Kylie Minogue'),
  ('Ricky Martin'),
  ('Juanes'),
  ('Lionel Richie'),
  ('Seal'),
  ('Rick Astley'),
  ('Simply Red'),
  ('Sam Spence'),
  ('Buddha Bar'),
  ('Jennifer Lopez'),
  ('Marshall Tucker Band'),
  ('The String Cheese Incident'),
  ('Robert Lopez'),
  ('Michael Buble'),
  ('Art of Noise'),
  ('Deadmaus'),
  ('The Marine Corp Band'),
  ('Chronos Quartet'),
  ('Kronos Quartet'),
  ('Pachelbel'),
  ('Charpentier'),
  ('Paul Oakenfold'),
  ('Heaven 17'),
  ('TWRK'),
  ('Lupe Fiasco'),
  ('Panic! at the Disco'),
  ('Franz Ferdinand'),
  ('M/A/R/R/S'),
  ('C&C Music Factory'),
  ('Spandau Ballet'),
  ('Ultravox'),
  ('Edward Elgar'),
  ('LMFAO'),
  ('Gigi D''Agostino'),
  ('Crystal Method'),
  ('La Bouche'),
  ('Dead Or Alive'),
  ('Snap!'),
  ('Gary Numan'),
  ('Information Society'),
  ('Soft Cell'),
  ('Joy Division'),
  ('George Gershwin'),
  ('Jelly Roll Morton'),
  ('Popeye The Sailor Man'),
  ('Sammy Lerner'),
  ('Birdy'),
  ('The Kooks'),
  ('The Fratellis'),
  ('Christopher Young'),
  ('John Wall'),
  ('Jan and Dean'),
  ('Jason Derulo'),
  ('Mark Ronson'),
  ('Robin Thicke'),
  ('Zebra'),
  ('Maurice Jarre'),
  ('Bachman-Turner Overdrive'),
  ('The Strumbellas'),
  ('Dishwalla'),
  ('Stevie B.'),
  ('DJ Jazzy Jeff & The Fresh Prince'),
  ('Pet Shop Boys'),
  ('Macklemore & Ryan Lewis'),
  ('Black Label Society'),
  ('Royal Blood'),
  ('Tool'),
  ('Judas Priest'),
  ('Bob Marley and The Wailers'),
  ('Alpha Blondy'),
  ('Tribal Seeds'),
  ('Antonio Carlos Jobim'),
  ('Yaz'),
  ('iiO'),
  ('DCX'),
  ('Shakira'),
  ('Headbone'),
  ('The Faranas'),
  ('The Volcanos'),
  ('Mother Love Bone'),
  ('La La Land'),
  ('Justin Hurwitz'),
  ('Richard Rogers'),
  ('Richard Rodgers'),
  ('Haydn'),
  ('Rammstein'),
  ('Nathan Furst'),
  ('Sister Sledge'),
  ('Liszt'),
  ('Brahms'),
  ('Boccherini'),
  ('Korobeiniki"(Tetris)'),
  ('John Lunn (Downton Abbey)'),
  ('stephen sondheim'),
  ('Stephen Sondheim'),
  ('Charlie Daniels Band'),
  ('Rusted Root'),
  ('Nobuo Uematsu (Final Fantasy)'),
  ('Revolution #9'),
  ('Richard Bellis'),
  ('Charles Bernstein'),
  ('Donovan Frankenreiter'),
  ('Sponge'),
  ('Propellerheads'),
  ('Gorillaz'),
  ('Frankie goes to Hollywood'),
  ('When In Rome'),
  ('Grace Jones'),
  ('Sugar'),
  ('The Lemonheads'),
  ('Garth Brooks'),
  ('Godsmack'),
  ('Brad Paisley'),
  ('Bobby Fuller'),
  ('The Four Tops'),
  ('Ike and Tina Turner'),
  ('Earl Scruggs'),
  ('One Direction'),
  ('Europe'),
  ('Edvard Grieg'),
  ('Glen Hansard'),
  ('Don Davis'),
  ('Mark Mancina'),
  ('Matisyahu'),
  ('Maxi Priest'),
  ('Michael Franti & Spearhead'),
  ('The Dirtyheads'),
  ('Peter Tosh'),
  ('Gladys Knight'),
  ('Afrika Bambaataa'),
  ('George Clinton'),
  ('The Weeknd'),
  ('Corey Hart'),
  ('Chet Baker'),
  ('Stereo MCs'),
  ('En Vogue'),
  ('Destiny''s Child'),
  ('Swing Out Sister'),
  ('John Secada'),
  ('Testament'),
  ('Elvis Presley'),
  ('Justin Bieber'),
  ('Kendrick Lamar'),
  ('Beyonce'),
  ('Golden Earring'),
  ('Clutch'),
  ('Damien Rice'),
  ('The Frames'),
  ('Dean Martin'),
  ('Introspective'),
  ('Fleet Foxes'),
  ('The Decemberists'),
  ('Neutral Milk Hotel'),
  ('The Mountain Goats'),
  ('She & Him'),
  ('Blind Melon'),
  ('Saliva'),
  ('Seether'),
  ('The Might Be Giants'),
  ('The Db''s'),
  ('Cursive'),
  ('Snoop Dogg'),
  ('Colt Ford'),
  ('Eskmo'),
  ('OK Go'),
  ('Semisonic'),
  ('The Dead Kennedys'),
  ('Phuture'),
  ('Toadies'),
  ('Bloc Party'),
  ('Mondo Generator'),
  ('Miles Davis'),
  ('Eddie Richards'),
  ('Louis Armstrong'),
  ('Stefan Grossman'),
  ('Paco de Lucia'),
  ('Staind'),
  ('Mr. Fingers'),
  ('The Sugarhill Gang'),
  ('De La Soul'),
  ('Creed'),
  ('Finger Eleven'),
  ('Gene Autry'),
  ('London Symphony Orchestra'),
  ('The Orb'),
  ('Luke Vibert'),
  ('Lindsey Buckingham'),
  ('Frankie Knuckles'),
  ('Robert Miles'),
  ('Sleeping At Last'),
  ('Novo Amor'),
  ('First Aid Kit'),
  ('Yellow Magic Orchestra'),
  ('Warp-9'),
  ('Karl The Voice'),
  ('Joe Smooth'),
  ('The Libertines'),
  ('Tom Odell'),
  ('Benjamin Francis Leftwich'),
  ('Rosie Thomas'),
  ('Rick James'),
  ('Traditional'),
  ('Alabama'),
  ('Them Crooked Vultures'),
  ('Hole'),
  ('Lil Jon'),
  ('Modest Mouse'),
  ('BoDeans'),
  ('Local H'),
  ('Silversun Pickups'),
  ('REO Speedwagon'),
  ('Yellowcard'),
  ('Imaginary Future'),
  ('Kina Grannis'),
  ('The Head and The Heart'),
  ('The Bird and The Bee'),
  ('Glen Campbell'),
  ('Don Williams'),
  ('Marty Robbins'),
  ('The Paper Kites'),
  ('Seals and Crofts'),
  ('Sly and the Family Stone'),
  ('Nazareth'),
  ('Interpol'),
  ('The Bravery'),
  ('The Desert Sessions'),
  ('Bryan Adams'),
  ('The Von Bondies'),
  ('Cybotron'),
  ('Model 500'),
  ('The Shirelles'),
  ('Blind Blake'),
  ('Dario Marianelli'),
  ('The Mamas and The Papas'),
  ('ABBA'),
  ('Coolio'),
  ('Pennywise'),
  ('Mike Post'),
  ('Dead Sara'),
  ('Cutting Crew'),
  ('Jellyfish'),
  ('Van Hagar'),
  ('Candlebox'),
  ('The KLF'),
  ('Jesus Jones'),
  ('Eagles of Death Metal'),
  ('Daughter'),
  ('The Trammps'),
  ('Cowboy Junkies'),
  ('Bizet'),
  ('Schubert'),
  ('Trevor Morris'),
  ('Courtney Barnett'),
  ('Jace Everett'),
  ('Lisa Lisa & Cult Jam'),
  ('Will to Power'),
  ('Shalamar'),
  ('Teena Marie'),
  ('Expose'),
  ('Janet Jackson'),
  ('Will.I.Am'),
  ('KeSha'),
  ('The Chainsmokers'),
  ('Nicki Minaj'),
  ('Ratt'),
  ('Mastodon'),
  ('Ram Jam'),
  ('Chris Isaak'),
  ('Stevie Nicks'),
  ('XTC'),
  ('Pete Townshend'),
  ('Dan Auerbach'),
  ('Tom Cochrane'),
  ('Bo Diddley'),
  ('The Strangeloves'),
  ('Danny and the Juniors'),
  ('Iron Butterfly'),
  ('Them'),
  ('Haircut 100'),
  ('Saves the Day'),
  ('David Gilmour'),
  ('Foghat'),
  ('Jimmy Reed'),
  ('Maxine Nightingale'),
  ('KD Lang'),
  ('Paul Revere and the Raiders'),
  ('Snow Patrol'),
  ('The Script'),
  ('Richard Strauss'),
  ('Eddie Shaw'),
  ('The Ataris'),
  ('The Vaselines'),
  ('Yeah Yeah Yeahs'),
  ('Nathaniel Rateliff & The Night Sweats'),
  ('Neal Hefti'),
  ('The Edge'),
  ('Jimmy Page'),
  ('Jerry Cantrell'),
  ('John Frusciante'),
  ('Billy Gibbons'),
  ('Weird Al Yankovic'),
  ('Cher'),
  ('Debbie Deb'),
  ('Tommy James and The Shondells'),
  ('Mazzy Star'),
  ('Dr. Dre'),
  ('LL Cool J'),
  ('Aqua'),
  ('Kool & the Gang'),
  ('Biz Markie'),
  ('John Paul Young'),
  ('Jason Hayes (Blizzard Games)'),
  ('Free'),
  ('Scott Schreer'),
  ('Sheila Cole'),
  ('Stone Sour'),
  ('Sevendust'),
  ('Volbeat'),
  ('Liz Phair'),
  ('A-ha'),
  ('Warrant'),
  ('Skid Row'),
  ('Bullet Boys'),
  ('Black Flag'),
  ('Circle Jerks'),
  ('Roxy Music'),
  ('Luther Vandross'),
  ('LeAnn Rimes'),
  ('Taking Back Sunday'),
  ('30 Seconds To Mars'),
  ('Rise Against'),
  ('Sum 41'),
  ('Richard Marx'),
  ('Big Country'),
  ('Judah & the Lion'),
  ('Hanson'),
  ('The Derek Trucks Band'),
  ('Kenny Wayne Shepherd'),
  ('Hinder'),
  ('Haddaway'),
  ('Silverchair'),
  ('Coheed and Cambria'),
  ('Fort Minor'),
  ('Spin Doctors'),
  ('808 State'),
  ('Florida Georgia Line'),
  ('Stephen Warbeck'),
  ('Portugal. The Man'),
  ('Dio'),
  ('Peret'),
  ('Rodrigo y Gabriela'),
  ('Vicente Amigo'),
  ('Dashboard Confessional'),
  ('Something Corporate'),
  ('Brand New'),
  ('The Raconteurs'),
  ('The Sundays'),
  ('The Verve'),
  ('Joe Bonamassa'),
  ('Hank Williams Jr'),
  ('Jason Aldean'),
  ('Nikolai Rimsky-Korsakov'),
  ('Norman Greenbaum'),
  ('Rob Zombie'),
  ('Primitive Radio Gods'),
  ('Mudhoney'),
  ('James Gang'),
  ('The Oneders'),
  ('Adam Clayton & Larry Mullen'),
  ('Paul Desmond'),
  ('Take 5'),
  ('Dave Brubeck'),
  ('Benny Carter'),
  ('Johnny Pearson'),
  ('E.S. Posthumus'),
  ('Nada Surf'),
  ('Body Count'),
  ('Public Enemy'),
  ('Lipps Inc'),
  ('Screaming Trees'),
  ('Great White'),
  ('W.A.S.P.'),
  ('Steve Vai'),
  ('Anti-Flag'),
  ('NOFX'),
  ('Helmet'),
  ('Soil'),
  ('Static-X'),
  ('Nonpoint'),
  ('Sepultura'),
  ('Overkill'),
  ('Obituary'),
  ('Peter Bjorn and John'),
  ('The Psychedelic Furs'),
  ('Israel Kamakawiwoole'),
  ('Clifton Chenier'),
  ('Steam'),
  ('Vanessa Carlton'),
  ('Michelle Branch'),
  ('Joe Raposo'),
  ('Carl Stalling'),
  ('Owl City'),
  ('Common'),
  ('Deuter'),
  ('Klaus Badelt'),
  ('Vitamin C'),
  ('Paul McCartney'),
  ('Jon Bellion'),
  ('Elliott Smith'),
  ('KT Tunstall'),
  ('Sonny Rhodes'),
  ('Jerry Reed'),
  ('Hamilton Leithauser'),
  ('Steve Earle'),
  ('David Schwartz'),
  ('Gramatik'),
  ('Eric B. & Rakim'),
  ('The Fat Boys'),
  ('Tone Loc'),
  ('Jurassic 5'),
  ('Irving Szathmary'),
  ('Four Tops'),
  ('The Isley Brothers'),
  ('KRS-One'),
  ('Axel Thesleff'),
  ('Rolfe Kent'),
  ('Marc Streitenfeld'),
  ('Johnny Rivers'),
  ('Paul Dukas'),
  ('Nujabes'),
  ('Rob Dougan'),
  ('Mike Jones'),
  ('Widespread Panic'),
  ('Hootie & the Blowfish'),
  ('Sixpence None the Richer'),
  ('Jim Croce'),
  ('Ravi Shankar'),
  ('Cyndi Lauper'),
  ('Charlie Parker'),
  ('Dr. Lonnie Smith'),
  ('Herbie Mann'),
  ('Clare Fischer'),
  ('Bobby Hutcherson'),
  ('Argent'),
  ('John Coltrane'),
  ('Ray Brown'),
  ('US3'),
  ('Gary Burton'),
  ('Fred Hersch'),
  ('João Gilberto'),
  ('Benny Goodman'),
  ('Bud Powell'),
  ('The Brand New Heavies'),
  ('Link Wray'),
  ('The Contours'),
  ('Rick Braun'),
  ('Maynard Ferguson'),
  ('Animotion'),
  ('Kyuss'),
  ('Death From Above 1979'),
  ('John Lennon'),
  ('RedOne'),
  ('Head East'),
  ('Vengaboys'),
  ('T.I.'),
  ('Jerry Martin (The Sims)'),
  ('Tupac Shakur'),
  ('Chuck Mangione'),
  ('The Jayhawks'),
  ('Joey DeFrancesco'),
  ('Bubba Sparxxx'),
  ('Del the Funky Homosapien'),
  ('A Tribe Called Quest'),
  ('The Pharcyde'),
  ('Erykah Badu'),
  ('Count Basie'),
  ('Buck Clayton'),
  ('Luciano Michelini'),
  ('Soyo Oka (Nintendo)'),
  ('Wolf Parade'),
  ('Crash Test Dummies'),
  ('The Bill Evans Trio'),
  ('Peace Orchestra'),
  ('Charlie Christian'),
  ('Marc Antoine'),
  ('Sam Most'),
  ('Bill Evans'),
  ('Wes Montgomery'),
  ('Wilson Pickett'),
  ('Spencer Nilsen (SEGA)'),
  ('Julius Fucik'),
  ('Mike Oldfield'),
  ('JS16'),
  ('A.C. Reed'),
  ('Jonzun Crew'),
  ('Mohombi'),
  ('Milt Franklyn'),
  ('Heatmiser'),
  ('Built to Spill'),
  ('The Cyrkle'),
  ('Terry Francis'),
  ('Masterboy'),
  ('Magic Affair'),
  ('No Mercy'),
  ('Corona'),
  ('Culture Beat'),
  ('Richie Hawtin'),
  ('RuPaul'),
  ('Marky Mark & the Funky Bunch'),
  ('Eiffel 65'),
  ('Bell Biv DeVoe'),
  ('Fast Eddie'),
  ('Jose Padilla'),
  ('Alice Deejay'),
  ('Bomfunk MC''s'),
  ('Chris Cornell'),
  ('Charlie Clouser'),
  ('Dirty Vegas'),
  ('Twenty 4 Seven'),
  ('Scott Bradley'),
  ('Seatbelts'),
  ('Jazzanova'),
  ('Robert Reich'),
  ('Duke Ellington'),
  ('Yolanda Be Cool'),
  ('Parov Stelar'),
  ('Tape Five'),
  ('Caravan Palace'),
  ('Caro Emerald'),
  ('Artie Shaw'),
  ('Glenn Miller'),
  ('The Outfield'),
  ('Ray Barretto'),
  ('Machito'),
  ('Digable Planets'),
  ('Vince Guaraldi'),
  ('Art Tatum'),
  ('Crosby, Stills, Nash & Young'),
  ('Faith No More'),
  ('The Sisters of Mercy'),
  ('Richard Elliot'),
  ('Gerald Albright'),
  ('Incognito'),
  ('James Taylor Quartet'),
  ('Grant Geissman'),
  ('The Dukes of September'),
  ('Stan Kenton'),
  ('Buddy Rich'),
  ('Groove Doktor'),
  ('Brian Tyler'),
  ('Sanseverino'),
  ('Pearl Django'),
  ('Mark Snow'),
  ('Oscar Peterson'),
  ('McCoy Tyner'),
  ('Cedar Walton'),
  ('Dizzy Gillespie'),
  ('Ron Carter'),
  ('Leaf Hound'),
  ('Heinz Kiessling'),
  ('Billy May'),
  ('Thelonious Monk'),
  ('Brother Jack McDuff'),
  ('Seven Mary Three'),
  ('Ray Charles'),
  ('Pink Martini'),
  ('David Newman'),
  ('Canned Heat'),
  ('Marc Shaiman'),
  ('The Handsome Family'),
  ('Blackfoot'),
  ('St. Germain'),
  ('Tomoyasu Hotei'),
  ('Stan Getz'),
  ('Little Richard'),
  ('Fats Domino'),
  ('Leroy Vinnegar'),
  ('Connie Francis'),
  ('Ella Fitzgerald'),
  ('Jerry Jeff Walker'),
  ('Charles Strouse'),
  ('Mel Leven'),
  ('Leonard Bernstein'),
  ('J. Cole'),
  ('Styles of Beyond'),
  ('MF Doom'),
  ('Thomas Arne'),
  ('Post Malone'),
  ('Lloyd Banks'),
  ('Kid Cudi'),
  ('Meek Mill'),
  ('Ray Dalton'),
  ('Puff Daddy'),
  ('Nelly'),
  ('Future'),
  ('ASAP MOB'),
  ('Hubert Laws'),
  ('Phil Woods'),
  ('Zoot Sims'),
  ('Jimmy Smith'),
  ('Herbie Nichols'),
  ('Jimmy Sturr'),
  ('Frankie Yankovic'),
  ('Patrick Doyle'),
  ('Space Time Continuum'),
  ('Giacomo Puccini'),
  ('King Crimson'),
  ('Tracy Chapman'),
  ('NicK Cave'),
  ('The Lounge Lizards'),
  ('Echo and the Bunnymen'),
  ('Greg Edmonson'),
  ('Alfred Newman'),
  ('Corey Harris'),
  ('The Heavy Eyes'),
  ('Robert Plant'),
  ('Shenandoah'),
  ('George Bruns'),
  ('George Strait'),
  ('Mr. President'),
  ('Nancy Sinatra'),
  ('Sonic Mayhem'),
  ('Faunts'),
  ('Raison Varner'),
  ('Monty Norman'),
  ('Buzzcocks'),
  ('Robert Folk'),
  ('Black Stone Cherry'),
  ('Brooklyn Tabernacle Choir'),
  ('Rev. James Cleveland Choir'),
  ('Akira Ifukube'),
  ('The Teardrop Explodes'),
  ('Clint Bajakian'),
  ('Stephen Flaherty'),
  ('Kirk Franklin'),
  ('Donnie McClurkin'),
  ('John P. Kee'),
  ('Yolanda Adams'),
  ('France Gall'),
  ('Mireille Mathieu'),
  ('Bow Wow Wow'),
  ('Bobby McFerrin'),
  ('George Formby'),
  ('Little Mix'),
  ('Simple Plan'),
  ('Randy Edelman'),
  ('Sharon Jones & The Dap-Kings'),
  ('Waka Flocka Flame'),
  ('Christophe Beck'),
  ('Migos'),
  ('The Shamen'),
  ('Wanz'),
  ('Young Thug'),
  ('Chief Keef'),
  ('Chris Brown'),
  ('Sultan and Shepard'),
  ('Beatmasters'),
  ('Gucci Mane'),
  ('Rozalla'),
  ('Real McCoy'),
  ('Method Man'),
  ('Fistful Of Mercy'),
  ('The Notorious B.I.G.'),
  ('Sir Walter Scott'),
  ('M.I.A.'),
  ('Wang Chung'),
  ('Lee Fields & the Expressions'),
  ('Charles Bradley'),
  ('My Morning Jacket'),
  ('The Rubinoos'),
  ('Gleaming Spires'),
  ('The Standells'),
  ('Keith Strachen'),
  ('Avancada'),
  ('Duncan Sheik'),
  ('Sammy Hagar'),
  ('The Guess Who'),
  ('John Bonham'),
  ('Adrian Younge & Ali Shaheed Muhammad'),
  ('Brian Kirk'),
  ('Nelson Riddle'),
  ('William Lava'),
  ('Howard Ashman'),
  ('Stephen Schwartz'),
  ('Fred Hammond'),
  ('Edwin Hawkins'),
  ('Tye Tribbett'),
  ('Marvin Sapp'),
  ('Morris Day'),
  ('Mississippi Mass Choir'),
  ('DMX'),
  ('The Arcs'),
  ('Tantric'),
  ('Marco Beltrami'),
  ('Bad News Brown'),
  ('Ludwig Goransson'),
  ('Outkast'),
  ('Mick Jagger'),
  ('Ira Newborn'),
  ('Transa'),
  ('PJ Harvey'),
  ('Django Reinhardt'),
  ('The Rembrandts'),
  ('Johann Strauss II'),
  ('Juliana Hatfield'),
  ('Teste'),
  ('Edwyn Collins'),
  ('The Scrantones'),
  ('J Cole'),
  ('Logic'),
  ('Clint Black'),
  ('Amy WineHouse'),
  ('N.E.R.D.'),
  ('Chamillionaire'),
  ('Garbage'),
  ('2chainz'),
  ('T-Pain'),
  ('Martin Solveig'),
  ('Germs'),
  ('The Cramps'),
  ('Johnny Thunders'),
  ('Metal Church'),
  ('Neil Peart'),
  ('Carmine Appice'),
  ('Roger Taylor'),
  ('Swizz Beats'),
  ('Mike PosnerTravie McCoy'),
  ('One Republic'),
  ('Cesar Davila-Irizarry'),
  ('Alterbridge'),
  ('Alter Bridge'),
  ('Crystal Waters'),
  ('Second Carolina String Band'),
  ('Cab Calloway'),
  ('Tyler Bates'),
  ('Selena Gomez'),
  ('Bedřich Smetana'),
  ('Ludacris'),
  ('D''Angelo'),
  ('Peter Himmelman'),
  ('Icona Pop'),
  ('The Sandals'),
  ('Kurt Bestor'),
  ('Goteki'),
  ('Fabulous Thunderbirds'),
  ('Bella''s Bartok'),
  ('Vangelis'),
  ('The Undertones'),
  ('The Kooks'),
  ('Billy and the Kids'),
  ('Ugly Kid Joe'),
  ('Louis XIV'),
  ('Tom Tom Club'),
  ('Cardi B'),
  ('Mychael Danna'),
  ('The Dead Weather'),
  ('The Pretty Reckless'),
  ('Porno For Pyros'),
  ('The Everly Brothers'),
  ('The Real McCoy'),
  ('Charli XCX'),
  ('kesha'),
  ('Graeme Norgate'),
  ('Tommee Proffit'),
  ('StoneBridge'),
  ('Corn Potato String Band'),
  ('Patrick Gilmore'),
  ('Stephen Foster'),
  ('Janek Gwizdala'),
  ('DJ Krush'),
  ('Thievery Corporation'),
  ('Cosmic'),
  ('Johann Johannsson'),
  ('Jazz Liberatorz'),
  ('Snaer'),
  ('Bullet For My Valentine'),
  ('Stereophonics'),
  ('House of Pain'),
  ('Faithless'),
  ('Royksopp'),
  ('Kerri Chandler'),
  ('Jimpster'),
  ('The Foxboro Hottubs'),
  ('Kurt Cobain'),
  ('Queens of the Stone Age'),
  ('Apocalyptica'),
  ('Dan Marocco'),
  ('Faith Hill'),
  ('CeCe Peniston'),
  ('The Newton Brothers'),
  ('Naoki'),
  ('Tech N9ne'),
  ('Trivium'),
  ('Bowling For Soup'),
  ('Dr. Octagon'),
  ('Kool Keith'),
  ('Uncle Murda'),
  ('CKY'),
  ('Shamen'),
  ('Mike Shinoda'),
  ('Nappy Roots'),
  ('DJ Starscream'),
  ('Rancid'),
  ('Awolnation'),
  ('RATT'),
  ('Double Trouble'),
  ('Neon Waltz'),
  ('Haf Bitten Moon'),
  ('Blackwater'),
  ('Ernie Ford'),
  ('Ian Hunter'),
  ('Tom Petty and the Heartbreakers'),
  ('Kasabian'),
  ('Dua Lipa'),
  ('John Hartford'),
  ('Hot Rize'),
  ('Zircon'),
  ('Knox Hamilton'),
  ('The 1975'),
  ('Fluke'),
  ('Mr. Big'),
  ('Thomas Schumacher'),
  ('LFO'),
  ('Mica Levi'),
  ('Three Dog Night'),
  ('Mississippi John Hurt'),
  ('Big Bill Broonzy'),
  ('Modjo'),
  ('Bob Sinclar'),
  ('Down'),
  ('Preacher Stone'),
  ('Gwar'),
  ('Esteban'),
  ('Biting Elbows'),
  ('Laura Barrett'),
  ('Sergei Prokofiev'),
  ('The Mighty Sparrow'),
  ('Bashiri Johnson'),
  ('Matchbook Romance'),
  ('Trevor Rabin'),
  ('Chick Corea'),
  ('Jim Brickman'),
  ('David Foster'),
  ('Zakk Wyld'),
  ('Jason & The Punknecks'),
  ('Danzig'),
  ('Coldplay'),
  ('Brantley Gilbert'),
  ('The Fallen Starlets'),
  ('Electric Wizard'),
  ('Michael Nyman'),
  ('Cornershop'),
  ('Man Alive'),
  ('David Wise (Donkey Kong Country)'),
  ('Portishead'),
  ('Morah Rocks'),
  ('Mungo Jerry'),
  ('Stewart Copeland'),
  ('G Unit'),
  ('Jun Ishikawa'),
  ('Secondhand Serenade'),
  ('Clouds And Thorns'),
  ('James Bay'),
  ('Barry Blue'),
  ('Sons Of Anarchy'),
  ('Matthew Shultz'),
  ('Marshmello'),
  ('Still Time'),
  ('Nils Frahm'),
  ('Jean Michel Jarre'),
  ('Ashra'),
  ('Los Banditos'),
  ('Enya'),
  ('6ix9ine'),
  ('John Digweed'),
  ('Mandrill'),
  ('Lionel Hampton'),
  ('Lorne Balfe'),
  ('Ariana Grande'),
  ('Rag''n''Bone Man'),
  ('David Lanz'),
  ('Jon Brion'),
  ('squarepusher'),
  ('Squarepusher'),
  ('Substantial'),
  ('Kidd Kidd'),
  ('Ladysmith Black Mambazo'),
  ('Fastball'),
  ('R.E.M'),
  ('The La''s'),
  ('The Proclaimers'),
  ('Patrick O''Hearn'),
  ('Authority Zero'),
  ('Floret'),
  ('Sergio Mendes & Brazil ‘66'),
  ('Lil Pump'),
  ('The Champs'),
  ('Karl Jenkins'),
  ('Eric Weissberg'),
  ('Emperor'),
  ('Lamb of God'),
  ('Lisa Loeb'),
  ('George Fenton'),
  ('Trevor Demaere'),
  ('Hozier'),
  ('Samiyam'),
  ('Eva Cassidy'),
  ('Alberto Ginastera'),
  ('Alannah Myles'),
  ('Stravinsky'),
  ('Janis Joplin'),
  ('Big Brother and the Holding Company'),
  ('Eric Prydz'),
  ('The Feeling'),
  ('George Ezra'),
  ('Earthless'),
  ('Killswitch Engage'),
  ('Rockwell'),
  ('Thutmose'),
  ('Marian Hill'),
  ('Laura Mvula'),
  ('Vancouver Sleep Clinic'),
  ('Otep'),
  ('Municipal Waste'),
  ('Secret Garden'),
  ('Blood Red Shoes'),
  ('John Waite'),
  ('The Dillinger Escape Plan'),
  ('D.R.I.'),
  ('Foxboro Hot Tubs'),
  ('Bring Me The Horizon'),
  ('Behemoth'),
  ('Lil Nas X'),
  ('John Paesano (Daredevil)'),
  ('Johnny Mercer'),
  ('War on Drugs'),
  ('Blind Pilot'),
  ('Buena Vista Social Club'),
  ('Gary Portnoy'),
  ('Everlast'),
  ('Greta Van Fleet'),
  ('Scorpions'),
  ('Nahko and Medicine for the People'),
  ('Chase Long Beach'),
  ('Bad Brains'),
  ('Traveling Wilburys'),
  ('The Kills'),
  ('Ryuichi Sakamoto'),
  ('Bear McCreary'),
  ('Rostam Batmanglij'),
  ('Benjamin Wallfisch'),
  ('The Impossibles'),
  ('The Forest Rangers'),
  ('Lee Ann Womack'),
  ('Dawes'),
  ('Missy Higgins'),
  ('The Carpenters'),
  ('The War On Drugs'),
  ('Hildur Guonadottir (Chernobyl)'),
  ('Blackway & Black Caviar'),
  ('The Dirty South'),
  ('Needtobreathe'),
  ('Yanni'),
  ('Nicholas Britel'),
  ('Lauren Daigle'),
  ('American Authors'),
  ('Rob Thomas'),
  ('Cowboy Troy'),
  ('The Silly Surfers'),
  ('Thomas Happ (Axiom Verge)'),
  ('Cheb Mami'),
  ('Uriah Heap'),
  ('Ghost'),
  ('Yelawolf'),
  ('The Drifters'),
  ('Robert Paterson'),
  ('Jason & The Scorchers'),
  ('All That Remains'),
  ('Josh Kramon (Veronica Mars)'),
  ('Childish Gambino'),
  ('Karizma'),
  ('Mojo Blues Band'),
  ('Travis Scott'),
  ('Trevor Jones'),
  ('Message To Bears'),
  ('Canyon City'),
  ('The Platters'),
  ('Kevin Kern'),
  ('Vertical Horizon'),
  ('Harry Styles'),
  ('Syd Barrett'),
  ('KOAN Sound'),
  ('Noisia'),
  ('Skream'),
  ('Netsky'),
  ('Sigma'),
  ('Flux Pavilion'),
  ('Chase & Status'),
  ('Blanco Brown'),
  ('Luke Bryan'),
  ('Kygo'),
  ('Georgia Satellites'),
  ('Yasunori Mitsuda (Chrono Trigger)'),
  ('Chevelle'),
  ('A Perfect Circle'),
  ('Jimpster'),
  ('Isaac Hayes'),
  ('Hot Since 82'),
  ('CamelPhat'),
  ('Solomun'),
  ('Yotto'),
  ('Klangkarussell'),
  ('Duke Dumont'),
  ('Felix Jaehn'),
  ('Robin Schulz'),
  ('Steve Aoki'),
  ('Kygo'),
  ('Claptone'),
  ('Maceo Plex'),
  ('Tchami'),
  ('Benny Benassi'),
  ('Detroit Swindle'),
  ('Fred Everything'),
  ('Andhim'),
  ('Paul van Dyk'),
  ('Paul Kalkbrenner'),
  ('Armand van Helden'),
  ('Sidney Charles'),
  ('Scott Diaz'),
  ('Nora En Pure'),
  ('Blue Six'),
  ('The Struts'),
  ('Sebastien Leger'),
  ('Oliver Schories'),
  ('Oliver Koletzki'),
  ('Nina Kravitz'),
  ('Weiss (UK)'),
  ('Leftwing : Kody'),
  ('Mark Knight'),
  ('Tube & Berger'),
  ('Dubfire'),
  ('Stephan Bodzin'),
  ('Oliver Huntemann'),
  ('Kollektiv Turmstrasse'),
  ('Marek Hemmann'),
  ('Groove Armada'),
  ('Boards of Canada'),
  ('Nighmare on Wax'),
  ('Nightmares on Wax'),
  ('Röyksopp'),
  ('Bonobo'),
  ('Cassius'),
  ('Fred Falke'),
  ('Derrick May'),
  ('20Syl'),
  ('Flume'),
  ('Moonwalk'),
  ('Pomo'),
  ('Zimmer'),
  ('Darius'),
  ('Derrick Carter'),
  ('Goldmund'),
  ('Gavin DeGraw'),
  ('Our Lady Peace'),
  ('They Might Be Giants'),
  ('Covenant'),
  ('Dimitri Vegas & Like Mike'),
  ('Hardwell'),
  ('Booka Shade'),
  ('Adam Port'),
  ('Betoko'),
  ('Schiller'),
  ('Pleasurekraft'),
  ('Benga'),
  ('Rusko'),
  ('Kode9'),
  ('Burial'),
  ('Magnetic Man'),
  ('Zeds Dead'),
  ('James Blake'),
  ('Modestep'),
  ('12th Planet'),
  ('Grandson'),
  ('JACKLNDN'),
  ('CHVRCHES'),
  ('The Ghost Wolves'),
  ('King''s X'),
  ('Lost Frequencies'),
  ('Camouflage'),
  ('Gnarls Barkley'),
  ('DJ Yoda'),
  ('Michael Salvatori & Martin O''Donnell (Halo)'),
  ('Symphony X'),
  ('Stabbing Westward'),
  ('John Keane'),
  ('Benoit Pioulard'),
  ('The Phantoms'),
  ('Toto'),
  ('Ludovico Einaudi'),
  ('Daniel Pemberton'),
  ('Love and Rockets'),
  ('Kermit The Frog'),
  ('Artful Dodger'),
  ('Craig David'),
  ('Reliant K'),
  ('The Goo Goo Dolls'),
  ('Soco'),
  ('Black Coffee'),
  ('Lila Ike'''),
  ('Meadowlark'),
  ('The Lacs'),
  ('Cliff Eidelman'),
  ('Yonder Mountain String Band'),
  ('Arnold Schoenberg'),
  ('Gwen Stefani'),
  ('Crowded House'),
  ('Trojan Marching Band'),
  ('Enigma'),
  ('Mike & The Mechanics'),
  ('Rupert Gregson-Williams'),
  ('Liberty DeVito'),
  ('Duckwrth'),
  ('Supertramp'),
  ('Rita Hayworth'),
  ('Bumps McGhee and His Twisters'),
  ('Harry Belafonte'),
  ('David Rose'),
  ('Edward Shearmur'),
  ('Marilyn Monroe'),
  ('Ciara'),
  ('The Jonas Brothers'),
  ('Metric'),
  ('Highly Suspect'),
  ('Phillip Walker'),
  ('Jackson Whalan'),
  ('Nancy Faust'),
  ('Drive By Truckers'),
  ('Henry Jackman'),
  ('The Chris Robinson Brotherhood'),
  ('Steven Halpern'),
  ('Stealers Wheel'),
  ('Alanis Morissette'),
  ('Citizen King'),
  ('Billy Bragg'),
  ('The Hoodoo Gurus'),
  ('Orleans'),
  ('Carl Perkins'),
  ('The Highwaymen'),
  ('Night Ranger'),
  ('Camila Cabello'),
  ('The Germs'),
  ('Ryan Tedder'),
  ('Junior Vasquez'),
  ('Irving Berlin'),
  ('Hayden James'),
  ('Jamie xx'),
  ('Robyn'),
  ('Carly Rae Jepsen'),
  ('French Montana'),
  ('Fifth Harmony'),
  ('Alessia Cara'),
  ('Gretchen Wilson'),
  ('Little Big Town'),
  ('Miley Cyrus'),
  ('Lizzo'),
  ('Arrested Development'),
  ('T.I.'),
  ('J. Geils Band'),
  ('Savage Garden'),
  ('Olly Murs'),
  ('Lifehouse'),
  ('Patti Page'),
  ('Lou Bega'),
  ('Charles Trenet'),
  ('The Urge'),
  ('Ray Parker Jr.'),
  ('Johnny Nash'),
  ('Robbie Williams'),
  ('Wojciech Kilar (The Pianist)'),
  ('Chad Lawson'),
  ('Hauschka'),
  ('Puscifer'),
  ('Charles-Marie Widor'),
  ('Les Claypool'),
  ('Alicia Keys'),
  ('White Lion'),
  ('WInger'),
  ('Cinderella'),
  ('The Alarm'),
  ('Daughtry'),
  ('Lumineers'),
  ('Marcelo Zarvus'),
  ('Charlie Pluth'),
  ('Bread'),
  ('Britney Spears'),
  ('The Dream Academy'),
  ('Josh Homme'),
  ('Jack Nitzsche'),
  ('Mac Miller'),
  ('Gary Jules'),
  ('M83'),
  ('Will Smith'),
  ('Lennie Niehaus'),
  ('Atreyu'),
  ('Jason Graves (Dead Space)'),
  ('Marius Constant'),
  ('Gioachino Rossini'),
  ('Dimitri Tiomkin'),
  ('Gerard McMann'),
  ('Lonestar'),
  ('Crystal Gayle'),
  ('Blake Neely'),
  ('10cc'),
  ('Buddy Collette'),
  ('CeeLo Green'),
  ('Pearl Jam (Unplugged)'),
  ('Stephen Stills'),
  ('Eric Clapton (Unplugged)'),
  ('Basil Paledouris'),
  ('William Ackerman'),
  ('Iggy Azalea'),
  ('Douglas Pipes'),
  ('Jessie J'),
  ('John Tesh'),
  ('Son House'),
  ('Tommy Tutone'),
  ('Blind Willie Johnson'),
  ('Keith and Matthew Strachan'),
  ('Naked Eyes'),
  ('Brian Reitzell'),
  ('Siddhartha Khosla (This Is Us)'),
  ('The Darkness'),
  ('Thrill Kill Cult'),
  ('Halsey'),
  ('Steve Dorff'),
  ('Baseball'),
  ('Dan Forden (Mortal Kombat)'),
  ('Slim Harpo'),
  ('Manuel de Falla'),
  ('Fergie'),
  ('Daddy Yankee'),
  ('Don Omar'),
  ('Tom Misch'),
  ('DNCE'),
  ('The Wanted'),
  ('Charlie Puth'),
  ('Tove Lo'),
  ('Nelly Furtado'),
  ('Shawn Mendes'),
  ('Kelis'),
  ('Clean Bandit'),
  ('Mary J. Blige'),
  ('Fitz and the Tantrums'),
  ('ZAYN'),
  ('La Roux'),
  ('The Stone Roses'),
  ('Miranda Lambert'),
  ('Miranda Cosgrove'),
  ('Spa Music'),
  ('Nigel Godrich'),
  ('Scott Weiland'),
  ('Darius Rucker'),
  ('The Little River Band'),
  ('George Tipton'),
  ('Bobby Tahouri'),
  ('Verne Langdon'),
  ('John Morris'),
  ('MKTO'),
  ('Jermaine Dupri'),
  ('Sugar Ray'),
  ('Melanie Martinez'),
  ('Celtic Orchestra'),
  ('Nordsee'),
  ('Keller Williams'),
  ('The Velvet Underground'),
  ('L.A. Guns'),
  ('Slash''s Snakepit'),
  ('Roisin Murphy'),
  ('Melissa Etheridge'),
  ('James S. Levine'),
  ('David Essex'),
  ('The Buggles'),
  ('Juice Wrld'),
  ('Megan Thee Stallion'),
  ('Lauryn Hill'),
  ('Les Nubians'),
  ('Manfred Mann'),
  ('Dierks Bently'),
  ('Tedeschi Trucks Band'),
  ('Gov''t Mule'),
  ('Steel Panther'),
  ('David Lee Roth'),
  ('Amos Lee'),
  ('Cypress Hill'),
  ('Warren G'),
  ('KONO'),
  ('Puddle of Mudd'),
  ('Theory of a Deadman'),
  ('Stone Temple Pilots (Unplugged)'),
  ('Reggie Watts'),
  ('Abandoned Toys'),
  ('Lil Mosey'),
  ('Ne-Yo'),
  ('Trey Songz'),
  ('Split Enz'),
  ('Tyga'),
  ('Terence Trent D''Arby'),
  ('Macy GrayAloe BlaccAdam Levine'),
  ('The HoneycombsThe SurfarisThe Deuce Coups'),
  ('Boogie Belgique'),
  ('Benee'),
  ('ABC'),
  ('Juicy JFetty Wap'),
  ('ProleterBoztownSkinshape'),
  ('Chris Botti'),
  ('Tre CoastVice MentaMaejorBrian Puspos'),
  ('DeBargeGo West'),
  ('Jon Secada'),
  ('Trans Siberian Orchestra'),
  ('Tim SimonecMichael Abels'),
  ('Michael SalgadoCafe Accordion OrchestraDana Boule'),
  ('Dave KozSpyro Gyra'),
  ('Tegan and Sarah'),
  ('Cascada'),
  ('Roger Waters'),
  ('Schoolboy Q'),
  ('Angelo BadalamentiPino Donaggio'),
  ('Johnny Paycheck'),
  ('Josh Kelley'),
  ('Westlife'),
  ('Rita Ora'),
  ('Troye Sivan'),
  ('Minor Threat'),
  ('Lea Salonga'),
  ('Bruno Major'),
  ('Kazumi Totaka'),
  ('Jovial'),
  ('Limes'),
  ('The Deli'),
  ('Saib'),
  ('Gyvus'),
  ('Jazz Hop Cafe'),
  ('Tom Doolie'),
  ('Flamingosis'),
  ('Funkmammoth'),
  ('Kiefer'),
  ('Bad FInger'),
  ('Mac DeMarco'),
  ('The Dillards'),
  ('Jesse McCartney'),
  ('Joseph Conlan'),
  ('Gary Stewart'),
  ('David Allan Coe'),
  ('Michael Weatherly'),
  ('Placebo'),
  ('David Julyan'),
  ('Creature Feature'),
  ('Alex Clare'),
  ('Sesame Street'),
  ('Rival Sons'),
  ('The Honeydrippers'),
  ('Harry ChapinJohn Denver'),
  ('Katrina and the Waves'),
  ('Shiro Sagisu'),
  ('Kathryn Jones'),
  ('Temple of the Dog'),
  ('Ben Vaughn'),
  ('Billy Swan'),
  ('Matchbox'),
  ('Foggy Mountain Boys'),
  ('The Foggy Mountain Boys'),
  ('McFly'),
  ('Hollow Coves'),
  ('Front Line Assembly'),
  ('Toru Takemitsu'),
  ('Jaden Smith'),
  ('Run DMC & Aerosmith'),
  ('Powfu'),
  ('Jay-Z & Kanye West'),
  ('Photek'),
  ('Folklorico'),
  ('Temples'),
  ('Joe Hisaishi'),
  ('Giles Lamb'),
  ('Inon Zur'),
  ('Jasper Byrne'),
  ('Michael Convertino'),
  ('Johnny Marks'),
  ('Frank Sinatra'),
  ('Emile Waldteufel'),
  ('Justin E. Bell'),
  ('The ArchiesThe Partridge Family'),
  ('Cold War KidsFoster the People'),
  ('Niilo Takalainen'),
  ('Manami Matsumae (Mega Man)'),
  ('Keiichi Suzuki and Hirokazu Tanaka (Earthbound)'),
  ('Masato Nakamura (Sonic the Hedgehog)'),
  ('Anamanaguchi'),
  ('Jeff Beal'),
  ('Eddie Money'),
  ('Daniel Rosenfeld'),
  ('Junkie XL'),
  ('The Bloodhound Gang'),
  ('Oliver Wallace'),
  ('Soichi Terada'),
  ('King Gizzard and the Lizard Wizard'),
  ('Clinton Shorter'),
  ('Shawn Lee'),
  ('Mick Gordon'),
  ('Junichi Masuda (Pokemon)'),
  ('Jerrold Immel'),
  ('Kris Bowers'),
  ('Adam Gock'),
  ('Kevin Kiner'),
  ('Ted Nichols'),
  ('The Thompson Twins'),
  ('Naughty By Nature'),
  ('Billy Preston'),
  ('Taro Bando & Hajime Wakai'),
  ('World Party'),
  ('2 Unlimited'),
  ('Frank Ocean'),
  ('Bill Conti'),
  ('MC Hammer'),
  ('James Hannigan'),
  ('Elmer Bernstein'),
  ('King Oliver'),
  ('Burl IvesAndy Williams'),
  ('Christopher Lennertz'),
  ('Debbie GibsonRoxetteGloria Estefan'),
  ('Fine Young Cannibals'),
  ('Flogging Molly'),
  ('The Roots'),
  ('Original Dixieland Jazz Band'),
  ('Eazy-E'),
  ('GZA'),
  ('Mos Def'),
  ('Gang Starr'),
  ('Nathan Johnson'),
  ('Slick Rick'),
  ('Pinar Toprak'),
  ('Cocteau Twins'),
  ('Conway Twitty'),
  ('Alex Wurman'),
  ('Frank Churchill'),
  ('Dan Romer'),
  ('Men Without Hats'),
  ('Richard Wells'),
  ('Joe Pass'),
  ('Young MC'),
  ('TLC'),
  ('Ratatat'),
  ('bsd.u'),
  ('Kelly Bailey'),
  ('Jeremy Soule'),
  ('Tom Holkenborg'),
  ('Masami Ueda'),
  ('John Philip Sousa'),
  ('Paul J. Smith & Leigh Harline'),
  ('James Lord Pierpont'),
  ('Antonio Sanchez'),
  ('George Benson'),
  ('Paul Shaffer'),
  ('Yma Sumac'),
  ('Amii Stewart'),
  ('John Newman'),
  ('Patrice Rushen'),
  ('John Du Prez'),
  ('Michael Rubin'),
  ('Merv Griffin'),
  ('Gal Costa'),
  ('Machine Gun Kelly'),
  ('Bob Wills'),
  ('Balfa Brothers'),
  ('Gillian Hills'),
  ('NVDES'),
  ('Kate Bush'),
  ('The James Gang'),
  ('Major Lazer'),
  ('Falco'),
  ('Drew Neumann'),
  ('Jean Knight'),
  ('Jeff Russo'),
  ('A$AP Rocky'),
  ('Laura Karpman'),
  ('LCD Soundsystem'),
  ('Tame Impala'),
  ('The Fugees'),
  ('Tobacco'),
  ('Kenny Hoopla'),
  ('Nico & Vinz'),
  ('Blood Orange'),
  ('Sofi Tukker'),
  ('Ava Max'),
  ('Lakeside'),
  ('FISHER'),
  ('Pop Smoke'),
  ('Bad Bunny'),
  ('J Balvin'),
  ('Olivia Rodrigo'),
  ('Doja Cat'),
  ('LANY'),
  ('Christina Milian'),
  ('Bloodhound Gang'),
  ('Oliver Heldens'),
  ('Chance The Rapper'),
  ('Inner Circle'),
  ('Luis Fonsi'),
  ('Boyz II Men'),
  ('KC and the Sunshine Band'),
  ('Missy Elliott'),
  ('DNA'),
  ('Christina Aguilera'),
  ('Spice Girls'),
  ('Dobie Grey'),
  ('Cristobal Tapia de Veer'),
  ('Blippi'),
  ('The Donnas'),
  ('Jai Wolf'),
  ('Washed Out'),
  ('Plain White T''s'),
  ('Motion City Soundtrack'),
  ('Red Jumpsuit Apparatus'),
  ('The Used'),
  ('John Robert Wood'),
  ('Lauv'),
  ('Adam Cohen'),
  ('Tyler the Creator'),
  ('H.E.R'),
  ('Anderson Paak'),
  ('Kid Ink'),
  ('KYLE'),
  ('Insane Clown Posse'),
  ('DaBaby'),
  ('The Lonely Island'),
  ('BTS'),
  ('Andy Grammer'),
  ('Three 6 Mafia'),
  ('Kevin Sherwood'),
  ('Lil Baby'),
  ('Bryson Tiller'),
  ('Kodak Black'),
  ('Rae Sremmurd'),
  ('6Lack'),
  ('Brockhampton'),
  ('21 Savage'),
  ('Ice T'),
  ('John Parr'),
  ('Nick Kingsley'),
  ('Walker and Royce'),
  ('3OH!3'),
  ('City Girls'),
  ('Christopher Cross'),
  ('Front 242'),
  ('Joel P. West'),
  ('Miguel'),
  ('Michael Sembello'),
  ('Kehlani'),
  ('The Kid Laroi'),
  ('Angie Stone'),
  ('Jack Harlow'),
  ('Salt N Pepa'),
  ('Roddy Ricch'),
  ('A Boogie wit da Hoodie'),
  ('The Pussycat Dolls'),
  ('Ty Dolla $ign'),
  ('MAGIC!'),
  ('The Jungle Brothers'),
  ('Omarion'),
  ('Akon'),
  ('SZA'),
  ('Young Boy Never Broke Again'),
  ('Nipsey Hussle'),
  ('Craig Wedren & Anna Waronker'),
  ('London On Da Track'),
  ('Kacey Musgraves'),
  ('Taylor Dayne'),
  ('Reel 2 Real'),
  ('Victoria Monet'),
  ('Tory Lanez'),
  ('Wendy Carlos'),
  ('John Cage'),
  ('Television'),
  ('Tate McRae'),
  ('Sean Kingston'),
  ('Sexyy Red'),
  ('Chumbawumba'),
  ('Daniel Bedingfield'),
  ('Explosions in The Sky'),
  ('Holeg Spies'),
  ('Mansionair'),
  ('Lasgo'),
  ('Lex Horton'),
  ('Leona Lewis'),
  ('Ice Spice'),
  ('Snarky Puppy'),
  ('Jesse Frederick'),
  ('Bonnie Tyler'),
  ('Tommy Richman'),
  ('OMI'),
  ('Sabrina Carpenter'),
  ('Chappell Roan'),
  ('Kim Petras'),
  ('DJ Sammy'),
  ('Meduza'),
  ('DCUP'),
  ('Andrew Lloyd Weber'),
  ('Vic Mizzi'),
  ('Tantro Metro & Devonte'),
  ('Tanto Metro & Devonte'),
  ('Tyla'),
  ('Cartola'),
  ('Hellogoodbye'),
  ('Kim Carnes'),
  ('Francis And The Lights'),
  ('The Click Five'),
  ('The Greg Kihn Band'),
  ('Billy Ray Cyrus'),
  ('Children Of Bodom'),
  ('Helloween'),
  ('Dokken'),
  ('Edie Brickell & New Bohemians'),
  ('Metro Station'),
  ('Alesso'),
  ('Pulp'),
  ('Death'),
  ('Blue Man Group'),
  ('ATC'),
  ('Stomp!'),
  ('Kajagoogoo'),
  ('Doechii'),
  ('Cannons'),
  ('Masahiro Andoh'),
  ('Jun Senoue'),
  ('The Heavy'),
  ('Noah Kahan'),
  ('Sisters of Mercy'),
  ('Madness'),
  ('Tom Howe'),
  ('Trippie Redd'),
  ('Amber'),
  ('Glass Animals'),
  ('Jeff Zahn'),
  ('Cobra Starship'),
  ('The Wiseguys'),
  ('Navos'),
  ('Joel Corry'),
  ('Rufus Du Sol'),
  ('Cedric Gervais'),
  ('MK'),
  ('STRFKR'),
  ('Mike Sherm'),
  ('SAINt JHN'),
  ('Robin S.'),
  ('Alan Walker'),
  ('Bebe Rexha'),
  ('Jelly Roll'),
  ('Alexandra Stan'),
  ('Dirty Honey'),
  ('Disco Lines'),
  ('Far East Movement'),
  ('Capital Cities'),
  ('The Mars Volta'),
  ('Rednex'),
  ('Ella Henderson'),
  ('James Hype'),
  ('Meat Loaf'),
  ('Luke Combs'),
  ('Latto'),
  ('Andy Summers'),
  ('Armani White'),
  ('The Gaslight Anthem'),
  ('Krewella'),
  ('Dax'),
  ('Olivia Dean'),
  ('AJR'),
  ('Pete Rodriguez'),
  ('Takafumi Fijisawa'),
  ('Colin Stetson'),
  ('Romeo Santos'),
  ('Cha Cha Chuckles'),
  ('BandaBanda'),
  ('Saja Boys'),
  ('Chris Hendricks'),
  ('Jesse Glynne'),
  ('Jess Glynne'),
  ('The Fearless Flyers'),
  ('Rockell'),
  ('HUNTR/X'),
  ('Jack Lenz'),
  ('Oneheart'),
  ('Billie Eilish'),
  ('Shinji Miyazaki'),
  ('Natti Natasha'),
  ('Johnny Ventura'),
  ('Sistek'),
  ('Danny Ocean & Kapo'),
  ('Wilfrido Vargas'),
  ('Nicky Jam'),
  ('Danny Ocean'),
  ('Camilo'),
  ('Sergio Vargas'),
  ('Celia Cruz'),
  ('Pipi Franco'),
  ('Stromae'),
  ('Acoustic Alchemy'),
  ('Slightly Stoopid'),
  ('Anita Ward'),
  ('Eddie Murphy'),
  ('Pale Waves')
ON CONFLICT (ksl_name) DO NOTHING;
