-- migration_035_seed_moods_genres.sql
-- Seeds all mood_1 values from FileMaker catalog export
-- Seeds missing primary_genres (normalized, deduped)

-- ── Mood 1 (all unique values from TITLES_Table.csv) ────────────────────────
INSERT INTO mood_1 (mood_1_name) VALUES
  ('Aggressive'), ('Ambient'), ('Anthemic'), ('Barren'), ('Beat'),
  ('Bitter'), ('Chill'), ('Comic'), ('Complex'), ('Confident'),
  ('Content'), ('Creepy'), ('Curious'), ('Dark'), ('Defiant'),
  ('Downer'), ('Drama'), ('Dramatic'), ('Edgy'), ('Eerie'),
  ('Epic'), ('Exotic'), ('Friendly'), ('Fun'), ('Funky'),
  ('Groovy'), ('Happy'), ('Hopeful'), ('Humorous'), ('Laid back'),
  ('Melancholic'), ('Moderate'), ('Mysterious'), ('Negative'), ('Nervous'),
  ('Nightclub'), ('Ominous'), ('Peaceful'), ('Playful'), ('Positive'),
  ('Quirky'), ('Raw'), ('Reflective'), ('Regal'), ('Relaxed'),
  ('Rockin'''), ('Romantic'), ('Sad'), ('Sentimental'), ('Serious'),
  ('Sexy'), ('Silly'), ('Simple'), ('Soaring'), ('Sweeping'),
  ('Tense'), ('Tragic'), ('Trippy'), ('Triumphant'), ('Upbeat'),
  ('Whimsical')
ON CONFLICT (mood_1_name) DO NOTHING;

-- ── Primary Genres (normalized — deduped case variants, fixed typos) ─────────
INSERT INTO primary_genres (primary_genre_name) VALUES
  ('50''s Rock and Pop'),
  ('60''s Rock and Pop'),
  ('80''s Rock and Pop'),
  ('Alternative Rock'),
  ('Ambient'),
  ('Blues'),
  ('Breakbeat'),
  ('Christmas'),
  ('Classic Electro'),
  ('Classic Rock'),
  ('Classical'),
  ('Comedy'),
  ('Country'),
  ('Disco'),
  ('Drama Sting'),
  ('Dramatic Riser'),
  ('Drum Beat'),
  ('Drum N Bass'),
  ('Dubstep'),
  ('Experimental Electronic'),
  ('Extended Impact'),
  ('Famous Classical'),
  ('Film Score'),
  ('Folk'),
  ('Great American Songbook'),
  ('Guitar Sting'),
  ('Gumshoe'),
  ('Heartland Rock'),
  ('Heavy Metal'),
  ('Hip Hop/Rap'),
  ('Horror Sting'),
  ('House'),
  ('Jazz'),
  ('Marching Band'),
  ('Military'),
  ('New Age'),
  ('Old Timey'),
  ('Political'),
  ('Pop'),
  ('Religious'),
  ('SFX'),
  ('Single Instrument Bumper'),
  ('Soul'),
  ('Synthpop'),
  ('Techno'),
  ('Tension Tool Box'),
  ('Traditional'),
  ('Trance'),
  ('TV Theme'),
  ('World-Ethnic')
ON CONFLICT (primary_genre_name) DO NOTHING;
