-- migration_027_genres_subgenres.sql
-- Full HAUS proprietary genre + subgenre masterlist (78 genres, 716 subgenres)
-- Replaces the placeholder genres seeded in migration_026

TRUNCATE primary_genres CASCADE;

INSERT INTO primary_genres (primary_genre_name) VALUES
  ('50''s Rock and Pop'),
  ('60''s Rock and Pop'),
  ('80''s Rock and Pop'),
  ('ALTERNATIVE ROCK'),
  ('AMBIENT'),
  ('BLUES'),
  ('BREAKBEAT'),
  ('CHRISTMAS'),
  ('CLASSIC ELECTRO'),
  ('CLASSIC ROCK'),
  ('CLASSICAL'),
  ('COMEDY'),
  ('COUNTRY'),
  ('Country'),
  ('DISCO'),
  ('DRAMA STING'),
  ('DRAMATIC RISER'),
  ('DRUM BEAT'),
  ('DRUM N BASS'),
  ('DUBSTEP'),
  ('EXPERIMENTAL ELECTRONIC'),
  ('EXTENDED IMPACT'),
  ('FAMOUS CLASSICAL'),
  ('FILM SCORE_Action'),
  ('FILM SCORE_Adventure'),
  ('FILM SCORE_Battle'),
  ('FILM SCORE_Comic Light Tension'),
  ('FILM SCORE_Creepy Scary'),
  ('FILM SCORE_Defeated'),
  ('FILM SCORE_Dramatic Builds'),
  ('FILM SCORE_Dramatic Tension'),
  ('FILM SCORE_Epic'),
  ('FILM SCORE_Fanfares'),
  ('FILM SCORE_Fantasy_Magical'),
  ('FILM SCORE_Final Reel Triumphant'),
  ('FILM SCORE_Intrigue'),
  ('FILM SCORE_Light Tension'),
  ('FILM SCORE_Melancholic'),
  ('FILM SCORE_Mysterious'),
  ('FILM SCORE_Regal'),
  ('FILM SCORE_Romantic'),
  ('FILM SCORE_Serious'),
  ('FILM SCORE_Sports Package'),
  ('FILM SCORE_Tense Beat'),
  ('FILM SCORE_Tense Drone'),
  ('FILM SCORE_Tense Pulse'),
  ('FILM SCORE_Tension'),
  ('FILM SCORE_Uplifting'),
  ('FILM SCORE_Western'),
  ('FILM SCORE_Whimsical'),
  ('FOLK'),
  ('GREAT AMERICAN SONGBOOK'),
  ('GUITAR STING'),
  ('GUMSHOE'),
  ('HEARTLAND ROCK'),
  ('HEAVY METAL'),
  ('HIP HOP/RAP'),
  ('HORROR STING'),
  ('HOUSE'),
  ('JAZZ'),
  ('MARCHING BAND'),
  ('MILITARY'),
  ('NEW AGE'),
  ('OLD TIMEY'),
  ('ORCHESTRAL'),
  ('POLITICAL_Negative'),
  ('POLITICAL_Uplifting'),
  ('POP'),
  ('RELIGIOUS'),
  ('SFX'),
  ('SINGLE INSTRUMENT BUMPER'),
  ('SOUL_R AND B'),
  ('SYNTHPOP'),
  ('TECHNO'),
  ('TRADITIONAL'),
  ('TRANCE'),
  ('TV THEME'),
  ('WORLD-ETHNIC')
ON CONFLICT (primary_genre_name) DO NOTHING;

CREATE TABLE IF NOT EXISTS sub_genres (
  sub_genre_id        SERIAL PRIMARY KEY,
  primary_genre_id    INTEGER NOT NULL REFERENCES primary_genres(primary_genre_id) ON DELETE CASCADE,
  sub_genre_name      TEXT NOT NULL,
  UNIQUE (primary_genre_id, sub_genre_name)
);

INSERT INTO sub_genres (primary_genre_id, sub_genre_name)
SELECT pg.primary_genre_id, sg.sub_genre_name
FROM primary_genres pg
JOIN (VALUES
  ('50''s Rock and Pop', 'Rockabilly'),
  ('50''s Rock and Pop', 'Doo Wop'),
  ('50''s Rock and Pop', 'Rock and Roll'),
  ('50''s Rock and Pop', 'Acoustic - Rockabilly'),
  ('60''s Rock and Pop', 'British Invasion'),
  ('60''s Rock and Pop', 'Pop'),
  ('60''s Rock and Pop', 'Psychedelic'),
  ('60''s Rock and Pop', 'Solo Acoustic Guitar'),
  ('60''s Rock and Pop', 'Acoustic - Pop'),
  ('60''s Rock and Pop', 'Acoustic - British Invasion'),
  ('60''s Rock and Pop', 'Rock'),
  ('60''s Rock and Pop', 'Surf Rock'),
  ('80''s Rock and Pop', 'Punk'),
  ('80''s Rock and Pop', 'New Wave - Rock'),
  ('80''s Rock and Pop', 'Post-Punk'),
  ('80''s Rock and Pop', 'Hair Band - Metal'),
  ('80''s Rock and Pop', 'Pop Rock'),
  ('80''s Rock and Pop', 'New Wave - Synthpop'),
  ('80''s Rock and Pop', 'Heavy Metal'),
  ('80''s Rock and Pop', 'Pop'),
  ('80''s Rock and Pop', 'Dance Pop'),
  ('80''s Rock and Pop', 'Acoustic - Hair Band - Metal'),
  ('80''s Rock and Pop', 'Solo Guitar'),
  ('80''s Rock and Pop', 'Acoustic - Pop Rock'),
  ('80''s Rock and Pop', 'Ska'),
  ('80''s Rock and Pop', 'Funk Rock'),
  ('80''s Rock and Pop', 'Acoustic - Post-Punk'),
  ('80''s Rock and Pop', 'Rap Rock'),
  ('80''s Rock and Pop', 'Reggae Rock'),
  ('ALTERNATIVE ROCK', 'Acoustic'),
  ('ALTERNATIVE ROCK', 'Grunge'),
  ('ALTERNATIVE ROCK', 'Acoustic - Grunge'),
  ('ALTERNATIVE ROCK', 'Brit Pop'),
  ('ALTERNATIVE ROCK', 'Post-Grunge'),
  ('ALTERNATIVE ROCK', 'Acoustic - Post-Grunge'),
  ('ALTERNATIVE ROCK', 'Pop Punk'),
  ('ALTERNATIVE ROCK', 'Indie'),
  ('ALTERNATIVE ROCK', 'Acoustic - Indie'),
  ('ALTERNATIVE ROCK', 'Nu-Metal'),
  ('ALTERNATIVE ROCK', 'Post-Punk Revival'),
  ('ALTERNATIVE ROCK', 'Acoustic - Post-Punk-Revival'),
  ('ALTERNATIVE ROCK', 'Jam Band'),
  ('ALTERNATIVE ROCK', 'Acoustic - Jam Band'),
  ('ALTERNATIVE ROCK', 'Stoner_Desert Rock'),
  ('ALTERNATIVE ROCK', 'Garage Rock'),
  ('ALTERNATIVE ROCK', 'Funk Rock'),
  ('ALTERNATIVE ROCK', 'Acoustic - Pop Punk'),
  ('ALTERNATIVE ROCK', 'Industrial'),
  ('ALTERNATIVE ROCK', 'Metal'),
  ('ALTERNATIVE ROCK', 'Solo Guitar'),
  ('ALTERNATIVE ROCK', 'Acoustic - Garage Rock'),
  ('ALTERNATIVE ROCK', 'Punk'),
  ('ALTERNATIVE ROCK', 'Pop Rock'),
  ('ALTERNATIVE ROCK', 'Emo'),
  ('ALTERNATIVE ROCK', 'Singer/Songwriter'),
  ('ALTERNATIVE ROCK', 'Ska'),
  ('ALTERNATIVE ROCK', 'Reggae Rock'),
  ('ALTERNATIVE ROCK', 'Acoustic - Pop Rock'),
  ('ALTERNATIVE ROCK', 'Southern Rock'),
  ('ALTERNATIVE ROCK', 'Surf'),
  ('ALTERNATIVE ROCK', 'Rap Rock'),
  ('ALTERNATIVE ROCK', 'Acoustic - Stoner_Desert Rock'),
  ('ALTERNATIVE ROCK', 'Acoustic - Funk Rock'),
  ('ALTERNATIVE ROCK', 'Quirky'),
  ('ALTERNATIVE ROCK', 'Progressive Rock'),
  ('AMBIENT', 'Wallpaper'),
  ('AMBIENT', 'Ambient House'),
  ('AMBIENT', 'Acid Jazz'),
  ('AMBIENT', 'Trip Hop'),
  ('AMBIENT', 'Nu Jazz'),
  ('AMBIENT', 'Percussion'),
  ('AMBIENT', 'Piano'),
  ('BLUES', 'Acoustic'),
  ('BLUES', 'Delta Blues'),
  ('BLUES', 'Chicago Blues'),
  ('BLUES', 'Memphis Blues'),
  ('BLUES', 'Blues Rock'),
  ('BLUES', 'Jam Band'),
  ('BLUES', 'Piano'),
  ('BLUES', 'Texas Blues'),
  ('BLUES', 'Zydeco'),
  ('BLUES', 'Swamp'),
  ('BREAKBEAT', 'Electronic'),
  ('BREAKBEAT', 'Soul'),
  ('CHRISTMAS', 'Rock'),
  ('CHRISTMAS', 'Acoustic'),
  ('CHRISTMAS', 'Traditional'),
  ('CHRISTMAS', 'Electronic'),
  ('CHRISTMAS', 'Orchestral'),
  ('CHRISTMAS', 'Comedy'),
  ('CHRISTMAS', 'Percussion'),
  ('CHRISTMAS', 'Piano'),
  ('CHRISTMAS', 'Pop'),
  ('CHRISTMAS', 'Choir'),
  ('CHRISTMAS', 'Hip Hop/Rap'),
  ('CLASSIC ELECTRO', 'Video Game'),
  ('CLASSIC ELECTRO', 'Early Synthpop'),
  ('CLASSIC ROCK', 'Acoustic'),
  ('CLASSIC ROCK', 'Garage Rock'),
  ('CLASSIC ROCK', 'Prog Rock'),
  ('CLASSIC ROCK', 'Psychedelic'),
  ('CLASSIC ROCK', 'Jazz Rock'),
  ('CLASSIC ROCK', 'Glam Rock'),
  ('CLASSIC ROCK', 'Soft Rock'),
  ('CLASSIC ROCK', 'Hard Rock - Metal'),
  ('CLASSIC ROCK', 'Southern Rock'),
  ('CLASSIC ROCK', 'Acoustic - Southern Rock'),
  ('CLASSIC ROCK', 'Acoustic - Garage Rock'),
  ('CLASSIC ROCK', 'Jam Band'),
  ('CLASSIC ROCK', 'Blues Rock'),
  ('CLASSIC ROCK', 'Post-Punk'),
  ('CLASSIC ROCK', 'Pop Rock'),
  ('CLASSIC ROCK', 'Funk Rock'),
  ('CLASSIC ROCK', 'Acoustic - Blues Rock'),
  ('CLASSIC ROCK', 'Acoustic - Jam Band'),
  ('CLASSIC ROCK', 'Solo Acoustic Guitar'),
  ('CLASSIC ROCK', 'Solo Guitar'),
  ('CLASSIC ROCK', 'Acoustic - Soft Rock'),
  ('CLASSIC ROCK', 'Acoustic - Hard Rock'),
  ('CLASSIC ROCK', 'Ballad'),
  ('CLASSIC ROCK', 'Latin Rock'),
  ('CLASSIC ROCK', 'Folk Rock'),
  ('CLASSIC ROCK', 'Acoustic - Jazz Rock'),
  ('CLASSIC ROCK', 'Tropical Rock'),
  ('CLASSIC ROCK', 'Piano Rock'),
  ('CLASSICAL', 'Harpsichord'),
  ('CLASSICAL', 'Piano'),
  ('CLASSICAL', 'Baroque_Piano'),
  ('CLASSICAL', 'String Quartet'),
  ('CLASSICAL', 'Orchestral'),
  ('CLASSICAL', 'Acoustic'),
  ('CLASSICAL', 'Organ'),
  ('CLASSICAL', 'Hip Hop/Rap'),
  ('COMEDY', 'Jazz'),
  ('COMEDY', 'Vaudeville'),
  ('COMEDY', 'Circus'),
  ('COMEDY', 'Orchestral'),
  ('COMEDY', 'Quirky'),
  ('COMEDY', 'Americana'),
  ('COMEDY', 'Kazoo'),
  ('COMEDY', 'Rock'),
  ('COMEDY', 'Madcap, Silly'),
  ('COMEDY', '70s Game Show'),
  ('COMEDY', 'Acoustic - Madcap, Silly'),
  ('COMEDY', 'Percussion'),
  ('COMEDY', 'Carnival'),
  ('COMEDY', 'French Gypsy Jazz'),
  ('COMEDY', 'Dark Comedy'),
  ('COMEDY', 'Piano'),
  ('COMEDY', 'Western'),
  ('COMEDY', 'Children''s'),
  ('COUNTRY', 'Bluegrass'),
  ('COUNTRY', 'Appalachian'),
  ('COUNTRY', 'Americana'),
  ('COUNTRY', 'Country Rock'),
  ('COUNTRY', 'Pop Country'),
  ('COUNTRY', 'Alternative Country'),
  ('COUNTRY', 'Swamp'),
  ('COUNTRY', 'Hick Hop'),
  ('COUNTRY', 'Acoustic - Americana'),
  ('COUNTRY', 'Classic Country'),
  ('COUNTRY', 'Country Blues'),
  ('COUNTRY', 'Acoustic - Country Rock'),
  ('COUNTRY', 'Acoustic - Country Blues'),
  ('COUNTRY', 'Acoustic - Swamp'),
  ('COUNTRY', 'Western'),
  ('COUNTRY', 'Acoustic - Classic Country'),
  ('COUNTRY', 'Cowpunk'),
  ('COUNTRY', 'Outlaw'),
  ('Country', 'Acoustic - Pop Country'),
  ('DISCO', 'Classic Disco'),
  ('DISCO', 'Dance Pop'),
  ('DRAMA STING', 'Orchestral'),
  ('DRAMA STING', 'Piano'),
  ('DRAMATIC RISER', 'Orchestral'),
  ('DRAMATIC RISER', 'Electronic'),
  ('DRAMATIC RISER', 'Hybrid'),
  ('DRUM BEAT', 'Rock'),
  ('DRUM BEAT', 'Jazz'),
  ('DRUM BEAT', 'Hip Hop/Rap'),
  ('DRUM N BASS', 'Drumstep'),
  ('DUBSTEP', 'Pop'),
  ('DUBSTEP', 'Trap'),
  ('DUBSTEP', 'Future Bass'),
  ('EXTENDED IMPACT', 'Percussion'),
  ('EXTENDED IMPACT', 'Sound Design/FX'),
  ('EXTENDED IMPACT', 'Orchestral'),
  ('EXTENDED IMPACT', 'Electronic'),
  ('EXTENDED IMPACT', 'Ambient'),
  ('EXTENDED IMPACT', 'Industrial'),
  ('EXTENDED IMPACT', 'Hybrid'),
  ('FAMOUS CLASSICAL', 'Orchestral'),
  ('FAMOUS CLASSICAL', 'Harpsichord'),
  ('FAMOUS CLASSICAL', 'Organ'),
  ('FAMOUS CLASSICAL', 'Piano'),
  ('FAMOUS CLASSICAL', 'String Quartet'),
  ('FAMOUS CLASSICAL', 'Rock'),
  ('FAMOUS CLASSICAL', 'Acoustic'),
  ('FILM SCORE_Action', 'Orchestral'),
  ('FILM SCORE_Action', 'Industrial'),
  ('FILM SCORE_Action', 'Electronic'),
  ('FILM SCORE_Action', 'Hybrid'),
  ('FILM SCORE_Action', 'Rock'),
  ('FILM SCORE_Action', 'Jazz'),
  ('FILM SCORE_Action', 'Dubstep'),
  ('FILM SCORE_Action', 'Percussion'),
  ('FILM SCORE_Action', 'Acoustic'),
  ('FILM SCORE_Action', 'World-Ethnic'),
  ('FILM SCORE_Action', 'Hip Hop/Rap'),
  ('FILM SCORE_Adventure', 'Orchestral'),
  ('FILM SCORE_Adventure', 'Hybrid'),
  ('FILM SCORE_Adventure', 'Marching Band'),
  ('FILM SCORE_Adventure', 'Jazz'),
  ('FILM SCORE_Adventure', 'Americana'),
  ('FILM SCORE_Adventure', 'Rock'),
  ('FILM SCORE_Adventure', 'Electronic'),
  ('FILM SCORE_Adventure', 'Percussion'),
  ('FILM SCORE_Adventure', 'Pop'),
  ('FILM SCORE_Adventure', 'Piano'),
  ('FILM SCORE_Adventure', 'Ambient'),
  ('FILM SCORE_Adventure', 'Acoustic'),
  ('FILM SCORE_Adventure', 'World-Ethnic'),
  ('FILM SCORE_Adventure', 'Western'),
  ('FILM SCORE_Battle', 'Orchestral'),
  ('FILM SCORE_Battle', 'Electronic'),
  ('FILM SCORE_Battle', 'Hybrid'),
  ('FILM SCORE_Battle', 'Rock'),
  ('FILM SCORE_Battle', 'Percussion'),
  ('FILM SCORE_Comic Light Tension', 'Orchestral'),
  ('FILM SCORE_Comic Light Tension', 'Industrial'),
  ('FILM SCORE_Comic Light Tension', 'Hybrid'),
  ('FILM SCORE_Comic Light Tension', 'Electronic'),
  ('FILM SCORE_Comic Light Tension', 'Jazz'),
  ('FILM SCORE_Comic Light Tension', 'Rock'),
  ('FILM SCORE_Comic Light Tension', 'Piano'),
  ('FILM SCORE_Comic Light Tension', 'Ambient'),
  ('FILM SCORE_Comic Light Tension', 'Country'),
  ('FILM SCORE_Comic Light Tension', 'Percussion'),
  ('FILM SCORE_Comic Light Tension', 'Americana'),
  ('FILM SCORE_Comic Light Tension', 'Pop'),
  ('FILM SCORE_Comic Light Tension', 'Hip Hop/Rap'),
  ('FILM SCORE_Comic Light Tension', 'Sea Shanty'),
  ('FILM SCORE_Comic Light Tension', 'Acoustic - Blues'),
  ('FILM SCORE_Comic Light Tension', 'World-Ethnic'),
  ('FILM SCORE_Creepy Scary', 'Orchestral'),
  ('FILM SCORE_Creepy Scary', 'Industrial'),
  ('FILM SCORE_Creepy Scary', 'Hybrid'),
  ('FILM SCORE_Creepy Scary', 'Electronic'),
  ('FILM SCORE_Creepy Scary', 'Jazz'),
  ('FILM SCORE_Creepy Scary', 'Rock'),
  ('FILM SCORE_Creepy Scary', 'Piano'),
  ('FILM SCORE_Creepy Scary', 'Ambient'),
  ('FILM SCORE_Creepy Scary', 'Autoharp'),
  ('FILM SCORE_Creepy Scary', 'Creepy Carnival'),
  ('FILM SCORE_Creepy Scary', 'Percussion'),
  ('FILM SCORE_Defeated', 'Orchestral'),
  ('FILM SCORE_Defeated', 'Industrial'),
  ('FILM SCORE_Defeated', 'Hybrid'),
  ('FILM SCORE_Defeated', 'Electronic'),
  ('FILM SCORE_Defeated', 'Jazz'),
  ('FILM SCORE_Defeated', 'Rock'),
  ('FILM SCORE_Defeated', 'Piano'),
  ('FILM SCORE_Defeated', 'Ambient'),
  ('FILM SCORE_Dramatic Builds', 'Orchestral'),
  ('FILM SCORE_Dramatic Builds', 'Industrial'),
  ('FILM SCORE_Dramatic Builds', 'Hybrid'),
  ('FILM SCORE_Dramatic Builds', 'Electronic'),
  ('FILM SCORE_Dramatic Builds', 'Jazz'),
  ('FILM SCORE_Dramatic Builds', 'Rock'),
  ('FILM SCORE_Dramatic Builds', 'Piano'),
  ('FILM SCORE_Dramatic Builds', 'Ambient'),
  ('FILM SCORE_Dramatic Tension', 'Orchestral'),
  ('FILM SCORE_Dramatic Tension', 'Industrial'),
  ('FILM SCORE_Dramatic Tension', 'Hybrid'),
  ('FILM SCORE_Dramatic Tension', 'Electronic'),
  ('FILM SCORE_Dramatic Tension', 'Jazz'),
  ('FILM SCORE_Dramatic Tension', 'Rock'),
  ('FILM SCORE_Dramatic Tension', 'Piano'),
  ('FILM SCORE_Dramatic Tension', 'Ambient'),
  ('FILM SCORE_Dramatic Tension', 'Sci-Fi'),
  ('FILM SCORE_Dramatic Tension', 'Percussion'),
  ('FILM SCORE_Dramatic Tension', 'Hip Hop/Rap'),
  ('FILM SCORE_Epic', 'Orchestral'),
  ('FILM SCORE_Epic', 'Hybrid'),
  ('FILM SCORE_Epic', 'Electronic'),
  ('FILM SCORE_Epic', 'Industrial'),
  ('FILM SCORE_Fanfares', 'Orchestral'),
  ('FILM SCORE_Fantasy_Magical', 'Orchestral'),
  ('FILM SCORE_Fantasy_Magical', 'Hybrid'),
  ('FILM SCORE_Fantasy_Magical', 'Electronic'),
  ('FILM SCORE_Fantasy_Magical', 'Piano'),
  ('FILM SCORE_Fantasy_Magical', 'Percussion'),
  ('FILM SCORE_Final Reel Triumphant', 'Orchestral'),
  ('FILM SCORE_Final Reel Triumphant', 'Hybrid'),
  ('FILM SCORE_Final Reel Triumphant', 'Electronic'),
  ('FILM SCORE_Final Reel Triumphant', 'Hip Hop/Rap'),
  ('FILM SCORE_Intrigue', 'Orchestral'),
  ('FILM SCORE_Intrigue', 'Industrial'),
  ('FILM SCORE_Intrigue', 'Hybrid'),
  ('FILM SCORE_Intrigue', 'Electronic'),
  ('FILM SCORE_Intrigue', 'Jazz'),
  ('FILM SCORE_Intrigue', 'Rock'),
  ('FILM SCORE_Intrigue', 'Piano'),
  ('FILM SCORE_Intrigue', 'Ambient'),
  ('FILM SCORE_Intrigue', 'Western'),
  ('FILM SCORE_Intrigue', 'Funk'),
  ('FILM SCORE_Intrigue', 'Percussion'),
  ('FILM SCORE_Intrigue', 'Americana'),
  ('FILM SCORE_Intrigue', 'Alternative Rock'),
  ('FILM SCORE_Intrigue', 'Acoustic'),
  ('FILM SCORE_Intrigue', 'Hip Hop/Rap'),
  ('FILM SCORE_Intrigue', 'World-Ethnic'),
  ('FILM SCORE_Light Tension', 'Orchestral'),
  ('FILM SCORE_Light Tension', 'Industrial'),
  ('FILM SCORE_Light Tension', 'Hybrid'),
  ('FILM SCORE_Light Tension', 'Electronic'),
  ('FILM SCORE_Light Tension', 'Jazz'),
  ('FILM SCORE_Light Tension', 'Rock'),
  ('FILM SCORE_Light Tension', 'Piano'),
  ('FILM SCORE_Light Tension', 'Ambient'),
  ('FILM SCORE_Light Tension', 'Acoustic'),
  ('FILM SCORE_Light Tension', 'Percussion'),
  ('FILM SCORE_Light Tension', 'Hip Hop/Rap'),
  ('FILM SCORE_Light Tension', 'Americana'),
  ('FILM SCORE_Light Tension', 'Funk'),
  ('FILM SCORE_Light Tension', 'Reggae'),
  ('FILM SCORE_Light Tension', 'Hick Hop'),
  ('FILM SCORE_Melancholic', 'Orchestral'),
  ('FILM SCORE_Melancholic', 'String Quartet'),
  ('FILM SCORE_Melancholic', 'Hybrid'),
  ('FILM SCORE_Melancholic', 'Rock'),
  ('FILM SCORE_Melancholic', 'Acoustic'),
  ('FILM SCORE_Melancholic', 'Electronic'),
  ('FILM SCORE_Melancholic', 'Country'),
  ('FILM SCORE_Melancholic', 'Piano'),
  ('FILM SCORE_Melancholic', 'Hip Hop/Rap'),
  ('FILM SCORE_Melancholic', 'Ambient'),
  ('FILM SCORE_Melancholic', 'Percussion'),
  ('FILM SCORE_Melancholic', 'Jazz'),
  ('FILM SCORE_Melancholic', 'Americana'),
  ('FILM SCORE_Melancholic', 'World-Ethnic'),
  ('FILM SCORE_Mysterious', 'Orchestral'),
  ('FILM SCORE_Mysterious', 'Industrial'),
  ('FILM SCORE_Mysterious', 'Hybrid'),
  ('FILM SCORE_Mysterious', 'Electronic'),
  ('FILM SCORE_Mysterious', 'Jazz'),
  ('FILM SCORE_Mysterious', 'Rock'),
  ('FILM SCORE_Mysterious', 'Piano'),
  ('FILM SCORE_Mysterious', 'Ambient'),
  ('FILM SCORE_Mysterious', 'Acoustic'),
  ('FILM SCORE_Mysterious', 'Sci-Fi'),
  ('FILM SCORE_Mysterious', 'Western'),
  ('FILM SCORE_Mysterious', 'Hip Hop/Rap'),
  ('FILM SCORE_Mysterious', 'Percussion'),
  ('FILM SCORE_Mysterious', 'Americana'),
  ('FILM SCORE_Mysterious', 'World-Ethnic'),
  ('FILM SCORE_Mysterious', 'Country'),
  ('FILM SCORE_Regal', 'Orchestral'),
  ('FILM SCORE_Regal', 'Baroque'),
  ('FILM SCORE_Regal', 'String Quartet'),
  ('FILM SCORE_Romantic', 'Orchestral'),
  ('FILM SCORE_Romantic', 'Industrial'),
  ('FILM SCORE_Romantic', 'Hybrid'),
  ('FILM SCORE_Romantic', 'Electronic'),
  ('FILM SCORE_Romantic', 'Jazz'),
  ('FILM SCORE_Romantic', 'Rock'),
  ('FILM SCORE_Romantic', 'Piano'),
  ('FILM SCORE_Romantic', 'Ambient'),
  ('FILM SCORE_Romantic', 'String Quartet'),
  ('FILM SCORE_Romantic', 'Americana'),
  ('FILM SCORE_Romantic', 'Acoustic'),
  ('FILM SCORE_Serious', 'Orchestral'),
  ('FILM SCORE_Serious', 'Hybrid'),
  ('FILM SCORE_Serious', 'Electronic'),
  ('FILM SCORE_Serious', 'Piano'),
  ('FILM SCORE_Serious', 'Ambient'),
  ('FILM SCORE_Serious', 'Percussion'),
  ('FILM SCORE_Serious', 'Rock'),
  ('FILM SCORE_Serious', 'Acoustic'),
  ('FILM SCORE_Sports Package', 'Orchestral'),
  ('FILM SCORE_Sports Package', 'Hybrid'),
  ('FILM SCORE_Sports Package', 'Organ'),
  ('FILM SCORE_Sports Package', 'Rock'),
  ('FILM SCORE_Sports Package', 'College Fight Song'),
  ('FILM SCORE_Tense Beat', 'Orchestral'),
  ('FILM SCORE_Tense Beat', 'Industrial'),
  ('FILM SCORE_Tense Beat', 'Hybrid'),
  ('FILM SCORE_Tense Beat', 'Electronic'),
  ('FILM SCORE_Tense Beat', 'Jazz'),
  ('FILM SCORE_Tense Beat', 'Rock'),
  ('FILM SCORE_Tense Beat', 'Piano'),
  ('FILM SCORE_Tense Beat', 'Ambient'),
  ('FILM SCORE_Tense Beat', 'Percussion'),
  ('FILM SCORE_Tense Drone', 'Orchestral'),
  ('FILM SCORE_Tense Drone', 'Industrial'),
  ('FILM SCORE_Tense Drone', 'Hybrid'),
  ('FILM SCORE_Tense Drone', 'Electronic'),
  ('FILM SCORE_Tense Drone', 'Jazz'),
  ('FILM SCORE_Tense Drone', 'Rock'),
  ('FILM SCORE_Tense Drone', 'Piano'),
  ('FILM SCORE_Tense Drone', 'Ambient'),
  ('FILM SCORE_Tense Pulse', 'Orchestral'),
  ('FILM SCORE_Tense Pulse', 'Industrial'),
  ('FILM SCORE_Tense Pulse', 'Hybrid'),
  ('FILM SCORE_Tense Pulse', 'Electronic'),
  ('FILM SCORE_Tense Pulse', 'Jazz'),
  ('FILM SCORE_Tense Pulse', 'Rock'),
  ('FILM SCORE_Tense Pulse', 'Piano'),
  ('FILM SCORE_Tense Pulse', 'Ambient'),
  ('FILM SCORE_Tense Pulse', 'World-Ethnic'),
  ('FILM SCORE_Tense Pulse', 'Percussion'),
  ('FILM SCORE_Tension', 'Orchestral'),
  ('FILM SCORE_Tension', 'Industrial'),
  ('FILM SCORE_Tension', 'Hybrid'),
  ('FILM SCORE_Tension', 'Electronic'),
  ('FILM SCORE_Tension', 'Jazz'),
  ('FILM SCORE_Tension', 'Rock'),
  ('FILM SCORE_Tension', 'Piano'),
  ('FILM SCORE_Tension', 'Ambient'),
  ('FILM SCORE_Tension', 'Hip Hop/Rap'),
  ('FILM SCORE_Tension', 'Sci-Fi'),
  ('FILM SCORE_Tension', 'Percussion'),
  ('FILM SCORE_Tension', 'Americana'),
  ('FILM SCORE_Tension', 'Western'),
  ('FILM SCORE_Tension', 'Funk'),
  ('FILM SCORE_Tension', 'Hick Hop'),
  ('FILM SCORE_Tension', 'World-Ethnic'),
  ('FILM SCORE_Uplifting', 'Orchestral'),
  ('FILM SCORE_Uplifting', 'Industrial'),
  ('FILM SCORE_Uplifting', 'Hybrid'),
  ('FILM SCORE_Uplifting', 'Electronic'),
  ('FILM SCORE_Uplifting', 'Jazz'),
  ('FILM SCORE_Uplifting', 'Rock'),
  ('FILM SCORE_Uplifting', 'Piano'),
  ('FILM SCORE_Uplifting', 'Ambient'),
  ('FILM SCORE_Uplifting', 'Americana'),
  ('FILM SCORE_Uplifting', 'Hip Hop/Rap'),
  ('FILM SCORE_Uplifting', 'Ukulele'),
  ('FILM SCORE_Uplifting', 'Percussion'),
  ('FILM SCORE_Uplifting', 'Acoustic'),
  ('FILM SCORE_Uplifting', 'World/Ethnic'),
  ('FILM SCORE_Western', 'Rock'),
  ('FILM SCORE_Western', 'Acoustic'),
  ('FILM SCORE_Western', 'Orchestral'),
  ('FILM SCORE_Western', 'Spaghetti Western'),
  ('FILM SCORE_Western', 'Americana'),
  ('FILM SCORE_Western', 'Hybrid'),
  ('FILM SCORE_Whimsical', 'Electronic'),
  ('FILM SCORE_Whimsical', 'Orchestral'),
  ('FILM SCORE_Whimsical', 'Piano'),
  ('FILM SCORE_Whimsical', 'Hybrid'),
  ('FILM SCORE_Whimsical', 'String Quartet'),
  ('FILM SCORE_Whimsical', 'Acoustic'),
  ('FILM SCORE_Whimsical', 'Folk'),
  ('FILM SCORE_Whimsical', 'Circus'),
  ('FILM SCORE_Whimsical', 'Americana'),
  ('FILM SCORE_Whimsical', 'Percussion'),
  ('FILM SCORE_Whimsical', 'Ambient'),
  ('FILM SCORE_Whimsical', 'Ukulele'),
  ('FILM SCORE_Whimsical', 'Hip Hop/Rap'),
  ('FOLK', 'Acoustic'),
  ('FOLK', 'Indie Folk'),
  ('FOLK', 'Folk Rock'),
  ('FOLK', 'Americana'),
  ('FOLK', 'Singer/Songwriter'),
  ('FOLK', 'Acoustic - Americana'),
  ('FOLK', 'Alt Folk'),
  ('FOLK', 'Acoustic - Folk Rock'),
  ('FOLK', 'Cajun'),
  ('GREAT AMERICAN SONGBOOK', 'Timeless'),
  ('GREAT AMERICAN SONGBOOK', 'Old Timey'),
  ('GUITAR STING', 'Acoustic'),
  ('GUITAR STING', 'Electric - Clean'),
  ('GUITAR STING', 'Electric - Heavy'),
  ('GUITAR STING', 'Electric - Metal'),
  ('GUITAR STING', 'Classic'),
  ('GUMSHOE', 'Jazz'),
  ('GUMSHOE', 'Orchestral'),
  ('GUMSHOE', 'Big Band'),
  ('GUMSHOE', 'Rock'),
  ('GUMSHOE', 'Hybrid'),
  ('GUMSHOE', 'Acoustic - Rock'),
  ('HEARTLAND ROCK', 'Country Rock'),
  ('HEARTLAND ROCK', 'Country'),
  ('HEARTLAND ROCK', 'Americana'),
  ('HEARTLAND ROCK', 'Classic Rock'),
  ('HEARTLAND ROCK', 'Folk Rock'),
  ('HEARTLAND ROCK', 'Acoustic - Classic Rock'),
  ('HEARTLAND ROCK', 'Acoustic - Country Rock'),
  ('HEARTLAND ROCK', 'Alternative Rock'),
  ('HEARTLAND ROCK', 'Acoustic - Americana'),
  ('HEARTLAND ROCK', 'Southern Rock'),
  ('HEARTLAND ROCK', 'Acoustic - Alternative Rock'),
  ('HEAVY METAL', 'Thrash Metal'),
  ('HEAVY METAL', 'Black Metal'),
  ('HEAVY METAL', 'Death Metal'),
  ('HEAVY METAL', 'Industrial Metal'),
  ('HEAVY METAL', 'Doom'),
  ('HEAVY METAL', 'Grindcore'),
  ('HEAVY METAL', 'Metalcore'),
  ('HEAVY METAL', 'Progressive Metal'),
  ('HEAVY METAL', 'Folk Metal'),
  ('HEAVY METAL', 'Christian Metal'),
  ('HEAVY METAL', 'Gothic Metal'),
  ('HEAVY METAL', 'Glam Metal'),
  ('HEAVY METAL', 'Power Metal'),
  ('HEAVY METAL', 'Speed Metal'),
  ('HEAVY METAL', 'Post-Metal'),
  ('HEAVY METAL', 'Symphonic Metal'),
  ('HEAVY METAL', 'Extreme Metal'),
  ('HEAVY METAL', 'Alternative Metal'),
  ('HEAVY METAL', 'Groove Metal'),
  ('HIP HOP/RAP', 'Electro'),
  ('HIP HOP/RAP', 'East Coast'),
  ('HIP HOP/RAP', 'West Coast'),
  ('HIP HOP/RAP', 'Classic Hip Hop'),
  ('HIP HOP/RAP', 'Modern Hip Hop'),
  ('HIP HOP/RAP', 'Trap'),
  ('HIP HOP/RAP', 'World-Ethnic'),
  ('HIP HOP/RAP', 'Chill Hop'),
  ('HIP HOP/RAP', 'Alternative Hip Hop'),
  ('HIP HOP/RAP', 'Rock'),
  ('HORROR STING', 'Orchestral'),
  ('HORROR STING', 'Piano'),
  ('HORROR STING', 'Electronic'),
  ('HORROR STING', 'Percussion'),
  ('HOUSE', 'Classic Chicago House'),
  ('HOUSE', 'Deep House'),
  ('HOUSE', 'Progressive House'),
  ('HOUSE', 'Electro House'),
  ('HOUSE', 'Acid House'),
  ('HOUSE', 'Afro House'),
  ('HOUSE', 'Bass House'),
  ('HOUSE', 'Disco House'),
  ('HOUSE', 'French House'),
  ('HOUSE', 'Funky House'),
  ('HOUSE', 'Future House'),
  ('HOUSE', 'Garage House'),
  ('HOUSE', 'Minimal House'),
  ('HOUSE', 'Tribal House'),
  ('HOUSE', 'Tech House'),
  ('HOUSE', 'Tropical House'),
  ('HOUSE', 'Vocal House'),
  ('HOUSE', 'UK Garage'),
  ('JAZZ', 'Piano Trio'),
  ('JAZZ', 'Big Band'),
  ('JAZZ', 'Dixieland'),
  ('JAZZ', 'Smooth'),
  ('JAZZ', 'Western Swing'),
  ('JAZZ', 'Latin'),
  ('JAZZ', 'Swing'),
  ('JAZZ', 'Trad'),
  ('JAZZ', 'Bebop'),
  ('JAZZ', 'Nu Jazz'),
  ('JAZZ', 'Fusion'),
  ('JAZZ', 'New Orleans'),
  ('JAZZ', 'Solo Piano'),
  ('JAZZ', 'Bossa Nova'),
  ('JAZZ', 'Cool Jazz'),
  ('JAZZ', 'Mainstream Jazz'),
  ('JAZZ', 'Second Line Brass Band'),
  ('JAZZ', 'Electroswing'),
  ('JAZZ', 'Burlesque'),
  ('JAZZ', 'Ragtime'),
  ('JAZZ', 'Mambo'),
  ('MARCHING BAND', 'Drumline'),
  ('MARCHING BAND', 'Full Band'),
  ('MILITARY', 'Traditional'),
  ('MILITARY', 'Orchestral'),
  ('MILITARY', 'Fife and Drum Corp'),
  ('MILITARY', 'Percussion'),
  ('NEW AGE', 'Piano'),
  ('NEW AGE', 'Acoustic Guitar'),
  ('NEW AGE', 'Ambient'),
  ('NEW AGE', 'Electronic'),
  ('NEW AGE', 'Percussion'),
  ('NEW AGE', 'Flute'),
  ('OLD TIMEY', 'Saloon Piano'),
  ('OLD TIMEY', 'Sea Shanty'),
  ('OLD TIMEY', 'Americana'),
  ('OLD TIMEY', 'Organ'),
  ('ORCHESTRAL', 'Full Orchestra'),
  ('ORCHESTRAL', 'Strings'),
  ('ORCHESTRAL', 'Woodwinds'),
  ('ORCHESTRAL', 'Brass'),
  ('ORCHESTRAL', 'String Quartet'),
  ('ORCHESTRAL', 'Baroque'),
  ('ORCHESTRAL', 'Modern'),
  ('POLITICAL_Negative', 'Orchestral'),
  ('POLITICAL_Negative', 'Electronic'),
  ('POLITICAL_Negative', 'Percussion'),
  ('POLITICAL_Negative', 'Hybrid'),
  ('POLITICAL_Negative', 'Piano'),
  ('POLITICAL_Uplifting', 'Orchestral'),
  ('POLITICAL_Uplifting', 'Hybrid'),
  ('POLITICAL_Uplifting', 'Piano'),
  ('POLITICAL_Uplifting', 'Rock'),
  ('POP', 'Dance'),
  ('POP', 'Soul'),
  ('POP', 'R&B'),
  ('POP', 'Rock'),
  ('POP', 'Country'),
  ('POP', 'Adult Contemporary'),
  ('POP', 'Electropop'),
  ('POP', 'Funk'),
  ('POP', 'Singer/Songwriter'),
  ('POP', 'Synthpop'),
  ('POP', 'Acoustic - Rock'),
  ('POP', 'Piano'),
  ('POP', 'Future Bass'),
  ('POP', 'Hip Hop/Rap'),
  ('POP', 'Folk'),
  ('POP', 'Chiptune'),
  ('RELIGIOUS', 'Gregorian Chant'),
  ('RELIGIOUS', 'Organ Hymn'),
  ('SFX', 'Sound Design/FX'),
  ('SFX', 'Dramatic Impacts'),
  ('SFX', 'Percussion'),
  ('SINGLE INSTRUMENT BUMPER', 'Rock Guitar'),
  ('SINGLE INSTRUMENT BUMPER', 'Blues Guitar'),
  ('SINGLE INSTRUMENT BUMPER', 'Americana Guitar'),
  ('SINGLE INSTRUMENT BUMPER', 'Folk Guitar'),
  ('SINGLE INSTRUMENT BUMPER', 'Jazz Guitar'),
  ('SINGLE INSTRUMENT BUMPER', 'Folk - Acoustic Guitar'),
  ('SINGLE INSTRUMENT BUMPER', 'Heavy Metal Guitar'),
  ('SINGLE INSTRUMENT BUMPER', 'Blues - Acoustic Guitar'),
  ('SINGLE INSTRUMENT BUMPER', 'Americana - Acoustic Guitar'),
  ('SINGLE INSTRUMENT BUMPER', 'Jazz - Acoustic Guitar'),
  ('SINGLE INSTRUMENT BUMPER', 'Country Guitar'),
  ('SINGLE INSTRUMENT BUMPER', 'Country - Acoustic Guitar'),
  ('SINGLE INSTRUMENT BUMPER', 'Pedal Steel'),
  ('SINGLE INSTRUMENT BUMPER', 'Dobro'),
  ('SINGLE INSTRUMENT BUMPER', 'Dulcimer'),
  ('SINGLE INSTRUMENT BUMPER', 'Mandolin'),
  ('SINGLE INSTRUMENT BUMPER', 'Ukulele'),
  ('SINGLE INSTRUMENT BUMPER', 'Upright Bass'),
  ('SINGLE INSTRUMENT BUMPER', 'Harmonica Clean'),
  ('SINGLE INSTRUMENT BUMPER', 'Harmonica Amp'),
  ('SINGLE INSTRUMENT BUMPER', 'Banjo'),
  ('SINGLE INSTRUMENT BUMPER', 'Autoharp'),
  ('SINGLE INSTRUMENT BUMPER', 'Saloon Piano'),
  ('SINGLE INSTRUMENT BUMPER', 'Bells'),
  ('SINGLE INSTRUMENT BUMPER', 'Castanets'),
  ('SINGLE INSTRUMENT BUMPER', 'Cymbal'),
  ('SINGLE INSTRUMENT BUMPER', 'Drum Roll'),
  ('SINGLE INSTRUMENT BUMPER', 'Bass Guitar'),
  ('SINGLE INSTRUMENT BUMPER', 'Bottles'),
  ('SINGLE INSTRUMENT BUMPER', 'Guitar'),
  ('SINGLE INSTRUMENT BUMPER', 'Hurdy Gurdy'),
  ('SINGLE INSTRUMENT BUMPER', 'Jaw Harp'),
  ('SINGLE INSTRUMENT BUMPER', 'Rock - Acoustic Guitar'),
  ('SINGLE INSTRUMENT BUMPER', 'Rub Board'),
  ('SINGLE INSTRUMENT BUMPER', 'Shells'),
  ('SINGLE INSTRUMENT BUMPER', 'Slide Guitar - Clean'),
  ('SINGLE INSTRUMENT BUMPER', 'Slide Guitar - Amp'),
  ('SINGLE INSTRUMENT BUMPER', 'Rock - Slide Guitar'),
  ('SINGLE INSTRUMENT BUMPER', 'Organ'),
  ('SOUL_R AND B', 'Contemporary R and B'),
  ('SOUL_R AND B', 'Doo Wop'),
  ('SOUL_R AND B', 'Funk'),
  ('SOUL_R AND B', 'Motown'),
  ('SOUL_R AND B', 'Neo-Soul'),
  ('SOUL_R AND B', 'Soul'),
  ('SOUL_R AND B', 'Gospel'),
  ('TECHNO', 'Synthpop'),
  ('TECHNO', 'Classic Techno'),
  ('TECHNO', 'Melodic Techno'),
  ('TECHNO', 'Leftfield Techno'),
  ('TECHNO', 'Dub Techno'),
  ('TECHNO', 'Detroit Techno'),
  ('TECHNO', 'Minimal Techno'),
  ('TRADITIONAL', 'Rock'),
  ('TRADITIONAL', 'Acoustic'),
  ('TRADITIONAL', 'Orchestral'),
  ('TRADITIONAL', 'Electronic'),
  ('TRADITIONAL', 'Harpsichord'),
  ('TRADITIONAL', 'Organ'),
  ('TRADITIONAL', 'Americana'),
  ('TRANCE', 'Classic Trance'),
  ('TRANCE', 'Arena Trance'),
  ('TV THEME', 'Electronic'),
  ('TV THEME', 'Hybrid'),
  ('TV THEME', 'Rock'),
  ('TV THEME', 'Funk'),
  ('TV THEME', 'Game Show'),
  ('WORLD-ETHNIC', 'Polka'),
  ('WORLD-ETHNIC', 'French'),
  ('WORLD-ETHNIC', 'Italian'),
  ('WORLD-ETHNIC', 'Russian'),
  ('WORLD-ETHNIC', 'Latin'),
  ('WORLD-ETHNIC', 'Indian'),
  ('WORLD-ETHNIC', 'Spain'),
  ('WORLD-ETHNIC', 'Mexican Folk'),
  ('WORLD-ETHNIC', 'Middle Eastern'),
  ('WORLD-ETHNIC', 'Percussion'),
  ('WORLD-ETHNIC', 'Afro Beat'),
  ('WORLD-ETHNIC', 'African'),
  ('WORLD-ETHNIC', 'Latin Pop'),
  ('WORLD-ETHNIC', 'Reggae'),
  ('WORLD-ETHNIC', 'Australian'),
  ('WORLD-ETHNIC', 'Spanish Guitar'),
  ('WORLD-ETHNIC', 'Hawaiian'),
  ('WORLD-ETHNIC', 'Celtic'),
  ('WORLD-ETHNIC', 'Samba'),
  ('WORLD-ETHNIC', 'Calypso'),
  ('WORLD-ETHNIC', 'Mexican'),
  ('WORLD-ETHNIC', 'Acoustic - Gypsy Punk'),
  ('WORLD-ETHNIC', 'Native American'),
  ('WORLD-ETHNIC', 'Asian'),
  ('WORLD-ETHNIC', 'Reggaeton'),
  ('WORLD-ETHNIC', 'Acoustic - Latin Pop'),
  ('WORLD-ETHNIC', 'Mariachi'),
  ('WORLD-ETHNIC', 'Cajun')
) AS sg(genre_name, sub_genre_name) ON pg.primary_genre_name = sg.genre_name
ON CONFLICT (primary_genre_id, sub_genre_name) DO NOTHING;
