CREATE TABLE IF NOT EXISTS mmw_metapaks (
  metapak_id  SERIAL PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS mmw_phrases (
  phrase_id   SERIAL PRIMARY KEY,
  phrase      TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS mmw_metapak_phrases (
  metapak_id  INT NOT NULL REFERENCES mmw_metapaks(metapak_id),
  phrase_id   INT NOT NULL REFERENCES mmw_phrases(phrase_id),
  PRIMARY KEY (metapak_id, phrase_id)
);

INSERT INTO mmw_phrases (phrase) VALUES
  ('2 words: Mai Tai!'),
  ('Accept my fate'),
  ('Achieve my dreams'),
  ('Act cool'),
  ('Act crazy'),
  ('Act defiant'),
  ('Act goofy'),
  ('Act like I don''t have a trust fund'),
  ('Act like a 5 year old'),
  ('Act like a five year old'),
  ('Act silly'),
  ('Act upbeat'),
  ('Align my Chakras'),
  ('Allow happiness in'),
  ('Allow my mind to wander'),
  ('Ask for another chance'),
  ('Assemble my sniper rifle'),
  ('Attend a ball'),
  ('Attend an event in the city'),
  ('Bake cookies'),
  ('Bake weed brownies'),
  ('Bang a gong'),
  ('Bang my head'),
  ('Bask in glory'),
  ('Battle'),
  ('Be a COWBOY!!'),
  ('Be a Geisha'),
  ('Be a Samurai'),
  ('Be a better person'),
  ('Be a clown'),
  ('Be a frenemy'),
  ('Be a golden god'),
  ('Be a smooth operator'),
  ('Be adventurous'),
  ('Be all catty'),
  ('Be all saucy'),
  ('Be alone'),
  ('Be amusing'),
  ('Be awesome in slow motion'),
  ('Be blue'),
  ('Be charming'),
  ('Be cheeky'),
  ('Be confident'),
  ('Be courageous'),
  ('Be crowned king'),
  ('Be curious'),
  ('Be free'),
  ('Be funny'),
  ('Be happy'),
  ('Be in Texas'),
  ('Be in a corn field'),
  ('Be in a cornfield'),
  ('Be in nature'),
  ('Be in the south'),
  ('Be involved in some dark plotting'),
  ('Be one with the music'),
  ('Be one with the universe'),
  ('Be positive'),
  ('Be pretentious'),
  ('Be proud'),
  ('Be realistic'),
  ('Be righteous'),
  ('Be sad'),
  ('Be smooth'),
  ('Be undercover'),
  ('Become a vegan'),
  ('Befriend a mammoth'),
  ('Beg forgiveness'),
  ('Belong to a secret society'),
  ('Belt out a song'),
  ('Betray my comrade'),
  ('Betray someone'),
  ('Better myself'),
  ('Bite my nails'),
  ('Blend in'),
  ('Blow money on a concert tee-shirt'),
  ('Blow things up'),
  ('Blow up some animal balloons'),
  ('Bob my head to the rhythm'),
  ('Boogie'),
  ('Boogie down'),
  ('Brawl'),
  ('Break up'),
  ('Breathe in and out'),
  ('Bribe the concierge'),
  ('Brood'),
  ('Burn incense'),
  ('Buy a Persian Rug'),
  ('Buy a compass'),
  ('Buy essential oils'),
  ('Buy some go-go boots'),
  ('Buy some sunglasses'),
  ('Call a ghost hunter'),
  ('Call an exorcist'),
  ('Call an old friend'),
  ('Call her a bitch!'),
  ('Call my boyfriend'),
  ('Call my friends "Brah"'),
  ('Call my loved ones'),
  ('Cast a spell'),
  ('Cast a spell on you'),
  ('Cause a system malfunction'),
  ('Change the world'),
  ('Chant Ohm'),
  ('Chase after nuts'),
  ('Chase the bad guy through the parking garage'),
  ('Chase through foreign streets'),
  ('Check into rehab'),
  ('Check the wardrobes'),
  ('Check under the bed for ghosts'),
  ('Check under the bed for monsters'),
  ('Chill in front of a fire'),
  ('Chill out'),
  ('Chug a cold one'),
  ('Clap my hands'),
  ('Climb Mount Fuji'),
  ('Collect evidence'),
  ('Commit a crime'),
  ('Confront enemies'),
  ('Confront my past'),
  ('Conspire'),
  ('Conspire and configure'),
  ('Conspire to free someone from prison'),
  ('Contemplate'),
  ('Contemplate something deep'),
  ('Country line dance'),
  ('Cover my eyes'),
  ('Cover the mirrors'),
  ('Cradle a baby'),
  ('Cry'),
  ('Cry in my beer'),
  ('Curl up in a blanket'),
  ('DJ'),
  ('DOMINATE at Beer Pong!!!'),
  ('DOMINATE the mosh pit!!!!'),
  ('Dance'),
  ('Dance a two step'),
  ('Dance in the streets'),
  ('Dance like no one is watching'),
  ('Dance with my hands in the air'),
  ('Dance with the enemy'),
  ('Daydream'),
  ('Deceive all suspects'),
  ('Destroy all evidence'),
  ('Divulge information'),
  ('Do a headstand'),
  ('Do the Can-Can'),
  ('Do the Charleston'),
  ('Dont let her go'),
  ('Douse in Patchouli oil'),
  ('Draw my six-Shooter'),
  ('Dream'),
  ('Dream big'),
  ('Dress like a pimp'),
  ('Dress to the nines'),
  ('Drift Away'),
  ('Drink'),
  ('Drink Chianti'),
  ('Drink Kombucha'),
  ('Drink a cold one'),
  ('Drink anything with an umbrella in it'),
  ('Drink moonshine'),
  ('Drink whiskey'),
  ('Drive'),
  ('Drive a tractor'),
  ('Drive a truck'),
  ('Drive at night'),
  ('Drive like hell'),
  ('Drive real fast'),
  ('Drive slow'),
  ('Drive through the countryside'),
  ('Drive with the top down'),
  ('Drive with the windows down'),
  ('Drop acid'),
  ('Drop acid and eat a taco'),
  ('Duel'),
  ('Duel in an old western'),
  ('Eat BBQ'),
  ('Eat Tebouleh'),
  ('Eat apple pie'),
  ('Eat exotic food'),
  ('Embark on a quest'),
  ('Enjoy'),
  ('Enjoy a summer evening'),
  ('Enter the Matrix'),
  ('Escape'),
  ('Escape from prison'),
  ('Escape from the zoo'),
  ('Experience a golden sunset'),
  ('Explore'),
  ('Explore Chinatown'),
  ('Explore Exotic Locations'),
  ('Explore a dusty attic'),
  ('Explore a hidden cave'),
  ('Explore dark tunnels'),
  ('Explore the desert'),
  ('Explore the forest after dark'),
  ('Explore the hallways after dark'),
  ('Explore the world'),
  ('Face horrible consequences'),
  ('Face my demons'),
  ('Face the consequences'),
  ('Fall asleep during Shavasana'),
  ('Feel defeated'),
  ('Feel good'),
  ('Feel groovy'),
  ('Feel sad'),
  ('Feel safe secure + strong'),
  ('Feel sentimental'),
  ('Feel sorry for myself'),
  ('Feel the irony'),
  ('Feel the power'),
  ('Feel the weirdness'),
  ('Feel the wind in my hair'),
  ('Feel very tense'),
  ('Fight against the darkness'),
  ('Fight for my country'),
  ('Fight for my freedom'),
  ('Fight for the winning goal'),
  ('Fight in the Highlands'),
  ('Figure out what''s going on'),
  ('Find a safe place to hide'),
  ('Find a way out'),
  ('Find a way to win'),
  ('Find inner peace'),
  ('Find my determination!'),
  ('Find my inner peace'),
  ('Find my most trusted friend'),
  ('Find myself'),
  ('Find peace'),
  ('Find the shipment of coke in the warehouse'),
  ('Fire up the shredder'),
  ('Flirt'),
  ('Flirt with the drummer'),
  ('Float away'),
  ('Fly on my broomstick'),
  ('Forget my troubles'),
  ('Funk it up'),
  ('Gather evidence'),
  ('Get Abducted by Aliens'),
  ('Get a facial'),
  ('Get a massage'),
  ('Get a pair of night vision goggles'),
  ('Get all defiant'),
  ('Get all hipster'),
  ('Get all self righteous'),
  ('Get captivated'),
  ('Get captivated by an exotic woman'),
  ('Get close to you'),
  ('Get depressed'),
  ('Get drunk'),
  ('Get drunk in a dive bar'),
  ('Get focused'),
  ('Get funky'),
  ('Get high'),
  ('Get hot and sweaty'),
  ('Get in a trance'),
  ('Get into a high speed chase'),
  ('Get lost in video games'),
  ('Get mad intimate'),
  ('Get my mind blown'),
  ('Get my palm read'),
  ('Get on a submarine'),
  ('Get out of the city before it explodes'),
  ('Get ready for the weekend'),
  ('Get real sexy'),
  ('Get revenge'),
  ('Get sadly drunk'),
  ('Get some pep in my step'),
  ('Get sweet revenge'),
  ('Get to the bottom'),
  ('Get up to no good'),
  ('Give in'),
  ('Give up on us'),
  ('Go birdwatching'),
  ('Go for it!'),
  ('Go home'),
  ('Go on a mission'),
  ('Go on a special mission with some penguins'),
  ('Go on a weekend retreat'),
  ('Go on an adventure'),
  ('Go on vacation'),
  ('Go sight seeing in Tokyo'),
  ('Go through the healing process'),
  ('Go to Kentucky'),
  ('Go to a funeral'),
  ('Go to the jungle'),
  ('Go to the market to buy spices'),
  ('Go to the zoo'),
  ('Go where no man has ever gone before'),
  ('Go wine tasting'),
  ('Gossip Gossip Gossip'),
  ('Gossip on my iPhone'),
  ('Grab a fiddle and join in'),
  ('Grab my washboard and harmonica'),
  ('Groove'),
  ('Groove with my girl'),
  ('Grow as a human being'),
  ('Grow hydroponic pot'),
  ('Grow old with you'),
  ('Hail the king'),
  ('Hang at a speakeasy'),
  ('Hang my head'),
  ('Hang out in a coffee shop'),
  ('Hang with Tony Bourdain'),
  ('Hangout in a coffee shop'),
  ('Have Liam Neeson''s special set of skills'),
  ('Have a 90''s flashback'),
  ('Have a ROM COM fest in my apartment'),
  ('Have a dark sense of humour'),
  ('Have a fake British accent'),
  ('Have a great day'),
  ('Have a moment'),
  ('Have a one night stand'),
  ('Have a pet owl'),
  ('Have a picnic'),
  ('Have a picnic in a meadow'),
  ('Have a picnic in the meadow'),
  ('Have a rowdy night out'),
  ('Have a secret meeting in the lobby'),
  ('Have a spa weekend with the girls'),
  ('Have an affair'),
  ('Have faith'),
  ('Have fun with my friends'),
  ('Have hope'),
  ('Have magical powers'),
  ('Hide'),
  ('Hide behind the sofa'),
  ('Hide inside a container'),
  ('Hide under a blanket'),
  ('Hide under the duvet'),
  ('Hide!'),
  ('Hit a warehouse party'),
  ('Hit the beach!'),
  ('Hit the dance floor'),
  ('Hit the game winning shot'),
  ('Hold someone close'),
  ('Hold up a lighter'),
  ('Hug a hippie'),
  ('Hum a tune'),
  ('Hunt down the monster in his own cave'),
  ('Hunt gators'),
  ('Ice skate'),
  ('Infiltrate a terrorist cell'),
  ('Inspire people'),
  ('Investigate'),
  ('Isolate myself'),
  ('Jam'),
  ('Jump'),
  ('Jump around'),
  ('KILL BILL!'),
  ('Keep my eyes shut'),
  ('Kick back with a cocktail'),
  ('Kiss'),
  ('Kiss another man on the cheek'),
  ('Lament'),
  ('Laugh'),
  ('Laugh WAY over the top'),
  ('Lay back in a field'),
  ('Lay by the pool'),
  ('Lay under a palm tree'),
  ('Lay you down by the fire'),
  ('Lead a high speed pursuit'),
  ('Learn Kung Fu'),
  ('Leave the gun, Take the Canoli'),
  ('Let my imagination run wild'),
  ('Lie back in a field'),
  ('Lie back in the club'),
  ('Lie by the pool'),
  ('Listen to old Stones records'),
  ('Listen to some old Stones records'),
  ('Live life'),
  ('Lock and load'),
  ('Lock the doors'),
  ('Look for clues'),
  ('Look through a photo album'),
  ('Look through old pictures'),
  ('Lose my inhibitions'),
  ('Lounge'),
  ('Love whatever I just inhaled'),
  ('Make a drastic decision'),
  ('Make an Entrance'),
  ('Make friends with some meerkats'),
  ('Make friends with some pandas'),
  ('Make friendship bracelets'),
  ('Make her jealous'),
  ('Make objects fly'),
  ('Meditate'),
  ('Meet magical creatures'),
  ('Mellow out'),
  ('Miss the good times'),
  ('Miss you'),
  ('Move on'),
  ('Move slowly and carefully'),
  ('Move those hips'),
  ('Move through the world'),
  ('Never forget'),
  ('Obtain secret information'),
  ('One word: FALAFEL'),
  ('One word: HACKYSACK'),
  ('Operate behind curtains'),
  ('Operate undetected'),
  ('Order a martini'),
  ('Order the dumplings'),
  ('Pack my bags'),
  ('Paint my nails black'),
  ('Party'),
  ('Party till the break of dawn'),
  ('Party too hard'),
  ('Pat my own back'),
  ('Peak around the corner'),
  ('Perform under pressure'),
  ('Persevere'),
  ('Pick a fight at a charity event'),
  ('Pick and grin'),
  ('Pick up the pieces'),
  ('Pimp my ride'),
  ('Plan a heist'),
  ('Plan my escape'),
  ('Play N64'),
  ('Play air guitar'),
  ('Play cards in the safe house'),
  ('Play detective'),
  ('Play the banjo'),
  ('Play the jukebox all night'),
  ('Play the tambourine'),
  ('Play video games'),
  ('Play with a giant beach ball'),
  ('Plot'),
  ('Ponder'),
  ('Pop bottles in the VIP section'),
  ('Pound tequila from a dirty glass'),
  ('Practice the art of Feng Shui'),
  ('Practice the art of seduction'),
  ('Prank someone'),
  ('Pray'),
  ('Prepare for the robot battle'),
  ('Protect the President'),
  ('Pull out my old vinyl'),
  ('Pump my fist'),
  ('Pump my fists'),
  ('Punch a wall'),
  ('Push back'),
  ('Push to the front of the crowd'),
  ('Put my heart on my sleeve'),
  ('Put on my cloak of invisibility'),
  ('Put on my cowboy boots'),
  ('Put two in the chest'),
  ('Put your hands together'),
  ('Rage all night'),
  ('Rave'),
  ('Rave till sunrise'),
  ('Reach for the Kleenex'),
  ('Reach for the stars'),
  ('Read One Thousand and One Nights'),
  ('Read a map'),
  ('Read inspirational memes'),
  ('Reflect'),
  ('Relax'),
  ('Release toxins'),
  ('Remember'),
  ('Remember a lost love'),
  ('Reveal that i''m an undercover agent'),
  ('Revolt'),
  ('Ride a Magic Carpet'),
  ('Ride a camel'),
  ('Ride a horse through the canyon'),
  ('Ride a mechanical bull'),
  ('Ride a motorcycle'),
  ('Ride off into the sunset'),
  ('Ride the Hog through the desert'),
  ('Ride through the desert'),
  ('Rise from the ashes victorious'),
  ('Risk my life'),
  ('Rob a bank'),
  ('Rock out'),
  ('Roll a fatty'),
  ('Roll your eyes'),
  ('Rollerblade in South Beach'),
  ('Round up a posse'),
  ('Run away'),
  ('Run like HELL!!!!'),
  ('Sack a kingdom'),
  ('Save the World'),
  ('Save the girl and get the bad guys'),
  ('Save the world'),
  ('Say goodbye'),
  ('Scheme'),
  ('Score backstage passes'),
  ('Scream!'),
  ('Search for clues'),
  ('Seduce'),
  ('See new places'),
  ('Set up a telephone meeting with the Queen'),
  ('Shake some maracas'),
  ('Shake your Money Maker'),
  ('Shake your money maker'),
  ('Share an intimate moment'),
  ('Shoot Pool'),
  ('Shoot Stab + Kill!'),
  ('Shop for shoes'),
  ('Shop for yoga pants'),
  ('Shout YEE HAAWWW!!!'),
  ('Show off'),
  ('Show off my Gucci'),
  ('Sing around the campfire'),
  ('Sing in the shower'),
  ('Sing into a hairbrush'),
  ('Sip a margarita'),
  ('Sip a martini'),
  ('Sip herbal tea'),
  ('Sit on the porch'),
  ('Skip down the road'),
  ('Skip through a field'),
  ('Sleep in the sun'),
  ('Slip on a banana peel'),
  ('Smile and dance and clap my hands'),
  ('Smile like Bobby D'),
  ('Smile like it''s Christmas'),
  ('Smirk mischievously'),
  ('Smoke'),
  ('Smoke a cigarette'),
  ('Smoke a cigarette in a tuxedo'),
  ('Smoke a cuban cigar'),
  ('Snoop around'),
  ('Solve a murder mystery'),
  ('Solve the case'),
  ('Solve the mystery'),
  ('Solve the puzzle'),
  ('Space out'),
  ('Speed down the highway'),
  ('Spend time at home'),
  ('Spray seltzer in someone''s face'),
  ('Spy'),
  ('Stagger Home'),
  ('Stand my ground'),
  ('Star in an Adidas commercial'),
  ('Stare at the woman in the red dress'),
  ('Start a fight club'),
  ('Start a juice cleanse'),
  ('Start getting rowdy'),
  ('Stay in my room'),
  ('Steal a priceless painting'),
  ('Stick sick tricks'),
  ('Stomp + Clap'),
  ('Stomp and dance'),
  ('Stomp my feet'),
  ('Stop worrying'),
  ('Stroll'),
  ('Strut'),
  ('Sunbathe'),
  ('Surf'),
  ('Survive the Apocalypse'),
  ('Sway back and forth'),
  ('Sweat'),
  ('Tailgate'),
  ('Take a contract'),
  ('Take a nap in a hammock'),
  ('Take a yoga class'),
  ('Take it easy'),
  ('Take my clothes off'),
  ('Take my friends and fly to somewhere new'),
  ('Take some pills a hot chick gave me'),
  ('Take the back street'),
  ('Talk behind their back'),
  ('Taunt strangers'),
  ('Tell a joke'),
  ('Tell it like it is'),
  ('Think about the future'),
  ('Throw a pie at someone'),
  ('Time travel'),
  ('Track the enemy'),
  ('Trade my shirt for a grilled cheese'),
  ('Travel back in time to old postcard Europe'),
  ('Travel on horseback'),
  ('Travel the world'),
  ('Travel to Asia'),
  ('Travel to a mysterious location'),
  ('Trip someone'),
  ('Try to get over you'),
  ('Turn down the lights'),
  ('Turn on all the lights'),
  ('Unveil old secrets'),
  ('Use gadgets and electronics'),
  ('Visit a mosque'),
  ('Visit old friends'),
  ('Wage war'),
  ('Wake up to sunshine and birds chirping'),
  ('Walk in the garden'),
  ('Walk in the snow'),
  ('Walk in the suburbs'),
  ('Walk in the woods'),
  ('Walk through a casino like I own the place'),
  ('Walk through a park full of cherry blossom trees'),
  ('Wander around aimlessly'),
  ('Wander the desert'),
  ('Wander the streets'),
  ('Watch cacti'),
  ('Watch the stars'),
  ('Watch the world from a rooftop'),
  ('Watch the world go by from a rooftop'),
  ('Watch them get what they deserve'),
  ('Wear Birkenstocks'),
  ('Wear Harem Pants'),
  ('Wear a black shirt with a white tie'),
  ('Wear a fedora'),
  ('Wear a long dark coat and sunglasses even though it isn’t sunny'),
  ('Wear a pinkie ring'),
  ('Wear a wool hat IN THE SUMMER'),
  ('Wear my hat backwards'),
  ('Wear tie dye'),
  ('Win the fight'),
  ('Win you back'),
  ('Wipe my eyes'),
  ('Wish for a better future'),
  ('Wish things were different'),
  ('Wonder if I will find love'),
  ('Wonder what''s next'),
  ('Worry'),
  ('Write in my diary'),
  ('Yawn like a sleepy baby'),
  ('You’re wondering what the HELL is going on'),
  ('meet with a Russian spy')
ON CONFLICT (phrase) DO NOTHING;

INSERT INTO mmw_metapaks (name) VALUES
  ('007 CHASE'),
  ('60’s SCI FI'),
  ('ADVENTURE FILM'),
  ('AGGRESSIVE ROCK'),
  ('AMERICANA'),
  ('ASIAN'),
  ('BASIC POSITIVE'),
  ('BENNY HILL SILLY'),
  ('BLUEGRASS'),
  ('BRO ROCK'),
  ('CHEEKY COMEDY'),
  ('CHILL OUT'),
  ('CLASSIC ROCK'),
  ('CRYIN’ COUNTRY'),
  ('DANCE PARTY'),
  ('DARK COMEDY'),
  ('DRUNKEN WAITS'),
  ('DUSTY, DRINKIN’ DRIVIN’'),
  ('EDM RAGER'),
  ('EPIC THEME'),
  ('EXTREME TENSION'),
  ('FANTASY MAGICAL'),
  ('FEEL GOOD AMERICANA'),
  ('FEEL GOOD POP'),
  ('FEEL GOOD, GROOVY'),
  ('FUN BLUES'),
  ('GARAGE ROCK'),
  ('GROOVY SOUL'),
  ('HIPPY DIPPY'),
  ('JAM BAND'),
  ('KINDA MYSTERIOUS'),
  ('LATE NIGHT CHILL'),
  ('MAFIA'),
  ('MIDDLE EASTERN'),
  ('MILD MELANCHOLY'),
  ('OLD TIMEY SALOON'),
  ('POP FUN PARTY'),
  ('ROCKABILLY'),
  ('SEXY LOUNGE'),
  ('SEXY SEXY'),
  ('SHIT KICKIN’ COUNTRY'),
  ('SILLY LITE TENSION'),
  ('SPAGHETTI WESTERN'),
  ('SPOOKY THRILLER'),
  ('SPORTS PAK'),
  ('SPY MOVIE TENSION'),
  ('TRIPPY'),
  ('WARM + FUZZY'),
  ('WICKED SAD'),
  ('ZEN')
ON CONFLICT (name) DO NOTHING;

INSERT INTO mmw_metapak_phrases (metapak_id, phrase_id)
SELECT m.metapak_id, p.phrase_id
FROM (VALUES
  ('AMERICANA', 'Act upbeat'),
  ('AMERICANA', 'Allow happiness in'),
  ('AMERICANA', 'Be happy'),
  ('AMERICANA', 'Be in nature'),
  ('AMERICANA', 'Be positive'),
  ('AMERICANA', 'Call my boyfriend'),
  ('AMERICANA', 'Country line dance'),
  ('AMERICANA', 'Dance a two step'),
  ('AMERICANA', 'Drive through the countryside'),
  ('AMERICANA', 'Enjoy a summer evening'),
  ('AMERICANA', 'Feel good'),
  ('AMERICANA', 'Feel groovy'),
  ('AMERICANA', 'Feel safe secure + strong'),
  ('AMERICANA', 'Feel sentimental'),
  ('AMERICANA', 'Find peace'),
  ('AMERICANA', 'Grab a fiddle and join in'),
  ('AMERICANA', 'Have a picnic in the meadow'),
  ('AMERICANA', 'Hold someone close'),
  ('AMERICANA', 'Hum a tune'),
  ('AMERICANA', 'Laugh'),
  ('AMERICANA', 'Lay back in a field'),
  ('AMERICANA', 'Mellow out'),
  ('AMERICANA', 'Pick and grin'),
  ('AMERICANA', 'Ponder'),
  ('AMERICANA', 'Reflect'),
  ('AMERICANA', 'Relax'),
  ('AMERICANA', 'Sit on the porch'),
  ('AMERICANA', 'Skip through a field'),
  ('AMERICANA', 'Smile like it''s Christmas'),
  ('AMERICANA', 'Stop worrying'),
  ('AMERICANA', 'Sway back and forth'),
  ('AMERICANA', 'Take it easy'),
  ('AMERICANA', 'Wake up to sunshine and birds chirping'),
  ('AMERICANA', 'Walk in the garden'),
  ('AMERICANA', 'Walk in the woods'),
  ('AMERICANA', 'Watch the stars'),
  ('AMERICANA', 'Write in my diary'),
  ('CRYIN’ COUNTRY', 'Allow my mind to wander'),
  ('CRYIN’ COUNTRY', 'Be blue'),
  ('CRYIN’ COUNTRY', 'Be in Texas'),
  ('CRYIN’ COUNTRY', 'Be sad'),
  ('CRYIN’ COUNTRY', 'Chug a cold one'),
  ('CRYIN’ COUNTRY', 'Drink whiskey'),
  ('CRYIN’ COUNTRY', 'Drive a tractor'),
  ('CRYIN’ COUNTRY', 'Eat apple pie'),
  ('CRYIN’ COUNTRY', 'Eat BBQ'),
  ('CRYIN’ COUNTRY', 'Enjoy a summer evening'),
  ('CRYIN’ COUNTRY', 'Feel sad'),
  ('CRYIN’ COUNTRY', 'Feel sentimental'),
  ('CRYIN’ COUNTRY', 'Feel sorry for myself'),
  ('CRYIN’ COUNTRY', 'Get drunk'),
  ('CRYIN’ COUNTRY', 'Get drunk in a dive bar'),
  ('CRYIN’ COUNTRY', 'Get sadly drunk'),
  ('CRYIN’ COUNTRY', 'Go to Kentucky'),
  ('CRYIN’ COUNTRY', 'Hang my head'),
  ('CRYIN’ COUNTRY', 'Have faith'),
  ('CRYIN’ COUNTRY', 'Lament'),
  ('CRYIN’ COUNTRY', 'Move on'),
  ('CRYIN’ COUNTRY', 'Put on my cowboy boots'),
  ('CRYIN’ COUNTRY', 'Say goodbye'),
  ('CRYIN’ COUNTRY', 'Sing around the campfire'),
  ('CRYIN’ COUNTRY', 'Stroll'),
  ('CRYIN’ COUNTRY', 'Try to get over you'),
  ('CRYIN’ COUNTRY', 'Wipe my eyes'),
  ('CRYIN’ COUNTRY', 'Wonder what''s next'),
  ('SHIT KICKIN’ COUNTRY', 'Be a COWBOY!!'),
  ('SHIT KICKIN’ COUNTRY', 'Be all saucy'),
  ('SHIT KICKIN’ COUNTRY', 'Be in a cornfield'),
  ('SHIT KICKIN’ COUNTRY', 'Be in nature'),
  ('SHIT KICKIN’ COUNTRY', 'Be in Texas'),
  ('SHIT KICKIN’ COUNTRY', 'Be in the south'),
  ('SHIT KICKIN’ COUNTRY', 'Chug a cold one'),
  ('SHIT KICKIN’ COUNTRY', 'Country line dance'),
  ('SHIT KICKIN’ COUNTRY', 'Dance a two step'),
  ('SHIT KICKIN’ COUNTRY', 'Draw my six-Shooter'),
  ('SHIT KICKIN’ COUNTRY', 'Drink a cold one'),
  ('SHIT KICKIN’ COUNTRY', 'Drink moonshine'),
  ('SHIT KICKIN’ COUNTRY', 'Drink whiskey'),
  ('SHIT KICKIN’ COUNTRY', 'Drive a tractor'),
  ('SHIT KICKIN’ COUNTRY', 'Drive a truck'),
  ('SHIT KICKIN’ COUNTRY', 'Duel in an old western'),
  ('SHIT KICKIN’ COUNTRY', 'Get drunk'),
  ('SHIT KICKIN’ COUNTRY', 'Get drunk in a dive bar'),
  ('SHIT KICKIN’ COUNTRY', 'Go to Kentucky'),
  ('SHIT KICKIN’ COUNTRY', 'Grab my washboard and harmonica'),
  ('SHIT KICKIN’ COUNTRY', 'Hang at a speakeasy'),
  ('SHIT KICKIN’ COUNTRY', 'Hang with Tony Bourdain'),
  ('SHIT KICKIN’ COUNTRY', 'Have a picnic'),
  ('SHIT KICKIN’ COUNTRY', 'Hunt gators'),
  ('SHIT KICKIN’ COUNTRY', 'Jam'),
  ('SHIT KICKIN’ COUNTRY', 'Play the banjo'),
  ('SHIT KICKIN’ COUNTRY', 'Put on my cowboy boots'),
  ('SHIT KICKIN’ COUNTRY', 'Ride a horse through the canyon'),
  ('SHIT KICKIN’ COUNTRY', 'Ride a mechanical bull'),
  ('SHIT KICKIN’ COUNTRY', 'Ride a motorcycle'),
  ('SHIT KICKIN’ COUNTRY', 'Ride the Hog through the desert'),
  ('SHIT KICKIN’ COUNTRY', 'Ride through the desert'),
  ('SHIT KICKIN’ COUNTRY', 'Round up a posse'),
  ('SHIT KICKIN’ COUNTRY', 'Shout YEE HAAWWW!!!'),
  ('SHIT KICKIN’ COUNTRY', 'Sing around the campfire'),
  ('SHIT KICKIN’ COUNTRY', 'Sit on the porch'),
  ('SHIT KICKIN’ COUNTRY', 'Smoke a cigarette'),
  ('SHIT KICKIN’ COUNTRY', 'Stomp + Clap'),
  ('SHIT KICKIN’ COUNTRY', 'Travel on horseback'),
  ('SHIT KICKIN’ COUNTRY', 'Wander the desert'),
  ('SHIT KICKIN’ COUNTRY', 'Wear my hat backwards'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Be in Texas'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Chug a cold one'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Draw my six-Shooter'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Drink moonshine'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Drink whiskey'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Drive slow'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Duel in an old western'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Get drunk in a dive bar'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Hang with Tony Bourdain'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Lock and load'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Plan a heist'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Plot'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Pound tequila from a dirty glass'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Put on my cowboy boots'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Ride a horse through the canyon'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Ride a motorcycle'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Ride off into the sunset'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Ride the Hog through the desert'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Ride through the desert'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Round up a posse'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Smoke'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Smoke a cuban cigar'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Start a fight club'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Track the enemy'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Travel on horseback'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Wander the desert'),
  ('DUSTY, DRINKIN’ DRIVIN’', 'Watch cacti'),
  ('FEEL GOOD AMERICANA', 'Be in Texas'),
  ('FEEL GOOD AMERICANA', 'Chug a cold one'),
  ('FEEL GOOD AMERICANA', 'Draw my six-Shooter'),
  ('FEEL GOOD AMERICANA', 'Drink moonshine'),
  ('FEEL GOOD AMERICANA', 'Drink whiskey'),
  ('FEEL GOOD AMERICANA', 'Drive slow'),
  ('FEEL GOOD AMERICANA', 'Duel in an old western'),
  ('FEEL GOOD AMERICANA', 'Get drunk in a dive bar'),
  ('FEEL GOOD AMERICANA', 'Hang with Tony Bourdain'),
  ('FEEL GOOD AMERICANA', 'Lock and load'),
  ('FEEL GOOD AMERICANA', 'Plan a heist'),
  ('FEEL GOOD AMERICANA', 'Plot'),
  ('FEEL GOOD AMERICANA', 'Pound tequila from a dirty glass'),
  ('FEEL GOOD AMERICANA', 'Put on my cowboy boots'),
  ('FEEL GOOD AMERICANA', 'Ride a horse through the canyon'),
  ('FEEL GOOD AMERICANA', 'Ride a motorcycle'),
  ('FEEL GOOD AMERICANA', 'Ride off into the sunset'),
  ('FEEL GOOD AMERICANA', 'Ride the Hog through the desert'),
  ('FEEL GOOD AMERICANA', 'Ride through the desert'),
  ('FEEL GOOD AMERICANA', 'Round up a posse'),
  ('FEEL GOOD AMERICANA', 'Smoke'),
  ('FEEL GOOD AMERICANA', 'Smoke a cuban cigar'),
  ('FEEL GOOD AMERICANA', 'Start a fight club'),
  ('FEEL GOOD AMERICANA', 'Track the enemy'),
  ('FEEL GOOD AMERICANA', 'Travel on horseback'),
  ('FEEL GOOD AMERICANA', 'Wander the desert'),
  ('FEEL GOOD AMERICANA', 'Watch cacti'),
  ('BLUEGRASS', 'Allow happiness in'),
  ('BLUEGRASS', 'Be a COWBOY!!'),
  ('BLUEGRASS', 'Be cheeky'),
  ('BLUEGRASS', 'Be in a corn field'),
  ('BLUEGRASS', 'Be in Texas'),
  ('BLUEGRASS', 'Be in the south'),
  ('BLUEGRASS', 'Be positive'),
  ('BLUEGRASS', 'Chug a cold one'),
  ('BLUEGRASS', 'Dance a two step'),
  ('BLUEGRASS', 'Drink moonshine'),
  ('BLUEGRASS', 'Drive a tractor'),
  ('BLUEGRASS', 'Eat apple pie'),
  ('BLUEGRASS', 'Eat BBQ'),
  ('BLUEGRASS', 'Feel good'),
  ('BLUEGRASS', 'Go to Kentucky'),
  ('BLUEGRASS', 'Grab a fiddle and join in'),
  ('BLUEGRASS', 'Grab my washboard and harmonica'),
  ('BLUEGRASS', 'Pick and grin'),
  ('BLUEGRASS', 'Play the banjo'),
  ('BLUEGRASS', 'Put on my cowboy boots'),
  ('BLUEGRASS', 'Ride a mechanical bull'),
  ('BLUEGRASS', 'Shout YEE HAAWWW!!!'),
  ('BLUEGRASS', 'Stomp + Clap'),
  ('FUN BLUES', 'Be all saucy'),
  ('FUN BLUES', 'Be happy'),
  ('FUN BLUES', 'Boogie'),
  ('FUN BLUES', 'Chug a cold one'),
  ('FUN BLUES', 'Clap my hands'),
  ('FUN BLUES', 'Dance'),
  ('FUN BLUES', 'Drink'),
  ('FUN BLUES', 'Drink a cold one'),
  ('FUN BLUES', 'Drink moonshine'),
  ('FUN BLUES', 'Drive slow'),
  ('FUN BLUES', 'Enjoy a summer evening'),
  ('FUN BLUES', 'Feel good'),
  ('FUN BLUES', 'Feel groovy'),
  ('FUN BLUES', 'Get funky'),
  ('FUN BLUES', 'Get high'),
  ('FUN BLUES', 'Groove with my girl'),
  ('FUN BLUES', 'Hang at a speakeasy'),
  ('FUN BLUES', 'Hang with Tony Bourdain'),
  ('FUN BLUES', 'Have a rowdy night out'),
  ('FUN BLUES', 'Jam'),
  ('FUN BLUES', 'Pimp my ride'),
  ('FUN BLUES', 'Pound tequila from a dirty glass'),
  ('FUN BLUES', 'Rock out'),
  ('FUN BLUES', 'Shoot Pool'),
  ('FUN BLUES', 'Smoke'),
  ('FUN BLUES', 'Stomp + Clap'),
  ('FUN BLUES', 'Strut'),
  ('AGGRESSIVE ROCK', 'Act crazy'),
  ('AGGRESSIVE ROCK', 'Act defiant'),
  ('AGGRESSIVE ROCK', 'Bang a gong'),
  ('AGGRESSIVE ROCK', 'Bang my head'),
  ('AGGRESSIVE ROCK', 'Bask in glory'),
  ('AGGRESSIVE ROCK', 'Battle'),
  ('AGGRESSIVE ROCK', 'Be in the south'),
  ('AGGRESSIVE ROCK', 'Be proud'),
  ('AGGRESSIVE ROCK', 'Blow things up'),
  ('AGGRESSIVE ROCK', 'Brawl'),
  ('AGGRESSIVE ROCK', 'Call her a bitch!'),
  ('AGGRESSIVE ROCK', 'Chase the bad guy through the parking garage'),
  ('AGGRESSIVE ROCK', 'Chug a cold one'),
  ('AGGRESSIVE ROCK', 'Confront enemies'),
  ('AGGRESSIVE ROCK', 'DOMINATE the mosh pit!!!!'),
  ('AGGRESSIVE ROCK', 'Draw my six-Shooter'),
  ('AGGRESSIVE ROCK', 'Drink a cold one'),
  ('AGGRESSIVE ROCK', 'Drink whiskey'),
  ('AGGRESSIVE ROCK', 'Drive like hell'),
  ('AGGRESSIVE ROCK', 'Drive real fast'),
  ('AGGRESSIVE ROCK', 'Duel'),
  ('AGGRESSIVE ROCK', 'Face horrible consequences'),
  ('AGGRESSIVE ROCK', 'Face my demons'),
  ('AGGRESSIVE ROCK', 'Feel the power'),
  ('AGGRESSIVE ROCK', 'Fight for the winning goal'),
  ('AGGRESSIVE ROCK', 'Find a way to win'),
  ('AGGRESSIVE ROCK', 'Find my determination!'),
  ('AGGRESSIVE ROCK', 'Get all defiant'),
  ('AGGRESSIVE ROCK', 'Get all self righteous'),
  ('AGGRESSIVE ROCK', 'Get drunk'),
  ('AGGRESSIVE ROCK', 'Get into a high speed chase'),
  ('AGGRESSIVE ROCK', 'Get lost in video games'),
  ('AGGRESSIVE ROCK', 'Get my mind blown'),
  ('AGGRESSIVE ROCK', 'Get ready for the weekend'),
  ('AGGRESSIVE ROCK', 'Go for it!'),
  ('AGGRESSIVE ROCK', 'Have a one night stand'),
  ('AGGRESSIVE ROCK', 'Have a rowdy night out'),
  ('AGGRESSIVE ROCK', 'Hold up a lighter'),
  ('AGGRESSIVE ROCK', 'Hunt gators'),
  ('AGGRESSIVE ROCK', 'Infiltrate a terrorist cell'),
  ('AGGRESSIVE ROCK', 'Jam'),
  ('AGGRESSIVE ROCK', 'KILL BILL!'),
  ('AGGRESSIVE ROCK', 'Lead a high speed pursuit'),
  ('AGGRESSIVE ROCK', 'Lock and load'),
  ('AGGRESSIVE ROCK', 'Make a drastic decision'),
  ('AGGRESSIVE ROCK', 'Paint my nails black'),
  ('AGGRESSIVE ROCK', 'Party too hard'),
  ('AGGRESSIVE ROCK', 'Pimp my ride'),
  ('AGGRESSIVE ROCK', 'Play air guitar'),
  ('AGGRESSIVE ROCK', 'Play video games'),
  ('AGGRESSIVE ROCK', 'Plot'),
  ('AGGRESSIVE ROCK', 'Pound tequila from a dirty glass'),
  ('AGGRESSIVE ROCK', 'Pump my fist'),
  ('AGGRESSIVE ROCK', 'Pump my fists'),
  ('AGGRESSIVE ROCK', 'Punch a wall'),
  ('AGGRESSIVE ROCK', 'Put two in the chest'),
  ('AGGRESSIVE ROCK', 'Rage all night'),
  ('AGGRESSIVE ROCK', 'Revolt'),
  ('AGGRESSIVE ROCK', 'Ride the Hog through the desert'),
  ('AGGRESSIVE ROCK', 'Ride through the desert'),
  ('AGGRESSIVE ROCK', 'Rock out'),
  ('AGGRESSIVE ROCK', 'Round up a posse'),
  ('AGGRESSIVE ROCK', 'Shoot Stab + Kill!'),
  ('AGGRESSIVE ROCK', 'Speed down the highway'),
  ('AGGRESSIVE ROCK', 'Start a fight club'),
  ('AGGRESSIVE ROCK', 'Start getting rowdy'),
  ('AGGRESSIVE ROCK', 'Sweat'),
  ('AGGRESSIVE ROCK', 'Taunt strangers'),
  ('AGGRESSIVE ROCK', 'Wage war'),
  ('AGGRESSIVE ROCK', 'Win the fight'),
  ('BRO ROCK', 'Bang my head'),
  ('BRO ROCK', 'Be happy'),
  ('BRO ROCK', 'Be positive'),
  ('BRO ROCK', 'Brawl'),
  ('BRO ROCK', 'Chug a cold one'),
  ('BRO ROCK', 'DOMINATE at Beer Pong!!!'),
  ('BRO ROCK', 'Drink'),
  ('BRO ROCK', 'Drink a cold one'),
  ('BRO ROCK', 'Drive real fast'),
  ('BRO ROCK', 'Drive with the windows down'),
  ('BRO ROCK', 'Enjoy a summer evening'),
  ('BRO ROCK', 'Feel good'),
  ('BRO ROCK', 'Get drunk'),
  ('BRO ROCK', 'Get high'),
  ('BRO ROCK', 'Get lost in video games'),
  ('BRO ROCK', 'Get ready for the weekend'),
  ('BRO ROCK', 'Go for it!'),
  ('BRO ROCK', 'Have a rowdy night out'),
  ('BRO ROCK', 'Jam'),
  ('BRO ROCK', 'Party'),
  ('BRO ROCK', 'Party too hard'),
  ('BRO ROCK', 'Play air guitar'),
  ('BRO ROCK', 'Play video games'),
  ('BRO ROCK', 'Pump my fist'),
  ('BRO ROCK', 'Surf'),
  ('BRO ROCK', 'Wear my hat backwards'),
  ('GARAGE ROCK', 'Act defiant'),
  ('GARAGE ROCK', 'Bang a gong'),
  ('GARAGE ROCK', 'Battle'),
  ('GARAGE ROCK', 'Be all saucy'),
  ('GARAGE ROCK', 'Blow things up'),
  ('GARAGE ROCK', 'Brawl'),
  ('GARAGE ROCK', 'Buy some go-go boots'),
  ('GARAGE ROCK', 'Chug a cold one'),
  ('GARAGE ROCK', 'Clap my hands'),
  ('GARAGE ROCK', 'Dance'),
  ('GARAGE ROCK', 'DOMINATE at Beer Pong!!!'),
  ('GARAGE ROCK', 'Drink a cold one'),
  ('GARAGE ROCK', 'Drink whiskey'),
  ('GARAGE ROCK', 'Drive like hell'),
  ('GARAGE ROCK', 'Drive real fast'),
  ('GARAGE ROCK', 'Drop acid'),
  ('GARAGE ROCK', 'Embark on a quest'),
  ('GARAGE ROCK', 'Feel groovy'),
  ('GARAGE ROCK', 'Find the shipment of coke in the warehouse'),
  ('GARAGE ROCK', 'Get all defiant'),
  ('GARAGE ROCK', 'Get all hipster'),
  ('GARAGE ROCK', 'Get captivated by an exotic woman'),
  ('GARAGE ROCK', 'Get drunk'),
  ('GARAGE ROCK', 'Get drunk in a dive bar'),
  ('GARAGE ROCK', 'Get high'),
  ('GARAGE ROCK', 'Get hot and sweaty'),
  ('GARAGE ROCK', 'Get into a high speed chase'),
  ('GARAGE ROCK', 'Get my mind blown'),
  ('GARAGE ROCK', 'Get ready for the weekend'),
  ('GARAGE ROCK', 'Get revenge'),
  ('GARAGE ROCK', 'Groove with my girl'),
  ('GARAGE ROCK', 'Hang at a speakeasy'),
  ('GARAGE ROCK', 'Hang with Tony Bourdain'),
  ('GARAGE ROCK', 'Have a one night stand'),
  ('GARAGE ROCK', 'Have a rowdy night out'),
  ('GARAGE ROCK', 'Listen to some old Stones records'),
  ('GARAGE ROCK', 'Love whatever I just inhaled'),
  ('GARAGE ROCK', 'Move those hips'),
  ('GARAGE ROCK', 'Paint my nails black'),
  ('GARAGE ROCK', 'Party'),
  ('GARAGE ROCK', 'Party too hard'),
  ('GARAGE ROCK', 'Play air guitar'),
  ('GARAGE ROCK', 'Play the jukebox all night'),
  ('GARAGE ROCK', 'Play the tambourine'),
  ('GARAGE ROCK', 'Pound tequila from a dirty glass'),
  ('GARAGE ROCK', 'Pull out my old vinyl'),
  ('GARAGE ROCK', 'Revolt'),
  ('GARAGE ROCK', 'Shake some maracas'),
  ('GARAGE ROCK', 'Shake your Money Maker'),
  ('GARAGE ROCK', 'Show off'),
  ('GARAGE ROCK', 'Smoke a cigarette'),
  ('GARAGE ROCK', 'Speed down the highway'),
  ('GARAGE ROCK', 'Stare at the woman in the red dress'),
  ('GARAGE ROCK', 'Start getting rowdy'),
  ('GARAGE ROCK', 'Stomp my feet'),
  ('GARAGE ROCK', 'Surf'),
  ('GARAGE ROCK', 'Sweat'),
  ('GARAGE ROCK', 'Take some pills a hot chick gave me'),
  ('GARAGE ROCK', 'Watch them get what they deserve'),
  ('GARAGE ROCK', 'Wear my hat backwards'),
  ('GARAGE ROCK', 'Wear tie dye'),
  ('GARAGE ROCK', 'Win the fight'),
  ('FEEL GOOD POP', 'Act upbeat'),
  ('FEEL GOOD POP', 'Allow happiness in'),
  ('FEEL GOOD POP', 'Be a better person'),
  ('FEEL GOOD POP', 'Be happy'),
  ('FEEL GOOD POP', 'Be positive'),
  ('FEEL GOOD POP', 'Be proud'),
  ('FEEL GOOD POP', 'Chug a cold one'),
  ('FEEL GOOD POP', 'Clap my hands'),
  ('FEEL GOOD POP', 'Drink a cold one'),
  ('FEEL GOOD POP', 'Drive through the countryside'),
  ('FEEL GOOD POP', 'Drive with the top down'),
  ('FEEL GOOD POP', 'Drive with the windows down'),
  ('FEEL GOOD POP', 'Enjoy a summer evening'),
  ('FEEL GOOD POP', 'Feel good'),
  ('FEEL GOOD POP', 'Feel safe secure + strong'),
  ('POP FUN PARTY', 'Act crazy'),
  ('POP FUN PARTY', 'Act upbeat'),
  ('POP FUN PARTY', 'Allow happiness in'),
  ('POP FUN PARTY', 'Bang my head'),
  ('POP FUN PARTY', 'Be happy'),
  ('POP FUN PARTY', 'Be positive'),
  ('POP FUN PARTY', 'Boogie'),
  ('POP FUN PARTY', 'Boogie down'),
  ('POP FUN PARTY', 'Dance'),
  ('POP FUN PARTY', 'DJ'),
  ('POP FUN PARTY', 'Enjoy a summer evening'),
  ('POP FUN PARTY', 'Feel good'),
  ('POP FUN PARTY', 'Feel groovy'),
  ('POP FUN PARTY', 'Get funky'),
  ('POP FUN PARTY', 'Get in a trance'),
  ('POP FUN PARTY', 'Get real sexy'),
  ('POP FUN PARTY', 'Get some pep in my step'),
  ('POP FUN PARTY', 'Go on vacation'),
  ('POP FUN PARTY', 'Groove'),
  ('POP FUN PARTY', 'Groove with my girl'),
  ('POP FUN PARTY', 'Hit a warehouse party'),
  ('POP FUN PARTY', 'Hit the dance floor'),
  ('POP FUN PARTY', 'Jump'),
  ('POP FUN PARTY', 'Jump around'),
  ('POP FUN PARTY', 'Lie by the pool'),
  ('POP FUN PARTY', 'Party'),
  ('POP FUN PARTY', 'Party till the break of dawn'),
  ('POP FUN PARTY', 'Party too hard'),
  ('POP FUN PARTY', 'Pop bottles in the VIP section'),
  ('POP FUN PARTY', 'Pump my fist'),
  ('POP FUN PARTY', 'Pump my fists'),
  ('POP FUN PARTY', 'Rage all night'),
  ('POP FUN PARTY', 'Rave'),
  ('POP FUN PARTY', 'Rave till sunrise'),
  ('POP FUN PARTY', 'Sunbathe'),
  ('POP FUN PARTY', 'Take some pills a hot chick gave me'),
  ('JAM BAND', 'Achieve my dreams'),
  ('JAM BAND', 'Act like a 5 year old'),
  ('JAM BAND', 'Allow happiness in'),
  ('JAM BAND', 'Allow my mind to wander'),
  ('JAM BAND', 'Bake cookies'),
  ('JAM BAND', 'Be happy'),
  ('JAM BAND', 'Be in a cornfield'),
  ('JAM BAND', 'Be in nature'),
  ('JAM BAND', 'Be one with the universe'),
  ('JAM BAND', 'Chill out'),
  ('JAM BAND', 'Chug a cold one'),
  ('JAM BAND', 'Clap my hands'),
  ('JAM BAND', 'Dance like no one is watching'),
  ('JAM BAND', 'Dance with my hands in the air'),
  ('JAM BAND', 'DOMINATE at Beer Pong!!!'),
  ('JAM BAND', 'Drink'),
  ('JAM BAND', 'Drink a cold one'),
  ('JAM BAND', 'Drop acid'),
  ('JAM BAND', 'Eat BBQ'),
  ('JAM BAND', 'Enjoy a summer evening'),
  ('JAM BAND', 'Feel good'),
  ('JAM BAND', 'Find my inner peace'),
  ('JAM BAND', 'Find myself'),
  ('JAM BAND', 'Find peace'),
  ('JAM BAND', 'Float away'),
  ('JAM BAND', 'Funk it up'),
  ('JAM BAND', 'Get all hipster'),
  ('JAM BAND', 'Get drunk'),
  ('JAM BAND', 'Get high'),
  ('JAM BAND', 'Get hot and sweaty'),
  ('JAM BAND', 'Get in a trance'),
  ('JAM BAND', 'Get my palm read'),
  ('JAM BAND', 'Get real sexy'),
  ('JAM BAND', 'Get sadly drunk'),
  ('JAM BAND', 'Groove with my girl'),
  ('JAM BAND', 'Have a 90''s flashback'),
  ('JAM BAND', 'Have a one night stand'),
  ('JAM BAND', 'Have a picnic'),
  ('JAM BAND', 'Have a picnic in the meadow'),
  ('JAM BAND', 'Hold up a lighter'),
  ('JAM BAND', 'Hug a hippie'),
  ('JAM BAND', 'Jam'),
  ('JAM BAND', 'Jump around'),
  ('JAM BAND', 'Kiss'),
  ('JAM BAND', 'Lay you down by the fire'),
  ('JAM BAND', 'Lie back in a field'),
  ('JAM BAND', 'Love whatever I just inhaled'),
  ('JAM BAND', 'Mellow out'),
  ('JAM BAND', 'One word: HACKYSACK'),
  ('JAM BAND', 'Pick and grin'),
  ('JAM BAND', 'Play air guitar'),
  ('JAM BAND', 'Put your hands together'),
  ('JAM BAND', 'Rage all night'),
  ('JAM BAND', 'Relax'),
  ('JAM BAND', 'Smile and dance and clap my hands'),
  ('JAM BAND', 'Smoke a cigarette'),
  ('JAM BAND', 'Stomp and dance'),
  ('JAM BAND', 'Take my clothes off'),
  ('JAM BAND', 'Take some pills a hot chick gave me'),
  ('JAM BAND', 'Trade my shirt for a grilled cheese'),
  ('JAM BAND', 'Wander around aimlessly'),
  ('JAM BAND', 'Wander the desert'),
  ('JAM BAND', 'Watch cacti'),
  ('JAM BAND', 'Wear tie dye'),
  ('BASIC POSITIVE', 'Achieve my dreams'),
  ('BASIC POSITIVE', 'Allow happiness in'),
  ('BASIC POSITIVE', 'Be happy'),
  ('BASIC POSITIVE', 'Be positive'),
  ('BASIC POSITIVE', 'Better myself'),
  ('BASIC POSITIVE', 'Chill out'),
  ('BASIC POSITIVE', 'Feel safe secure + strong'),
  ('BASIC POSITIVE', 'Find my inner peace'),
  ('BASIC POSITIVE', 'Find myself'),
  ('BASIC POSITIVE', 'Find peace'),
  ('BASIC POSITIVE', 'Go on an adventure'),
  ('BASIC POSITIVE', 'Go on vacation'),
  ('BASIC POSITIVE', 'Have a great day'),
  ('BASIC POSITIVE', 'Lounge'),
  ('BASIC POSITIVE', 'Mellow out'),
  ('BASIC POSITIVE', 'Relax'),
  ('BASIC POSITIVE', 'Smile and dance and clap my hands'),
  ('FEEL GOOD, GROOVY', 'Achieve my dreams'),
  ('FEEL GOOD, GROOVY', 'Allow happiness in'),
  ('FEEL GOOD, GROOVY', 'Attend an event in the city'),
  ('FEEL GOOD, GROOVY', 'Be all saucy'),
  ('FEEL GOOD, GROOVY', 'Be happy'),
  ('FEEL GOOD, GROOVY', 'Be one with the universe'),
  ('FEEL GOOD, GROOVY', 'Be positive'),
  ('FEEL GOOD, GROOVY', 'Better myself'),
  ('FEEL GOOD, GROOVY', 'Call an old friend'),
  ('FEEL GOOD, GROOVY', 'Chill out'),
  ('FEEL GOOD, GROOVY', 'Dance with my hands in the air'),
  ('FEEL GOOD, GROOVY', 'Dress like a pimp'),
  ('FEEL GOOD, GROOVY', 'Embark on a quest'),
  ('FEEL GOOD, GROOVY', 'Explore'),
  ('FEEL GOOD, GROOVY', 'Explore the world'),
  ('FEEL GOOD, GROOVY', 'Feel groovy'),
  ('FEEL GOOD, GROOVY', 'Feel safe secure + strong'),
  ('FEEL GOOD, GROOVY', 'Find my inner peace'),
  ('FEEL GOOD, GROOVY', 'Find myself'),
  ('FEEL GOOD, GROOVY', 'Find peace'),
  ('FEEL GOOD, GROOVY', 'Flirt'),
  ('FEEL GOOD, GROOVY', 'Get captivated by an exotic woman'),
  ('FEEL GOOD, GROOVY', 'Get funky'),
  ('FEEL GOOD, GROOVY', 'Get mad intimate'),
  ('FEEL GOOD, GROOVY', 'Get ready for the weekend'),
  ('FEEL GOOD, GROOVY', 'Go on an adventure'),
  ('FEEL GOOD, GROOVY', 'Go on vacation'),
  ('FEEL GOOD, GROOVY', 'Gossip on my iPhone'),
  ('FEEL GOOD, GROOVY', 'Groove'),
  ('FEEL GOOD, GROOVY', 'Groove with my girl'),
  ('FEEL GOOD, GROOVY', 'Have a great day'),
  ('FEEL GOOD, GROOVY', 'Hit the dance floor'),
  ('FEEL GOOD, GROOVY', 'Lie back in the club'),
  ('FEEL GOOD, GROOVY', 'Lounge'),
  ('FEEL GOOD, GROOVY', 'Mellow out'),
  ('FEEL GOOD, GROOVY', 'Move those hips'),
  ('FEEL GOOD, GROOVY', 'Play with a giant beach ball'),
  ('FEEL GOOD, GROOVY', 'Practice the art of seduction'),
  ('FEEL GOOD, GROOVY', 'Relax'),
  ('FEEL GOOD, GROOVY', 'Shop for shoes'),
  ('FEEL GOOD, GROOVY', 'Sip a martini'),
  ('FEEL GOOD, GROOVY', 'Smile and dance and clap my hands'),
  ('FEEL GOOD, GROOVY', 'Stare at the woman in the red dress'),
  ('GROOVY SOUL', 'Be happy'),
  ('GROOVY SOUL', 'Boogie'),
  ('GROOVY SOUL', 'Boogie down'),
  ('GROOVY SOUL', 'Chill out'),
  ('GROOVY SOUL', 'Clap my hands'),
  ('GROOVY SOUL', 'Dance'),
  ('GROOVY SOUL', 'DJ'),
  ('GROOVY SOUL', 'Dress like a pimp'),
  ('GROOVY SOUL', 'Enjoy a summer evening'),
  ('GROOVY SOUL', 'Feel groovy'),
  ('GROOVY SOUL', 'Get mad intimate'),
  ('GROOVY SOUL', 'Groove'),
  ('GROOVY SOUL', 'Groove with my girl'),
  ('GROOVY SOUL', 'Hit the dance floor'),
  ('GROOVY SOUL', 'Jam'),
  ('TRIPPY', 'Allow my mind to wander'),
  ('TRIPPY', 'Be curious'),
  ('TRIPPY', 'Cause a system malfunction'),
  ('TRIPPY', 'Daydream'),
  ('TRIPPY', 'Dream'),
  ('TRIPPY', 'Drift Away'),
  ('TRIPPY', 'Drop acid'),
  ('TRIPPY', 'Drop acid and eat a taco'),
  ('TRIPPY', 'Enter the Matrix'),
  ('TRIPPY', 'Feel very tense'),
  ('TRIPPY', 'Float away'),
  ('TRIPPY', 'Get high'),
  ('TRIPPY', 'Get lost in video games'),
  ('TRIPPY', 'Go where no man has ever gone before'),
  ('TRIPPY', 'Hit a warehouse party'),
  ('TRIPPY', 'Let my imagination run wild'),
  ('TRIPPY', 'Party too hard'),
  ('TRIPPY', 'Play video games'),
  ('TRIPPY', 'Smoke'),
  ('TRIPPY', 'Space out'),
  ('TRIPPY', 'Use gadgets and electronics'),
  ('LATE NIGHT CHILL', 'Allow happiness in'),
  ('LATE NIGHT CHILL', 'Allow my mind to wander'),
  ('LATE NIGHT CHILL', 'Be happy'),
  ('LATE NIGHT CHILL', 'Be in nature'),
  ('LATE NIGHT CHILL', 'Be one with the universe'),
  ('LATE NIGHT CHILL', 'Cast a spell on you'),
  ('LATE NIGHT CHILL', 'Chill out'),
  ('LATE NIGHT CHILL', 'Feel groovy'),
  ('LATE NIGHT CHILL', 'Find myself'),
  ('LATE NIGHT CHILL', 'Find peace'),
  ('LATE NIGHT CHILL', 'Get high'),
  ('LATE NIGHT CHILL', 'Get in a trance'),
  ('LATE NIGHT CHILL', 'Get mad intimate'),
  ('LATE NIGHT CHILL', 'Get my mind blown'),
  ('LATE NIGHT CHILL', 'Get real sexy'),
  ('LATE NIGHT CHILL', 'Groove'),
  ('LATE NIGHT CHILL', 'Groove with my girl'),
  ('LATE NIGHT CHILL', 'Have an affair'),
  ('LATE NIGHT CHILL', 'Lie back in the club'),
  ('LATE NIGHT CHILL', 'Love whatever I just inhaled'),
  ('LATE NIGHT CHILL', 'Mellow out'),
  ('LATE NIGHT CHILL', 'Order a martini'),
  ('LATE NIGHT CHILL', 'Pop bottles in the VIP section'),
  ('LATE NIGHT CHILL', 'Relax'),
  ('LATE NIGHT CHILL', 'Seduce'),
  ('LATE NIGHT CHILL', 'Share an intimate moment'),
  ('LATE NIGHT CHILL', 'Sip a martini'),
  ('LATE NIGHT CHILL', 'Smoke'),
  ('LATE NIGHT CHILL', 'Stare at the woman in the red dress'),
  ('LATE NIGHT CHILL', 'Take my clothes off'),
  ('LATE NIGHT CHILL', 'Take some pills a hot chick gave me'),
  ('LATE NIGHT CHILL', 'Watch the stars'),
  ('LATE NIGHT CHILL', 'Watch the world go by from a rooftop'),
  ('SEXY SEXY', 'Be smooth'),
  ('SEXY SEXY', 'Chill out'),
  ('SEXY SEXY', 'Drift Away'),
  ('SEXY SEXY', 'Float away'),
  ('SEXY SEXY', 'Get mad intimate'),
  ('SEXY SEXY', 'Get real sexy'),
  ('SEXY SEXY', 'Groove with my girl'),
  ('SEXY SEXY', 'Have a one night stand'),
  ('SEXY SEXY', 'Have an affair'),
  ('SEXY SEXY', 'Lay you down by the fire'),
  ('SEXY SEXY', 'Lounge'),
  ('SEXY SEXY', 'Mellow out'),
  ('SEXY SEXY', 'Order a martini'),
  ('SEXY SEXY', 'Practice the art of seduction'),
  ('SEXY SEXY', 'Relax'),
  ('SEXY SEXY', 'Seduce'),
  ('SEXY SEXY', 'Sip a martini'),
  ('SEXY SEXY', 'Smoke a cigarette in a tuxedo'),
  ('SEXY SEXY', 'Take my clothes off'),
  ('SEXY SEXY', 'Turn down the lights'),
  ('SEXY LOUNGE', 'Attend an event in the city'),
  ('SEXY LOUNGE', 'Be all saucy'),
  ('SEXY LOUNGE', 'Be one with the universe'),
  ('SEXY LOUNGE', 'Be smooth'),
  ('SEXY LOUNGE', 'Call my boyfriend'),
  ('SEXY LOUNGE', 'Chill out'),
  ('SEXY LOUNGE', 'Dress to the nines'),
  ('SEXY LOUNGE', 'Drive slow'),
  ('SEXY LOUNGE', 'Feel good'),
  ('SEXY LOUNGE', 'Feel groovy'),
  ('SEXY LOUNGE', 'Feel safe secure + strong'),
  ('SEXY LOUNGE', 'Find peace'),
  ('SEXY LOUNGE', 'Funk it up'),
  ('SEXY LOUNGE', 'Get close to you'),
  ('SEXY LOUNGE', 'Get high'),
  ('SEXY LOUNGE', 'Get mad intimate'),
  ('SEXY LOUNGE', 'Get real sexy'),
  ('SEXY LOUNGE', 'Groove'),
  ('SEXY LOUNGE', 'Groove with my girl'),
  ('SEXY LOUNGE', 'Have an affair'),
  ('SEXY LOUNGE', 'Hold someone close'),
  ('SEXY LOUNGE', 'Kiss'),
  ('SEXY LOUNGE', 'Lie back in the club'),
  ('SEXY LOUNGE', 'Lay you down by the fire'),
  ('SEXY LOUNGE', 'Let my imagination run wild'),
  ('SEXY LOUNGE', 'Lounge'),
  ('SEXY LOUNGE', 'Love whatever I just inhaled'),
  ('SEXY LOUNGE', 'Mellow out'),
  ('SEXY LOUNGE', 'Move those hips'),
  ('SEXY LOUNGE', 'Pop bottles in the VIP section'),
  ('SEXY LOUNGE', 'Relax'),
  ('SEXY LOUNGE', 'Seduce'),
  ('SEXY LOUNGE', 'Sip a martini'),
  ('SEXY LOUNGE', 'Smoke'),
  ('SEXY LOUNGE', 'Take my clothes off'),
  ('SEXY LOUNGE', 'Turn down the lights'),
  ('EDM RAGER', 'Act crazy'),
  ('EDM RAGER', 'Act upbeat'),
  ('EDM RAGER', 'Allow happiness in'),
  ('EDM RAGER', 'Bang my head'),
  ('EDM RAGER', 'Be happy'),
  ('EDM RAGER', 'Be positive'),
  ('EDM RAGER', 'Boogie'),
  ('EDM RAGER', 'Boogie down'),
  ('EDM RAGER', 'Dance'),
  ('EDM RAGER', 'DJ'),
  ('EDM RAGER', 'Enjoy a summer evening'),
  ('EDM RAGER', 'Feel good'),
  ('EDM RAGER', 'Feel groovy'),
  ('EDM RAGER', 'Get funky'),
  ('EDM RAGER', 'Get in a trance'),
  ('EDM RAGER', 'Get real sexy'),
  ('EDM RAGER', 'Get some pep in my step'),
  ('EDM RAGER', 'Go on vacation'),
  ('EDM RAGER', 'Groove'),
  ('EDM RAGER', 'Groove with my girl'),
  ('EDM RAGER', 'Hit a warehouse party'),
  ('EDM RAGER', 'Hit the dance floor'),
  ('EDM RAGER', 'Jump'),
  ('EDM RAGER', 'Jump around'),
  ('EDM RAGER', 'Lay by the pool'),
  ('EDM RAGER', 'Party'),
  ('EDM RAGER', 'Party till the break of dawn'),
  ('EDM RAGER', 'Party too hard'),
  ('EDM RAGER', 'Pop bottles in the VIP section'),
  ('EDM RAGER', 'Pump my fist'),
  ('EDM RAGER', 'Pump my fists'),
  ('EDM RAGER', 'Rage all night'),
  ('EDM RAGER', 'Rave'),
  ('EDM RAGER', 'Rave till sunrise'),
  ('EDM RAGER', 'Sunbathe'),
  ('EDM RAGER', 'Take some pills a hot chick gave me'),
  ('WARM + FUZZY', 'Allow happiness in'),
  ('WARM + FUZZY', 'Allow my mind to wander'),
  ('WARM + FUZZY', 'Bake cookies'),
  ('WARM + FUZZY', 'Be happy'),
  ('WARM + FUZZY', 'Be positive'),
  ('WARM + FUZZY', 'Call an old friend'),
  ('WARM + FUZZY', 'Call my boyfriend'),
  ('WARM + FUZZY', 'Call my loved ones'),
  ('WARM + FUZZY', 'Chill out'),
  ('WARM + FUZZY', 'Cradle a baby'),
  ('WARM + FUZZY', 'Curl up in a blanket'),
  ('WARM + FUZZY', 'Daydream'),
  ('WARM + FUZZY', 'Dream'),
  ('WARM + FUZZY', 'Drift Away'),
  ('WARM + FUZZY', 'Feel good'),
  ('WARM + FUZZY', 'Feel safe secure + strong'),
  ('WARM + FUZZY', 'Feel sentimental'),
  ('WARM + FUZZY', 'Find myself'),
  ('WARM + FUZZY', 'Find peace'),
  ('WARM + FUZZY', 'Go home'),
  ('WARM + FUZZY', 'Grow old with you'),
  ('WARM + FUZZY', 'Hang out in a coffee shop'),
  ('WARM + FUZZY', 'Look through old pictures'),
  ('WARM + FUZZY', 'Meditate'),
  ('WARM + FUZZY', 'Ponder'),
  ('WARM + FUZZY', 'Reach for the Kleenex'),
  ('WARM + FUZZY', 'Reflect'),
  ('WARM + FUZZY', 'Relax'),
  ('WARM + FUZZY', 'Sleep in the sun'),
  ('WARM + FUZZY', 'Stop worrying'),
  ('WARM + FUZZY', 'Visit old friends'),
  ('WARM + FUZZY', 'Walk in the garden'),
  ('WARM + FUZZY', 'Walk in the snow'),
  ('WARM + FUZZY', 'Walk in the suburbs'),
  ('WARM + FUZZY', 'Walk in the woods'),
  ('WARM + FUZZY', 'Wander the streets'),
  ('WARM + FUZZY', 'Wipe my eyes'),
  ('WARM + FUZZY', 'Write in my diary'),
  ('WARM + FUZZY', 'Yawn like a sleepy baby'),
  ('MILD MELANCHOLY', 'Accept my fate'),
  ('MILD MELANCHOLY', 'Allow happiness in'),
  ('MILD MELANCHOLY', 'Ask for another chance'),
  ('MILD MELANCHOLY', 'Be alone'),
  ('MILD MELANCHOLY', 'Be blue'),
  ('MILD MELANCHOLY', 'Be sad'),
  ('MILD MELANCHOLY', 'Beg forgiveness'),
  ('MILD MELANCHOLY', 'Call an old friend'),
  ('MILD MELANCHOLY', 'Call my boyfriend'),
  ('MILD MELANCHOLY', 'Call my loved ones'),
  ('MILD MELANCHOLY', 'Cry'),
  ('MILD MELANCHOLY', 'Daydream'),
  ('MILD MELANCHOLY', 'Feel defeated'),
  ('MILD MELANCHOLY', 'Feel sad'),
  ('MILD MELANCHOLY', 'Feel sentimental'),
  ('MILD MELANCHOLY', 'Feel sorry for myself'),
  ('MILD MELANCHOLY', 'Find myself'),
  ('MILD MELANCHOLY', 'Find peace'),
  ('MILD MELANCHOLY', 'Get depressed'),
  ('MILD MELANCHOLY', 'Give in'),
  ('MILD MELANCHOLY', 'Give up on us'),
  ('MILD MELANCHOLY', 'Hang my head'),
  ('MILD MELANCHOLY', 'Hold someone close'),
  ('MILD MELANCHOLY', 'Lament'),
  ('MILD MELANCHOLY', 'Look through a photo album'),
  ('MILD MELANCHOLY', 'Look through old pictures'),
  ('MILD MELANCHOLY', 'Mellow out'),
  ('MILD MELANCHOLY', 'Miss the good times'),
  ('MILD MELANCHOLY', 'Miss you'),
  ('MILD MELANCHOLY', 'Move through the world'),
  ('MILD MELANCHOLY', 'Persevere'),
  ('MILD MELANCHOLY', 'Pick up the pieces'),
  ('MILD MELANCHOLY', 'Ponder'),
  ('MILD MELANCHOLY', 'Put my heart on my sleeve'),
  ('MILD MELANCHOLY', 'Reach for the Kleenex'),
  ('MILD MELANCHOLY', 'Reflect'),
  ('MILD MELANCHOLY', 'Remember'),
  ('MILD MELANCHOLY', 'Remember a lost love'),
  ('MILD MELANCHOLY', 'Say goodbye'),
  ('MILD MELANCHOLY', 'Spend time at home'),
  ('MILD MELANCHOLY', 'Try to get over you'),
  ('MILD MELANCHOLY', 'Wander around aimlessly'),
  ('MILD MELANCHOLY', 'Wipe my eyes'),
  ('MILD MELANCHOLY', 'Wish for a better future'),
  ('MILD MELANCHOLY', 'Wish things were different'),
  ('MILD MELANCHOLY', 'Wonder if I will find love'),
  ('MILD MELANCHOLY', 'Wonder what''s next'),
  ('MILD MELANCHOLY', 'Worry'),
  ('MILD MELANCHOLY', 'Write in my diary'),
  ('WICKED SAD', 'Accept my fate'),
  ('WICKED SAD', 'Ask for another chance'),
  ('WICKED SAD', 'Be alone'),
  ('WICKED SAD', 'Be blue'),
  ('WICKED SAD', 'Be realistic'),
  ('WICKED SAD', 'Be sad'),
  ('WICKED SAD', 'Beg forgiveness'),
  ('WICKED SAD', 'Break up'),
  ('WICKED SAD', 'Breathe in and out'),
  ('WICKED SAD', 'Brood'),
  ('WICKED SAD', 'Call my loved ones'),
  ('WICKED SAD', 'Confront my past'),
  ('WICKED SAD', 'Contemplate'),
  ('WICKED SAD', 'Contemplate something deep'),
  ('WICKED SAD', 'Cry'),
  ('WICKED SAD', 'Dont let her go'),
  ('WICKED SAD', 'Face my demons'),
  ('WICKED SAD', 'Feel defeated'),
  ('WICKED SAD', 'Feel sad'),
  ('WICKED SAD', 'Find myself'),
  ('WICKED SAD', 'Get depressed'),
  ('WICKED SAD', 'Give up on us'),
  ('WICKED SAD', 'Go to a funeral'),
  ('WICKED SAD', 'Hang my head'),
  ('WICKED SAD', 'Have a moment'),
  ('WICKED SAD', 'Isolate myself'),
  ('WICKED SAD', 'Lament'),
  ('WICKED SAD', 'Look through old pictures'),
  ('WICKED SAD', 'Meditate'),
  ('WICKED SAD', 'Miss the good times'),
  ('WICKED SAD', 'Miss you'),
  ('WICKED SAD', 'Move on'),
  ('WICKED SAD', 'Never forget'),
  ('WICKED SAD', 'Persevere'),
  ('WICKED SAD', 'Ponder'),
  ('WICKED SAD', 'Reach for the Kleenex'),
  ('WICKED SAD', 'Reflect'),
  ('WICKED SAD', 'Remember'),
  ('WICKED SAD', 'Remember a lost love'),
  ('WICKED SAD', 'Say goodbye'),
  ('WICKED SAD', 'Think about the future'),
  ('WICKED SAD', 'Try to get over you'),
  ('WICKED SAD', 'Win you back'),
  ('WICKED SAD', 'Wipe my eyes'),
  ('WICKED SAD', 'Wish for a better future'),
  ('WICKED SAD', 'Wish things were different'),
  ('DANCE PARTY', 'Achieve my dreams'),
  ('DANCE PARTY', 'Act upbeat'),
  ('DANCE PARTY', 'Allow happiness in'),
  ('DANCE PARTY', 'Attend a ball'),
  ('DANCE PARTY', 'Attend an event in the city'),
  ('DANCE PARTY', 'Bang my head'),
  ('DANCE PARTY', 'Bask in glory'),
  ('DANCE PARTY', 'Be all catty'),
  ('DANCE PARTY', 'Be all saucy'),
  ('DANCE PARTY', 'Be happy'),
  ('DANCE PARTY', 'Be one with the universe'),
  ('DANCE PARTY', 'Be positive'),
  ('DANCE PARTY', 'Belt out a song'),
  ('DANCE PARTY', 'Boogie'),
  ('DANCE PARTY', 'Boogie down'),
  ('DANCE PARTY', 'Clap my hands'),
  ('DANCE PARTY', 'Dance'),
  ('DANCE PARTY', 'Dance in the streets'),
  ('DANCE PARTY', 'Dance like no one is watching'),
  ('DANCE PARTY', 'Dance with my hands in the air'),
  ('DANCE PARTY', 'DJ'),
  ('DANCE PARTY', 'Dream'),
  ('DANCE PARTY', 'Dream big'),
  ('DANCE PARTY', 'Dress like a pimp'),
  ('DANCE PARTY', 'Dress to the nines'),
  ('DANCE PARTY', 'Drink anything with an umbrella in it'),
  ('DANCE PARTY', 'Drive real fast'),
  ('DANCE PARTY', 'Drive with the top down'),
  ('DANCE PARTY', 'Drive with the windows down'),
  ('DANCE PARTY', 'Enjoy a summer evening'),
  ('DANCE PARTY', 'Escape'),
  ('DANCE PARTY', 'Feel good'),
  ('DANCE PARTY', 'Feel groovy'),
  ('DANCE PARTY', 'Feel safe secure + strong'),
  ('DANCE PARTY', 'Funk it up'),
  ('DANCE PARTY', 'Get drunk'),
  ('DANCE PARTY', 'Get mad intimate'),
  ('DANCE PARTY', 'Get ready for the weekend'),
  ('DANCE PARTY', 'Get real sexy'),
  ('DANCE PARTY', 'Go on vacation'),
  ('DANCE PARTY', 'Groove'),
  ('DANCE PARTY', 'Have a great day'),
  ('DANCE PARTY', 'Have a rowdy night out'),
  ('DANCE PARTY', 'Hit a warehouse party'),
  ('DANCE PARTY', 'Hit the beach!'),
  ('DANCE PARTY', 'Hit the dance floor'),
  ('DANCE PARTY', 'Jam'),
  ('DANCE PARTY', 'Jump'),
  ('DANCE PARTY', 'Jump around'),
  ('DANCE PARTY', 'Kick back with a cocktail'),
  ('DANCE PARTY', 'Make an Entrance'),
  ('DANCE PARTY', 'Move those hips'),
  ('DANCE PARTY', 'Order a martini'),
  ('DANCE PARTY', 'Party till the break of dawn'),
  ('DANCE PARTY', 'Party too hard'),
  ('DANCE PARTY', 'Play with a giant beach ball'),
  ('DANCE PARTY', 'Pop bottles in the VIP section'),
  ('DANCE PARTY', 'Put your hands together'),
  ('DANCE PARTY', 'Rage all night'),
  ('DANCE PARTY', 'Rave'),
  ('DANCE PARTY', 'Rave till sunrise'),
  ('DANCE PARTY', 'Reach for the stars'),
  ('DANCE PARTY', 'Rollerblade in South Beach'),
  ('DANCE PARTY', 'Seduce'),
  ('DANCE PARTY', 'Show off'),
  ('DANCE PARTY', 'Show off my Gucci'),
  ('DANCE PARTY', 'Sing in the shower'),
  ('DANCE PARTY', 'Sing into a hairbrush'),
  ('DANCE PARTY', 'Sip a martini'),
  ('DANCE PARTY', 'Smile and dance and clap my hands'),
  ('DANCE PARTY', 'Start getting rowdy'),
  ('DANCE PARTY', 'Take my clothes off'),
  ('DANCE PARTY', 'Take some pills a hot chick gave me'),
  ('DANCE PARTY', 'Walk through a casino like I own the place'),
  ('SILLY LITE TENSION', 'Accept my fate'),
  ('SILLY LITE TENSION', 'Act like a 5 year old'),
  ('SILLY LITE TENSION', 'Ask for another chance'),
  ('SILLY LITE TENSION', 'Be a better person'),
  ('SILLY LITE TENSION', 'Be all catty'),
  ('SILLY LITE TENSION', 'Be all saucy'),
  ('SILLY LITE TENSION', 'Be cheeky'),
  ('SILLY LITE TENSION', 'Be curious'),
  ('SILLY LITE TENSION', 'Be pretentious'),
  ('SILLY LITE TENSION', 'Be realistic'),
  ('SILLY LITE TENSION', 'Be smooth'),
  ('SILLY LITE TENSION', 'Beg forgiveness'),
  ('SILLY LITE TENSION', 'Belong to a secret society'),
  ('SILLY LITE TENSION', 'Betray someone'),
  ('SILLY LITE TENSION', 'Bite my nails'),
  ('SILLY LITE TENSION', 'Call an old friend'),
  ('SILLY LITE TENSION', 'Call her a bitch!'),
  ('SILLY LITE TENSION', 'Collect evidence'),
  ('SILLY LITE TENSION', 'Confront enemies'),
  ('SILLY LITE TENSION', 'Confront my past'),
  ('SILLY LITE TENSION', 'Conspire'),
  ('SILLY LITE TENSION', 'Conspire and configure'),
  ('SILLY LITE TENSION', 'Divulge information'),
  ('SILLY LITE TENSION', 'Explore a dusty attic'),
  ('SILLY LITE TENSION', 'Face my demons'),
  ('SILLY LITE TENSION', 'Feel sorry for myself'),
  ('SILLY LITE TENSION', 'Feel the irony'),
  ('SILLY LITE TENSION', 'Find a way out'),
  ('SILLY LITE TENSION', 'Gather evidence'),
  ('SILLY LITE TENSION', 'Get all self righteous'),
  ('SILLY LITE TENSION', 'Get revenge'),
  ('SILLY LITE TENSION', 'Get to the bottom'),
  ('SILLY LITE TENSION', 'Gossip Gossip Gossip'),
  ('SILLY LITE TENSION', 'Gossip on my iPhone'),
  ('SILLY LITE TENSION', 'Have a moment'),
  ('SILLY LITE TENSION', 'Have a ROM COM fest in my apartment'),
  ('SILLY LITE TENSION', 'Laugh WAY over the top'),
  ('SILLY LITE TENSION', 'Look for clues'),
  ('SILLY LITE TENSION', 'Make a drastic decision'),
  ('SILLY LITE TENSION', 'Make her jealous'),
  ('SILLY LITE TENSION', 'Order a martini'),
  ('SILLY LITE TENSION', 'Pat my own back'),
  ('SILLY LITE TENSION', 'Peak around the corner'),
  ('SILLY LITE TENSION', 'Pick a fight at a charity event'),
  ('SILLY LITE TENSION', 'Plot'),
  ('SILLY LITE TENSION', 'Ponder'),
  ('SILLY LITE TENSION', 'Push back'),
  ('SILLY LITE TENSION', 'Roll your eyes'),
  ('SILLY LITE TENSION', 'Scheme'),
  ('SILLY LITE TENSION', 'Shop for shoes'),
  ('SILLY LITE TENSION', 'Show off my Gucci'),
  ('SILLY LITE TENSION', 'Smirk mischievously'),
  ('SILLY LITE TENSION', 'Snoop around'),
  ('SILLY LITE TENSION', 'Spy'),
  ('SILLY LITE TENSION', 'Stand my ground'),
  ('SILLY LITE TENSION', 'Talk behind their back'),
  ('SILLY LITE TENSION', 'Tell it like it is'),
  ('SILLY LITE TENSION', 'Unveil old secrets'),
  ('SILLY LITE TENSION', 'Watch them get what they deserve'),
  ('SILLY LITE TENSION', 'Wipe my eyes'),
  ('SILLY LITE TENSION', 'Worry'),
  ('SPY MOVIE TENSION', 'Cause a system malfunction'),
  ('SPY MOVIE TENSION', 'Chase the bad guy through the parking garage'),
  ('SPY MOVIE TENSION', 'Collect evidence'),
  ('SPY MOVIE TENSION', 'Conspire'),
  ('SPY MOVIE TENSION', 'Conspire and configure'),
  ('SPY MOVIE TENSION', 'Dance with the enemy'),
  ('SPY MOVIE TENSION', 'Destroy all evidence'),
  ('SPY MOVIE TENSION', 'Dream'),
  ('SPY MOVIE TENSION', 'Drive at night'),
  ('SPY MOVIE TENSION', 'Explore'),
  ('SPY MOVIE TENSION', 'Feel the power'),
  ('SPY MOVIE TENSION', 'Figure out what''s going on'),
  ('SPY MOVIE TENSION', 'Find a way out'),
  ('SPY MOVIE TENSION', 'Find a way to win'),
  ('SPY MOVIE TENSION', 'Find my determination!'),
  ('SPY MOVIE TENSION', 'Gather evidence'),
  ('SPY MOVIE TENSION', 'Get revenge'),
  ('SPY MOVIE TENSION', 'Get to the bottom'),
  ('SPY MOVIE TENSION', 'Infiltrate a terrorist cell'),
  ('SPY MOVIE TENSION', 'Look for clues'),
  ('SPY MOVIE TENSION', 'Move through the world'),
  ('SPY MOVIE TENSION', 'Obtain secret information'),
  ('SPY MOVIE TENSION', 'Perform under pressure'),
  ('SPY MOVIE TENSION', 'Persevere'),
  ('SPY MOVIE TENSION', 'Plan my escape'),
  ('SPY MOVIE TENSION', 'Plot'),
  ('SPY MOVIE TENSION', 'Push back'),
  ('SPY MOVIE TENSION', 'Scheme'),
  ('SPY MOVIE TENSION', 'Search for clues'),
  ('SPY MOVIE TENSION', 'Snoop around'),
  ('SPY MOVIE TENSION', 'Solve the case'),
  ('SPY MOVIE TENSION', 'Solve the mystery'),
  ('SPY MOVIE TENSION', 'Solve the puzzle'),
  ('SPY MOVIE TENSION', 'Think about the future'),
  ('SPY MOVIE TENSION', 'Track the enemy'),
  ('007 CHASE', 'Chase the bad guy through the parking garage'),
  ('007 CHASE', 'Chase through foreign streets'),
  ('007 CHASE', 'Confront enemies'),
  ('007 CHASE', 'Drive at night'),
  ('007 CHASE', 'Drive like hell'),
  ('007 CHASE', 'Drive real fast'),
  ('007 CHASE', 'Feel the power'),
  ('007 CHASE', 'Get into a high speed chase'),
  ('007 CHASE', 'Get lost in video games'),
  ('007 CHASE', 'Get out of the city before it explodes'),
  ('007 CHASE', 'Get to the bottom'),
  ('007 CHASE', 'Have Liam Neeson''s special set of skills'),
  ('007 CHASE', 'Infiltrate a terrorist cell'),
  ('007 CHASE', 'KILL BILL!'),
  ('007 CHASE', 'Lead a high speed pursuit'),
  ('007 CHASE', 'Lock and load'),
  ('007 CHASE', 'Perform under pressure'),
  ('007 CHASE', 'Plan a heist'),
  ('007 CHASE', 'Plan my escape'),
  ('007 CHASE', 'Put two in the chest'),
  ('007 CHASE', 'Ride a motorcycle'),
  ('007 CHASE', 'Rob a bank'),
  ('007 CHASE', 'Run like HELL!!!!'),
  ('007 CHASE', 'Sack a kingdom'),
  ('007 CHASE', 'Save the girl and get the bad guys'),
  ('007 CHASE', 'Shoot Stab + Kill!'),
  ('007 CHASE', 'Speed down the highway'),
  ('007 CHASE', 'Wage war'),
  ('007 CHASE', 'Win the fight'),
  ('SPAGHETTI WESTERN', 'Act defiant'),
  ('SPAGHETTI WESTERN', 'Assemble my sniper rifle'),
  ('SPAGHETTI WESTERN', 'Bask in glory'),
  ('SPAGHETTI WESTERN', 'Be a COWBOY!!'),
  ('SPAGHETTI WESTERN', 'Be awesome in slow motion'),
  ('SPAGHETTI WESTERN', 'Be courageous'),
  ('SPAGHETTI WESTERN', 'Be in Texas'),
  ('SPAGHETTI WESTERN', 'Be in the south'),
  ('SPAGHETTI WESTERN', 'Be proud'),
  ('SPAGHETTI WESTERN', 'Blend in'),
  ('SPAGHETTI WESTERN', 'Blow things up'),
  ('SPAGHETTI WESTERN', 'Brawl'),
  ('SPAGHETTI WESTERN', 'Chug a cold one'),
  ('SPAGHETTI WESTERN', 'Commit a crime'),
  ('SPAGHETTI WESTERN', 'Confront enemies'),
  ('SPAGHETTI WESTERN', 'Conspire'),
  ('SPAGHETTI WESTERN', 'Destroy all evidence'),
  ('SPAGHETTI WESTERN', 'Draw my six-Shooter'),
  ('SPAGHETTI WESTERN', 'Drink a cold one'),
  ('SPAGHETTI WESTERN', 'Drink whiskey'),
  ('SPAGHETTI WESTERN', 'Drive'),
  ('SPAGHETTI WESTERN', 'Drive slow'),
  ('SPAGHETTI WESTERN', 'Duel'),
  ('SPAGHETTI WESTERN', 'Duel in an old western'),
  ('SPAGHETTI WESTERN', 'Embark on a quest'),
  ('SPAGHETTI WESTERN', 'Fight for my freedom'),
  ('SPAGHETTI WESTERN', 'Get drunk in a dive bar'),
  ('SPAGHETTI WESTERN', 'Get out of the city before it explodes'),
  ('SPAGHETTI WESTERN', 'Hang with Tony Bourdain'),
  ('SPAGHETTI WESTERN', 'Lock and load'),
  ('SPAGHETTI WESTERN', 'Plan a heist'),
  ('SPAGHETTI WESTERN', 'Ponder'),
  ('SPAGHETTI WESTERN', 'Pound tequila from a dirty glass'),
  ('SPAGHETTI WESTERN', 'Put on my cowboy boots'),
  ('SPAGHETTI WESTERN', 'Put two in the chest'),
  ('SPAGHETTI WESTERN', 'Ride a horse through the canyon'),
  ('SPAGHETTI WESTERN', 'Ride a motorcycle'),
  ('SPAGHETTI WESTERN', 'Ride off into the sunset'),
  ('SPAGHETTI WESTERN', 'Ride the Hog through the desert'),
  ('SPAGHETTI WESTERN', 'Ride through the desert'),
  ('SPAGHETTI WESTERN', 'Round up a posse'),
  ('SPAGHETTI WESTERN', 'Shoot Stab + Kill!'),
  ('SPAGHETTI WESTERN', 'Track the enemy'),
  ('SPAGHETTI WESTERN', 'Travel on horseback'),
  ('SPAGHETTI WESTERN', 'Wander the desert'),
  ('SPAGHETTI WESTERN', 'Win the fight'),
  ('SPORTS PAK', 'Achieve my dreams'),
  ('SPORTS PAK', 'Act defiant'),
  ('SPORTS PAK', 'Assemble my sniper rifle'),
  ('SPORTS PAK', 'Bang my head'),
  ('SPORTS PAK', 'Bask in glory'),
  ('SPORTS PAK', 'Be awesome in slow motion'),
  ('SPORTS PAK', 'Be courageous'),
  ('SPORTS PAK', 'Be positive'),
  ('SPORTS PAK', 'Blow things up'),
  ('SPORTS PAK', 'Brawl'),
  ('SPORTS PAK', 'Change the world'),
  ('SPORTS PAK', 'Chug a cold one'),
  ('SPORTS PAK', 'Confront enemies'),
  ('SPORTS PAK', 'Dream big'),
  ('SPORTS PAK', 'Drink a cold one'),
  ('SPORTS PAK', 'Face my demons'),
  ('SPORTS PAK', 'Feel the power'),
  ('SPORTS PAK', 'Fight for my freedom'),
  ('SPORTS PAK', 'Fight for the winning goal'),
  ('SPORTS PAK', 'Find a way to win'),
  ('SPORTS PAK', 'Find my determination!'),
  ('SPORTS PAK', 'Get focused'),
  ('SPORTS PAK', 'Go for it!'),
  ('SPORTS PAK', 'Hit the game winning shot'),
  ('SPORTS PAK', 'Ice skate'),
  ('SPORTS PAK', 'Inspire people'),
  ('SPORTS PAK', 'Jump'),
  ('SPORTS PAK', 'Jump around'),
  ('SPORTS PAK', 'Lock and load'),
  ('SPORTS PAK', 'Make an Entrance'),
  ('SPORTS PAK', 'Play N64'),
  ('SPORTS PAK', 'Protect the President'),
  ('SPORTS PAK', 'Pump my fist'),
  ('SPORTS PAK', 'Reach for the stars'),
  ('SPORTS PAK', 'Rise from the ashes victorious'),
  ('SPORTS PAK', 'Rock out'),
  ('SPORTS PAK', 'Save the World'),
  ('SPORTS PAK', 'Stand my ground'),
  ('SPORTS PAK', 'Star in an Adidas commercial'),
  ('SPORTS PAK', 'Start getting rowdy'),
  ('SPORTS PAK', 'Strut'),
  ('SPORTS PAK', 'Tailgate'),
  ('SPORTS PAK', 'Taunt strangers'),
  ('SPORTS PAK', 'Wear my hat backwards'),
  ('SPORTS PAK', 'Win the fight'),
  ('ROCKABILLY', 'Be all saucy'),
  ('ROCKABILLY', 'Be happy'),
  ('ROCKABILLY', 'Boogie'),
  ('ROCKABILLY', 'Chug a cold one'),
  ('ROCKABILLY', 'Clap my hands'),
  ('ROCKABILLY', 'Dance'),
  ('ROCKABILLY', 'Drink'),
  ('ROCKABILLY', 'Drink a cold one'),
  ('ROCKABILLY', 'Drink moonshine'),
  ('ROCKABILLY', 'Drive slow'),
  ('ROCKABILLY', 'Enjoy a summer evening'),
  ('ROCKABILLY', 'Feel good'),
  ('ROCKABILLY', 'Feel groovy'),
  ('ROCKABILLY', 'Get funky'),
  ('ROCKABILLY', 'Get high'),
  ('ROCKABILLY', 'Groove with my girl'),
  ('ROCKABILLY', 'Hang at a speakeasy'),
  ('ROCKABILLY', 'Hang with Tony Bourdain'),
  ('ROCKABILLY', 'Have a rowdy night out'),
  ('ROCKABILLY', 'Jam'),
  ('ROCKABILLY', 'Pimp my ride'),
  ('ROCKABILLY', 'Pound tequila from a dirty glass'),
  ('ROCKABILLY', 'Rock out'),
  ('ROCKABILLY', 'Shoot Pool'),
  ('ROCKABILLY', 'Smoke'),
  ('ROCKABILLY', 'Stomp + Clap'),
  ('ROCKABILLY', 'Strut'),
  ('HIPPY DIPPY', 'Act like I don''t have a trust fund'),
  ('HIPPY DIPPY', 'Allow happiness in'),
  ('HIPPY DIPPY', 'Allow my mind to wander'),
  ('HIPPY DIPPY', 'Bake weed brownies'),
  ('HIPPY DIPPY', 'Be happy'),
  ('HIPPY DIPPY', 'Be in nature'),
  ('HIPPY DIPPY', 'Be one with the universe'),
  ('HIPPY DIPPY', 'Be positive'),
  ('HIPPY DIPPY', 'Breathe in and out'),
  ('HIPPY DIPPY', 'Call my friends "Brah"'),
  ('HIPPY DIPPY', 'Chill out'),
  ('HIPPY DIPPY', 'Chug a cold one'),
  ('HIPPY DIPPY', 'Clap my hands'),
  ('HIPPY DIPPY', 'Dance'),
  ('HIPPY DIPPY', 'Dance like no one is watching'),
  ('HIPPY DIPPY', 'Dance with my hands in the air'),
  ('HIPPY DIPPY', 'Douse in Patchouli oil'),
  ('HIPPY DIPPY', 'Drift Away'),
  ('HIPPY DIPPY', 'Drink a cold one'),
  ('HIPPY DIPPY', 'Drive with the top down'),
  ('HIPPY DIPPY', 'Drop acid and eat a taco'),
  ('HIPPY DIPPY', 'Enjoy a summer evening'),
  ('HIPPY DIPPY', 'Escape'),
  ('HIPPY DIPPY', 'Feel good'),
  ('HIPPY DIPPY', 'Feel groovy'),
  ('HIPPY DIPPY', 'Find my inner peace'),
  ('HIPPY DIPPY', 'Find myself'),
  ('HIPPY DIPPY', 'Find peace'),
  ('HIPPY DIPPY', 'Funk it up'),
  ('HIPPY DIPPY', 'Get all hipster'),
  ('HIPPY DIPPY', 'Get drunk'),
  ('HIPPY DIPPY', 'Get high'),
  ('HIPPY DIPPY', 'Get in a trance'),
  ('HIPPY DIPPY', 'Get my mind blown'),
  ('HIPPY DIPPY', 'Get my palm read'),
  ('HIPPY DIPPY', 'Groove'),
  ('HIPPY DIPPY', 'Groove with my girl'),
  ('HIPPY DIPPY', 'Have a picnic'),
  ('HIPPY DIPPY', 'Have a picnic in the meadow'),
  ('HIPPY DIPPY', 'Hold someone close'),
  ('HIPPY DIPPY', 'Hold up a lighter'),
  ('HIPPY DIPPY', 'Hug a hippie'),
  ('HIPPY DIPPY', 'Jam'),
  ('HIPPY DIPPY', 'Jump around'),
  ('HIPPY DIPPY', 'Kiss'),
  ('HIPPY DIPPY', 'Lie back in a field'),
  ('HIPPY DIPPY', 'Love whatever I just inhaled'),
  ('HIPPY DIPPY', 'Make friendship bracelets'),
  ('HIPPY DIPPY', 'Meditate'),
  ('HIPPY DIPPY', 'Mellow out'),
  ('HIPPY DIPPY', 'Move those hips'),
  ('HIPPY DIPPY', 'One word: HACKYSACK'),
  ('HIPPY DIPPY', 'Party till the break of dawn'),
  ('HIPPY DIPPY', 'Play air guitar'),
  ('HIPPY DIPPY', 'Play the tambourine'),
  ('HIPPY DIPPY', 'Play with a giant beach ball'),
  ('HIPPY DIPPY', 'Put your hands together'),
  ('HIPPY DIPPY', 'Reach for the stars'),
  ('HIPPY DIPPY', 'Relax'),
  ('HIPPY DIPPY', 'Roll a fatty'),
  ('HIPPY DIPPY', 'Shake some maracas'),
  ('HIPPY DIPPY', 'Shake your Money Maker'),
  ('HIPPY DIPPY', 'Sing around the campfire'),
  ('HIPPY DIPPY', 'Smile and dance and clap my hands'),
  ('HIPPY DIPPY', 'Smoke'),
  ('HIPPY DIPPY', 'Space out'),
  ('HIPPY DIPPY', 'Stick sick tricks'),
  ('HIPPY DIPPY', 'Stomp and dance'),
  ('HIPPY DIPPY', 'Tailgate'),
  ('HIPPY DIPPY', 'Take my clothes off'),
  ('HIPPY DIPPY', 'Take some pills a hot chick gave me'),
  ('HIPPY DIPPY', 'Trade my shirt for a grilled cheese'),
  ('HIPPY DIPPY', 'Wander around aimlessly'),
  ('HIPPY DIPPY', 'Wear a wool hat IN THE SUMMER'),
  ('HIPPY DIPPY', 'Wear tie dye'),
  ('EPIC THEME', 'Achieve my dreams'),
  ('EPIC THEME', 'Allow happiness in'),
  ('EPIC THEME', 'Bask in glory'),
  ('EPIC THEME', 'Be awesome in slow motion'),
  ('EPIC THEME', 'Be courageous'),
  ('EPIC THEME', 'Be crowned king'),
  ('EPIC THEME', 'Change the world'),
  ('EPIC THEME', 'Confront enemies'),
  ('EPIC THEME', 'Feel the power'),
  ('EPIC THEME', 'Fight for my country'),
  ('EPIC THEME', 'Fight for my freedom'),
  ('EPIC THEME', 'Fight in the Highlands'),
  ('EPIC THEME', 'Go for it!'),
  ('EPIC THEME', 'Go where no man has ever gone before'),
  ('EPIC THEME', 'Hail the king'),
  ('EPIC THEME', 'Have faith'),
  ('EPIC THEME', 'Have hope'),
  ('EPIC THEME', 'Inspire people'),
  ('EPIC THEME', 'Reach for the stars'),
  ('EPIC THEME', 'Ride off into the sunset'),
  ('EPIC THEME', 'Round up a posse'),
  ('EPIC THEME', 'Sack a kingdom'),
  ('EPIC THEME', 'Save the girl and get the bad guys'),
  ('EPIC THEME', 'Save the World'),
  ('EPIC THEME', 'Survive the Apocalypse'),
  ('EPIC THEME', 'Wage war'),
  ('BENNY HILL SILLY', 'Act like a 5 year old'),
  ('BENNY HILL SILLY', 'Slip on a banana peel'),
  ('BENNY HILL SILLY', 'Spray seltzer in someone''s face'),
  ('BENNY HILL SILLY', 'Throw a pie at someone'),
  ('BENNY HILL SILLY', 'Trip someone'),
  ('OLD TIMEY SALOON', 'Battle'),
  ('OLD TIMEY SALOON', 'Be a COWBOY!!'),
  ('OLD TIMEY SALOON', 'Be all saucy'),
  ('OLD TIMEY SALOON', 'Be in Texas'),
  ('OLD TIMEY SALOON', 'Confront enemies'),
  ('OLD TIMEY SALOON', 'Dance a two step'),
  ('OLD TIMEY SALOON', 'Do the Can-Can'),
  ('OLD TIMEY SALOON', 'Do the Charleston'),
  ('OLD TIMEY SALOON', 'Draw my six-Shooter'),
  ('OLD TIMEY SALOON', 'Drink whiskey'),
  ('OLD TIMEY SALOON', 'Duel in an old western'),
  ('EXTREME TENSION', 'Accept my fate'),
  ('EXTREME TENSION', 'Belong to a secret society'),
  ('EXTREME TENSION', 'Betray my comrade'),
  ('EXTREME TENSION', 'Betray someone'),
  ('EXTREME TENSION', 'Cause a system malfunction'),
  ('EXTREME TENSION', 'Commit a crime'),
  ('EXTREME TENSION', 'Confront enemies'),
  ('EXTREME TENSION', 'Conspire'),
  ('EXTREME TENSION', 'Conspire and configure'),
  ('EXTREME TENSION', 'Destroy all evidence'),
  ('EXTREME TENSION', 'Face horrible consequences'),
  ('EXTREME TENSION', 'Face my demons'),
  ('EXTREME TENSION', 'Face the consequences'),
  ('EXTREME TENSION', 'Feel very tense'),
  ('EXTREME TENSION', 'Figure out what''s going on'),
  ('EXTREME TENSION', 'Find a safe place to hide'),
  ('EXTREME TENSION', 'Find a way out'),
  ('EXTREME TENSION', 'Get out of the city before it explodes'),
  ('EXTREME TENSION', 'Get to the bottom'),
  ('EXTREME TENSION', 'Have Liam Neeson''s special set of skills'),
  ('EXTREME TENSION', 'Hide'),
  ('EXTREME TENSION', 'Hunt down the monster in his own cave'),
  ('EXTREME TENSION', 'Infiltrate a terrorist cell'),
  ('EXTREME TENSION', 'Lock and load'),
  ('EXTREME TENSION', 'Look for clues'),
  ('EXTREME TENSION', 'Make a drastic decision'),
  ('EXTREME TENSION', 'Obtain secret information'),
  ('EXTREME TENSION', 'Peak around the corner'),
  ('EXTREME TENSION', 'Perform under pressure'),
  ('EXTREME TENSION', 'Persevere'),
  ('EXTREME TENSION', 'Plan a heist'),
  ('EXTREME TENSION', 'Plan my escape'),
  ('EXTREME TENSION', 'Pray'),
  ('EXTREME TENSION', 'Put two in the chest'),
  ('EXTREME TENSION', 'Reveal that i''m an undercover agent'),
  ('EXTREME TENSION', 'Revolt'),
  ('EXTREME TENSION', 'Risk my life'),
  ('EXTREME TENSION', 'Run like HELL!!!!'),
  ('EXTREME TENSION', 'Scheme'),
  ('EXTREME TENSION', 'Snoop around'),
  ('EXTREME TENSION', 'Solve the mystery'),
  ('EXTREME TENSION', 'Spy'),
  ('EXTREME TENSION', 'Stand my ground'),
  ('EXTREME TENSION', 'Survive the Apocalypse'),
  ('EXTREME TENSION', 'Track the enemy'),
  ('60’s SCI FI', 'Blow things up'),
  ('60’s SCI FI', 'Cause a system malfunction'),
  ('60’s SCI FI', 'Change the world'),
  ('60’s SCI FI', 'Confront enemies'),
  ('60’s SCI FI', 'Embark on a quest'),
  ('60’s SCI FI', 'Face horrible consequences'),
  ('60’s SCI FI', 'Find a safe place to hide'),
  ('60’s SCI FI', 'Get Abducted by Aliens'),
  ('60’s SCI FI', 'Get out of the city before it explodes'),
  ('60’s SCI FI', 'Go where no man has ever gone before'),
  ('60’s SCI FI', 'Make a drastic decision'),
  ('60’s SCI FI', 'Plan my escape'),
  ('60’s SCI FI', 'Prepare for the robot battle'),
  ('60’s SCI FI', 'Risk my life'),
  ('60’s SCI FI', 'Save the World'),
  ('60’s SCI FI', 'Survive the Apocalypse'),
  ('60’s SCI FI', 'Use gadgets and electronics'),
  ('60’s SCI FI', 'Watch them get what they deserve'),
  ('DRUNKEN WAITS', 'Check into rehab'),
  ('DRUNKEN WAITS', 'Chug a cold one'),
  ('DRUNKEN WAITS', 'Cry in my beer'),
  ('DRUNKEN WAITS', 'Drink a cold one'),
  ('DRUNKEN WAITS', 'Drink whiskey'),
  ('DRUNKEN WAITS', 'Face my demons'),
  ('DRUNKEN WAITS', 'Get drunk'),
  ('DRUNKEN WAITS', 'Get drunk in a dive bar'),
  ('DRUNKEN WAITS', 'Chug a cold one'),
  ('DRUNKEN WAITS', 'Cry in my beer'),
  ('DRUNKEN WAITS', 'Drink a cold one'),
  ('DRUNKEN WAITS', 'Drink whiskey'),
  ('DRUNKEN WAITS', 'Face my demons'),
  ('DRUNKEN WAITS', 'Get drunk'),
  ('DRUNKEN WAITS', 'Get drunk in a dive bar'),
  ('DRUNKEN WAITS', 'Stagger Home'),
  ('MAFIA', 'Accept my fate'),
  ('MAFIA', 'Ask for another chance'),
  ('MAFIA', 'Beg forgiveness'),
  ('MAFIA', 'Belong to a secret society'),
  ('MAFIA', 'Blow things up'),
  ('MAFIA', 'Commit a crime'),
  ('MAFIA', 'Destroy all evidence'),
  ('MAFIA', 'Drink Chianti'),
  ('MAFIA', 'Face the consequences'),
  ('MAFIA', 'Hang at a speakeasy'),
  ('MAFIA', 'Kiss another man on the cheek'),
  ('MAFIA', 'Leave the gun, Take the Canoli'),
  ('MAFIA', 'Play cards in the safe house'),
  ('MAFIA', 'Smile like Bobby D'),
  ('MAFIA', 'Smoke a cuban cigar'),
  ('MAFIA', 'Take a contract'),
  ('MAFIA', 'Wear a black shirt with a white tie'),
  ('MAFIA', 'Wear a fedora'),
  ('MAFIA', 'Wear a pinkie ring'),
  ('SPOOKY THRILLER', 'Hide behind the sofa'),
  ('SPOOKY THRILLER', 'Lock the doors'),
  ('SPOOKY THRILLER', 'Hide under a blanket'),
  ('SPOOKY THRILLER', 'Cover my eyes'),
  ('SPOOKY THRILLER', 'Check under the bed for monsters'),
  ('SPOOKY THRILLER', 'Check under the bed for ghosts'),
  ('SPOOKY THRILLER', 'Check the wardrobes'),
  ('SPOOKY THRILLER', 'Stay in my room'),
  ('SPOOKY THRILLER', 'Cover the mirrors'),
  ('SPOOKY THRILLER', 'Hide!'),
  ('SPOOKY THRILLER', 'Run away'),
  ('SPOOKY THRILLER', 'Scream!'),
  ('SPOOKY THRILLER', 'Call an exorcist'),
  ('SPOOKY THRILLER', 'Call a ghost hunter'),
  ('SPOOKY THRILLER', 'Turn on all the lights'),
  ('SPOOKY THRILLER', 'Hide under the duvet'),
  ('SPOOKY THRILLER', 'Bite my nails'),
  ('SPOOKY THRILLER', 'Keep my eyes shut'),
  ('CHEEKY COMEDY', 'Be happy'),
  ('CHEEKY COMEDY', 'Be cheeky'),
  ('CHEEKY COMEDY', 'Be funny'),
  ('CHEEKY COMEDY', 'Tell a joke'),
  ('CHEEKY COMEDY', 'Act silly'),
  ('CHEEKY COMEDY', 'Act like a five year old'),
  ('CHEEKY COMEDY', 'Lose my inhibitions'),
  ('CHEEKY COMEDY', 'Prank someone'),
  ('CHEEKY COMEDY', 'Act goofy'),
  ('CHEEKY COMEDY', 'Blow up some animal balloons'),
  ('CHEEKY COMEDY', 'Forget my troubles'),
  ('CHEEKY COMEDY', 'Relax'),
  ('CHEEKY COMEDY', 'Enjoy'),
  ('CHEEKY COMEDY', 'Be free'),
  ('CHEEKY COMEDY', 'Skip down the road'),
  ('CHEEKY COMEDY', 'Dance'),
  ('CHEEKY COMEDY', 'Bob my head to the rhythm'),
  ('CHEEKY COMEDY', 'Have fun with my friends'),
  ('CHEEKY COMEDY', 'Be a clown'),
  ('ADVENTURE FILM', 'Pack my bags'),
  ('ADVENTURE FILM', 'Buy a compass'),
  ('ADVENTURE FILM', 'Be cheeky'),
  ('ADVENTURE FILM', 'Be confident'),
  ('ADVENTURE FILM', 'Go on an adventure'),
  ('ADVENTURE FILM', 'Read a map'),
  ('ADVENTURE FILM', 'Live life'),
  ('ADVENTURE FILM', 'Travel the world'),
  ('ADVENTURE FILM', 'Act cool'),
  ('ADVENTURE FILM', 'Buy some sunglasses'),
  ('ADVENTURE FILM', 'Feel the wind in my hair'),
  ('ADVENTURE FILM', 'See new places'),
  ('ADVENTURE FILM', 'Explore'),
  ('ADVENTURE FILM', 'Take my friends and fly to somewhere new'),
  ('ADVENTURE FILM', 'Go on a mission'),
  ('ADVENTURE FILM', 'Get a pair of night vision goggles'),
  ('ADVENTURE FILM', 'Investigate'),
  ('ADVENTURE FILM', 'Chase after nuts'),
  ('ADVENTURE FILM', 'Go to the jungle'),
  ('ADVENTURE FILM', 'Make friends with some meerkats'),
  ('ADVENTURE FILM', 'Go on a special mission with some penguins'),
  ('ADVENTURE FILM', 'Hide inside a container'),
  ('ADVENTURE FILM', 'Get on a submarine'),
  ('ADVENTURE FILM', 'Befriend a mammoth'),
  ('ADVENTURE FILM', 'Save the world'),
  ('ADVENTURE FILM', 'Explore a hidden cave'),
  ('ADVENTURE FILM', 'Go to the zoo'),
  ('ADVENTURE FILM', 'Escape from the zoo'),
  ('ADVENTURE FILM', 'Escape from prison'),
  ('ADVENTURE FILM', 'Be free'),
  ('ADVENTURE FILM', 'Be adventurous'),
  ('DARK COMEDY', 'Smirk mischievously'),
  ('DARK COMEDY', 'Be curious'),
  ('DARK COMEDY', 'Be smooth'),
  ('DARK COMEDY', 'Find my most trusted friend'),
  ('DARK COMEDY', 'Steal a priceless painting'),
  ('DARK COMEDY', 'Snoop around'),
  ('DARK COMEDY', 'Have a secret meeting in the lobby'),
  ('DARK COMEDY', 'Be undercover'),
  ('DARK COMEDY', 'meet with a Russian spy'),
  ('DARK COMEDY', 'Wear a long dark coat and sunglasses even though it isn’t sunny'),
  ('DARK COMEDY', 'Be a frenemy'),
  ('DARK COMEDY', 'Deceive all suspects'),
  ('DARK COMEDY', 'Be charming'),
  ('DARK COMEDY', 'Play detective'),
  ('DARK COMEDY', 'Operate behind curtains'),
  ('DARK COMEDY', 'Be amusing'),
  ('DARK COMEDY', 'Take the back street'),
  ('DARK COMEDY', 'Explore dark tunnels'),
  ('DARK COMEDY', 'Be a smooth operator'),
  ('DARK COMEDY', 'Have a fake British accent'),
  ('DARK COMEDY', 'Set up a telephone meeting with the Queen'),
  ('DARK COMEDY', 'Bribe the concierge'),
  ('DARK COMEDY', 'Be funny'),
  ('DARK COMEDY', 'Have a dark sense of humour'),
  ('DARK COMEDY', 'Solve a murder mystery'),
  ('DARK COMEDY', 'Operate undetected'),
  ('DARK COMEDY', 'Travel back in time to old postcard Europe'),
  ('DARK COMEDY', 'Be involved in some dark plotting'),
  ('DARK COMEDY', 'Get sweet revenge'),
  ('DARK COMEDY', 'Conspire to free someone from prison'),
  ('ASIAN', 'Explore Chinatown'),
  ('ASIAN', 'Travel to Asia'),
  ('ASIAN', 'Be a Samurai'),
  ('ASIAN', 'Be a Geisha'),
  ('ASIAN', 'Eat exotic food'),
  ('ASIAN', 'Go sight seeing in Tokyo'),
  ('ASIAN', 'Climb Mount Fuji'),
  ('ASIAN', 'Walk through a park full of cherry blossom trees'),
  ('ASIAN', 'Make friends with some pandas'),
  ('ASIAN', 'Learn Kung Fu'),
  ('ASIAN', 'Practice the art of Feng Shui'),
  ('ASIAN', 'Order the dumplings'),
  ('ASIAN', '2 words: Mai Tai!'),
  ('FANTASY MAGICAL', 'Put on my cloak of invisibility'),
  ('FANTASY MAGICAL', 'Travel to a mysterious location'),
  ('FANTASY MAGICAL', 'Cast a spell'),
  ('FANTASY MAGICAL', 'Fly on my broomstick'),
  ('FANTASY MAGICAL', 'Have a pet owl'),
  ('FANTASY MAGICAL', 'Fight against the darkness'),
  ('FANTASY MAGICAL', 'Meet magical creatures'),
  ('FANTASY MAGICAL', 'Explore the forest after dark'),
  ('FANTASY MAGICAL', 'Time travel'),
  ('FANTASY MAGICAL', 'Have magical powers'),
  ('FANTASY MAGICAL', 'Explore the hallways after dark'),
  ('FANTASY MAGICAL', 'Get up to no good'),
  ('FANTASY MAGICAL', 'Make objects fly'),
  ('FANTASY MAGICAL', 'Be righteous'),
  ('MIDDLE EASTERN', 'Explore Exotic Locations'),
  ('MIDDLE EASTERN', 'Go to the market to buy spices'),
  ('MIDDLE EASTERN', 'Ride a Magic Carpet'),
  ('MIDDLE EASTERN', 'Experience a golden sunset'),
  ('MIDDLE EASTERN', 'Ride a camel'),
  ('MIDDLE EASTERN', 'Explore the desert'),
  ('MIDDLE EASTERN', 'Visit a mosque'),
  ('MIDDLE EASTERN', 'Wear Harem Pants'),
  ('MIDDLE EASTERN', 'Read One Thousand and One Nights'),
  ('MIDDLE EASTERN', 'Buy a Persian Rug'),
  ('MIDDLE EASTERN', 'Eat Tebouleh'),
  ('MIDDLE EASTERN', 'One word: FALAFEL'),
  ('KINDA MYSTERIOUS', 'Belong to a secret society'),
  ('KINDA MYSTERIOUS', 'Cause a system malfunction'),
  ('KINDA MYSTERIOUS', 'Check under the bed for ghosts'),
  ('KINDA MYSTERIOUS', 'Collect evidence'),
  ('KINDA MYSTERIOUS', 'Conspire'),
  ('KINDA MYSTERIOUS', 'Conspire and configure'),
  ('KINDA MYSTERIOUS', 'Destroy all evidence'),
  ('KINDA MYSTERIOUS', 'Fire up the shredder'),
  ('KINDA MYSTERIOUS', 'Divulge information'),
  ('KINDA MYSTERIOUS', 'Find a way out'),
  ('KINDA MYSTERIOUS', 'Gather evidence'),
  ('KINDA MYSTERIOUS', 'Get focused'),
  ('KINDA MYSTERIOUS', 'Get to the bottom'),
  ('KINDA MYSTERIOUS', 'Lock and load'),
  ('KINDA MYSTERIOUS', 'Move through the world'),
  ('KINDA MYSTERIOUS', 'Obtain secret information'),
  ('KINDA MYSTERIOUS', 'Plot'),
  ('KINDA MYSTERIOUS', 'Feel the weirdness'),
  ('KINDA MYSTERIOUS', 'Move slowly and carefully'),
  ('KINDA MYSTERIOUS', 'Search for clues'),
  ('KINDA MYSTERIOUS', 'Snoop around'),
  ('KINDA MYSTERIOUS', 'You’re wondering what the HELL is going on'),
  ('ZEN', 'Chant Ohm'),
  ('ZEN', 'Go on a weekend retreat'),
  ('ZEN', 'Get a massage'),
  ('ZEN', 'Get a facial'),
  ('ZEN', 'Have a spa weekend with the girls'),
  ('ZEN', 'Take a yoga class'),
  ('ZEN', 'Fall asleep during Shavasana'),
  ('ZEN', 'Buy essential oils'),
  ('ZEN', 'Shop for yoga pants'),
  ('ZEN', 'Sip herbal tea'),
  ('ZEN', 'Become a vegan'),
  ('ZEN', 'Align my Chakras'),
  ('ZEN', 'Be one with the universe'),
  ('ZEN', 'Meditate'),
  ('ZEN', 'Reflect'),
  ('ZEN', 'Find inner peace'),
  ('ZEN', 'Read inspirational memes'),
  ('ZEN', 'Release toxins'),
  ('ZEN', 'Start a juice cleanse'),
  ('ZEN', 'Wear Birkenstocks'),
  ('ZEN', 'Drink Kombucha'),
  ('ZEN', 'Burn incense'),
  ('ZEN', 'Do a headstand'),
  ('ZEN', 'Go through the healing process'),
  ('ZEN', 'Grow as a human being'),
  ('CHILL OUT', 'Take a nap in a hammock'),
  ('CHILL OUT', 'Hangout in a coffee shop'),
  ('CHILL OUT', 'Relax'),
  ('CHILL OUT', 'Sleep in the sun'),
  ('CHILL OUT', 'Watch the stars'),
  ('CHILL OUT', 'Allow happiness in'),
  ('CHILL OUT', 'Allow my mind to wander'),
  ('CHILL OUT', 'Be happy'),
  ('CHILL OUT', 'Be in nature'),
  ('CHILL OUT', 'Be one with the universe'),
  ('CHILL OUT', 'Feel groovy'),
  ('CHILL OUT', 'Find myself'),
  ('CHILL OUT', 'Find inner peace'),
  ('CHILL OUT', 'Get high'),
  ('CHILL OUT', 'Get drunk'),
  ('CHILL OUT', 'Love whatever I just inhaled'),
  ('CHILL OUT', 'Watch the world from a rooftop'),
  ('CHILL OUT', 'Lay under a palm tree'),
  ('CHILL OUT', 'Sip a margarita'),
  ('CHILL OUT', 'Smile and dance and clap my hands'),
  ('CHILL OUT', 'Mellow out'),
  ('CHILL OUT', 'Chill in front of a fire'),
  ('CHILL OUT', 'Have a picnic in a meadow'),
  ('CHILL OUT', 'Float away'),
  ('CHILL OUT', 'Feel good'),
  ('CHILL OUT', 'Enjoy a summer evening'),
  ('CHILL OUT', 'Eat BBQ'),
  ('CHILL OUT', 'Drink'),
  ('CHILL OUT', 'Drink a cold one'),
  ('CHILL OUT', 'Feel good'),
  ('CHILL OUT', 'Go wine tasting'),
  ('CHILL OUT', 'Be in a cornfield'),
  ('CHILL OUT', 'Go birdwatching'),
  ('CLASSIC ROCK', 'Score backstage passes'),
  ('CLASSIC ROCK', 'Flirt with the drummer'),
  ('CLASSIC ROCK', 'Push to the front of the crowd'),
  ('CLASSIC ROCK', 'Tailgate'),
  ('CLASSIC ROCK', 'Get drunk'),
  ('CLASSIC ROCK', 'Get drunk in a dive bar'),
  ('CLASSIC ROCK', 'Get high'),
  ('CLASSIC ROCK', 'Get hot and sweaty'),
  ('CLASSIC ROCK', 'Get my mind blown'),
  ('CLASSIC ROCK', 'Get ready for the weekend'),
  ('CLASSIC ROCK', 'Be a golden god'),
  ('CLASSIC ROCK', 'Have a one night stand'),
  ('CLASSIC ROCK', 'Listen to old Stones records'),
  ('CLASSIC ROCK', 'Party'),
  ('CLASSIC ROCK', 'Play air guitar'),
  ('CLASSIC ROCK', 'Pull out my old vinyl'),
  ('CLASSIC ROCK', 'Play video games'),
  ('CLASSIC ROCK', 'Go for it!'),
  ('CLASSIC ROCK', 'Feel good'),
  ('CLASSIC ROCK', 'Drink whiskey'),
  ('CLASSIC ROCK', 'Bang my head'),
  ('CLASSIC ROCK', 'Be positive'),
  ('CLASSIC ROCK', 'Drive real fast'),
  ('CLASSIC ROCK', 'Drive with the windows down'),
  ('CLASSIC ROCK', 'Pump my fist'),
  ('CLASSIC ROCK', 'Shake your money maker'),
  ('CLASSIC ROCK', 'Take some pills a hot chick gave me'),
  ('CLASSIC ROCK', 'Allow my mind to wander'),
  ('CLASSIC ROCK', 'Be one with the music'),
  ('CLASSIC ROCK', 'Clap my hands'),
  ('CLASSIC ROCK', 'Dance like no one is watching'),
  ('CLASSIC ROCK', 'Enjoy a summer evening'),
  ('CLASSIC ROCK', 'Get sadly drunk'),
  ('CLASSIC ROCK', 'Groove with my girl'),
  ('CLASSIC ROCK', 'Take my clothes off'),
  ('CLASSIC ROCK', 'Grow hydroponic pot'),
  ('CLASSIC ROCK', 'Get captivated'),
  ('CLASSIC ROCK', 'Blow money on a concert tee-shirt'),
  ('CLASSIC ROCK', 'Drop acid')
) AS v(pak, phr)
JOIN mmw_metapaks m ON m.name = v.pak
JOIN mmw_phrases p ON p.phrase = v.phr
ON CONFLICT DO NOTHING;